//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ZTest01.vn.gov.gdt.daotaonhantokhai.KQuaGDichService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://www.w3.org/ns/ws-policy' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="KQuaGDichService", Namespace="http://kquagdich.van.gdt.gov.vn/")]
    public partial class KQuaGDichService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback traKQuaGDichOperationCompleted;
        
        private System.Threading.SendOrPostCallback traKQuaPhienGDichOperationCompleted;
        
        private System.Threading.SendOrPostCallback traTTinMaSoThueOperationCompleted;
        
        private System.Threading.SendOrPostCallback traTThaiMaSoThueOperationCompleted;
        
        private System.Threading.SendOrPostCallback traDanhMucOperationCompleted;
        
        private System.Threading.SendOrPostCallback traDsachTKhaiLoiOperationCompleted;
        
        private System.Threading.SendOrPostCallback traTTinLoiTKhaiOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public KQuaGDichService() {
            this.Url = global::ZTest01.Properties.Settings.Default.ZTest01_vn_gov_gdt_daotaonhantokhai_KQuaGDichServicePort_KQuaGDichService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event traKQuaGDichCompletedEventHandler traKQuaGDichCompleted;
        
        /// <remarks/>
        public event traKQuaPhienGDichCompletedEventHandler traKQuaPhienGDichCompleted;
        
        /// <remarks/>
        public event traTTinMaSoThueCompletedEventHandler traTTinMaSoThueCompleted;
        
        /// <remarks/>
        public event traTThaiMaSoThueCompletedEventHandler traTThaiMaSoThueCompleted;
        
        /// <remarks/>
        public event traDanhMucCompletedEventHandler traDanhMucCompleted;
        
        /// <remarks/>
        public event traDsachTKhaiLoiCompletedEventHandler traDsachTKhaiLoiCompleted;
        
        /// <remarks/>
        public event traTTinLoiTKhaiCompletedEventHandler traTTinLoiTKhaiCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://kquagdich.van.gdt.gov.vn/", ResponseNamespace="http://kquagdich.van.gdt.gov.vn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", DataType="anyURI")]
        public string traKQuaGDich([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string maGDich) {
            object[] results = this.Invoke("traKQuaGDich", new object[] {
                        maGDich});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void traKQuaGDichAsync(string maGDich) {
            this.traKQuaGDichAsync(maGDich, null);
        }
        
        /// <remarks/>
        public void traKQuaGDichAsync(string maGDich, object userState) {
            if ((this.traKQuaGDichOperationCompleted == null)) {
                this.traKQuaGDichOperationCompleted = new System.Threading.SendOrPostCallback(this.OntraKQuaGDichOperationCompleted);
            }
            this.InvokeAsync("traKQuaGDich", new object[] {
                        maGDich}, this.traKQuaGDichOperationCompleted, userState);
        }
        
        private void OntraKQuaGDichOperationCompleted(object arg) {
            if ((this.traKQuaGDichCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.traKQuaGDichCompleted(this, new traKQuaGDichCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://kquagdich.van.gdt.gov.vn/", ResponseNamespace="http://kquagdich.van.gdt.gov.vn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", DataType="anyURI")]
        public string traKQuaPhienGDich([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string ngayGDich) {
            object[] results = this.Invoke("traKQuaPhienGDich", new object[] {
                        ngayGDich});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void traKQuaPhienGDichAsync(string ngayGDich) {
            this.traKQuaPhienGDichAsync(ngayGDich, null);
        }
        
        /// <remarks/>
        public void traKQuaPhienGDichAsync(string ngayGDich, object userState) {
            if ((this.traKQuaPhienGDichOperationCompleted == null)) {
                this.traKQuaPhienGDichOperationCompleted = new System.Threading.SendOrPostCallback(this.OntraKQuaPhienGDichOperationCompleted);
            }
            this.InvokeAsync("traKQuaPhienGDich", new object[] {
                        ngayGDich}, this.traKQuaPhienGDichOperationCompleted, userState);
        }
        
        private void OntraKQuaPhienGDichOperationCompleted(object arg) {
            if ((this.traKQuaPhienGDichCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.traKQuaPhienGDichCompleted(this, new traKQuaPhienGDichCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://kquagdich.van.gdt.gov.vn/", ResponseNamespace="http://kquagdich.van.gdt.gov.vn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public viewTin traTTinMaSoThue([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string maSoThue) {
            object[] results = this.Invoke("traTTinMaSoThue", new object[] {
                        maSoThue});
            return ((viewTin)(results[0]));
        }
        
        /// <remarks/>
        public void traTTinMaSoThueAsync(string maSoThue) {
            this.traTTinMaSoThueAsync(maSoThue, null);
        }
        
        /// <remarks/>
        public void traTTinMaSoThueAsync(string maSoThue, object userState) {
            if ((this.traTTinMaSoThueOperationCompleted == null)) {
                this.traTTinMaSoThueOperationCompleted = new System.Threading.SendOrPostCallback(this.OntraTTinMaSoThueOperationCompleted);
            }
            this.InvokeAsync("traTTinMaSoThue", new object[] {
                        maSoThue}, this.traTTinMaSoThueOperationCompleted, userState);
        }
        
        private void OntraTTinMaSoThueOperationCompleted(object arg) {
            if ((this.traTTinMaSoThueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.traTTinMaSoThueCompleted(this, new traTTinMaSoThueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://kquagdich.van.gdt.gov.vn/", ResponseNamespace="http://kquagdich.van.gdt.gov.vn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string traTThaiMaSoThue([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string maSoThue) {
            object[] results = this.Invoke("traTThaiMaSoThue", new object[] {
                        maSoThue});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void traTThaiMaSoThueAsync(string maSoThue) {
            this.traTThaiMaSoThueAsync(maSoThue, null);
        }
        
        /// <remarks/>
        public void traTThaiMaSoThueAsync(string maSoThue, object userState) {
            if ((this.traTThaiMaSoThueOperationCompleted == null)) {
                this.traTThaiMaSoThueOperationCompleted = new System.Threading.SendOrPostCallback(this.OntraTThaiMaSoThueOperationCompleted);
            }
            this.InvokeAsync("traTThaiMaSoThue", new object[] {
                        maSoThue}, this.traTThaiMaSoThueOperationCompleted, userState);
        }
        
        private void OntraTThaiMaSoThueOperationCompleted(object arg) {
            if ((this.traTThaiMaSoThueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.traTThaiMaSoThueCompleted(this, new traTThaiMaSoThueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://kquagdich.van.gdt.gov.vn/", ResponseNamespace="http://kquagdich.van.gdt.gov.vn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", DataType="anyURI")]
        public string traDanhMuc([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string maLoaiDMuc) {
            object[] results = this.Invoke("traDanhMuc", new object[] {
                        maLoaiDMuc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void traDanhMucAsync(string maLoaiDMuc) {
            this.traDanhMucAsync(maLoaiDMuc, null);
        }
        
        /// <remarks/>
        public void traDanhMucAsync(string maLoaiDMuc, object userState) {
            if ((this.traDanhMucOperationCompleted == null)) {
                this.traDanhMucOperationCompleted = new System.Threading.SendOrPostCallback(this.OntraDanhMucOperationCompleted);
            }
            this.InvokeAsync("traDanhMuc", new object[] {
                        maLoaiDMuc}, this.traDanhMucOperationCompleted, userState);
        }
        
        private void OntraDanhMucOperationCompleted(object arg) {
            if ((this.traDanhMucCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.traDanhMucCompleted(this, new traDanhMucCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://kquagdich.van.gdt.gov.vn/", ResponseNamespace="http://kquagdich.van.gdt.gov.vn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", DataType="anyURI")]
        public string traDsachTKhaiLoi([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string ngayTraLoi) {
            object[] results = this.Invoke("traDsachTKhaiLoi", new object[] {
                        ngayTraLoi});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void traDsachTKhaiLoiAsync(string ngayTraLoi) {
            this.traDsachTKhaiLoiAsync(ngayTraLoi, null);
        }
        
        /// <remarks/>
        public void traDsachTKhaiLoiAsync(string ngayTraLoi, object userState) {
            if ((this.traDsachTKhaiLoiOperationCompleted == null)) {
                this.traDsachTKhaiLoiOperationCompleted = new System.Threading.SendOrPostCallback(this.OntraDsachTKhaiLoiOperationCompleted);
            }
            this.InvokeAsync("traDsachTKhaiLoi", new object[] {
                        ngayTraLoi}, this.traDsachTKhaiLoiOperationCompleted, userState);
        }
        
        private void OntraDsachTKhaiLoiOperationCompleted(object arg) {
            if ((this.traDsachTKhaiLoiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.traDsachTKhaiLoiCompleted(this, new traDsachTKhaiLoiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://kquagdich.van.gdt.gov.vn/", ResponseNamespace="http://kquagdich.van.gdt.gov.vn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public mesgTKError traTTinLoiTKhai([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string maGDich) {
            object[] results = this.Invoke("traTTinLoiTKhai", new object[] {
                        maGDich});
            return ((mesgTKError)(results[0]));
        }
        
        /// <remarks/>
        public void traTTinLoiTKhaiAsync(string maGDich) {
            this.traTTinLoiTKhaiAsync(maGDich, null);
        }
        
        /// <remarks/>
        public void traTTinLoiTKhaiAsync(string maGDich, object userState) {
            if ((this.traTTinLoiTKhaiOperationCompleted == null)) {
                this.traTTinLoiTKhaiOperationCompleted = new System.Threading.SendOrPostCallback(this.OntraTTinLoiTKhaiOperationCompleted);
            }
            this.InvokeAsync("traTTinLoiTKhai", new object[] {
                        maGDich}, this.traTTinLoiTKhaiOperationCompleted, userState);
        }
        
        private void OntraTTinLoiTKhaiOperationCompleted(object arg) {
            if ((this.traTTinLoiTKhaiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.traTTinLoiTKhaiCompleted(this, new traTTinLoiTKhaiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kquagdich.services.van.ihtkk.seatechit/types")]
    public partial class viewTin {
        
        private string fullNameField;
        
        private string tinField;
        
        private string payTaxOfficeIdField;
        
        private string payTaxOfficeNameField;
        
        private string payTaxOfficeAbbreviationField;
        
        private string depaIdField;
        
        private string emailField;
        
        private string telField;
        
        private string faxField;
        
        private string provField;
        
        private string distField;
        
        private string addrField;
        
        private string certSerialNumberField;
        
        private string finaStartDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tin {
            get {
                return this.tinField;
            }
            set {
                this.tinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string payTaxOfficeId {
            get {
                return this.payTaxOfficeIdField;
            }
            set {
                this.payTaxOfficeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string payTaxOfficeName {
            get {
                return this.payTaxOfficeNameField;
            }
            set {
                this.payTaxOfficeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string payTaxOfficeAbbreviation {
            get {
                return this.payTaxOfficeAbbreviationField;
            }
            set {
                this.payTaxOfficeAbbreviationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string depaId {
            get {
                return this.depaIdField;
            }
            set {
                this.depaIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tel {
            get {
                return this.telField;
            }
            set {
                this.telField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string prov {
            get {
                return this.provField;
            }
            set {
                this.provField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dist {
            get {
                return this.distField;
            }
            set {
                this.distField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string addr {
            get {
                return this.addrField;
            }
            set {
                this.addrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string certSerialNumber {
            get {
                return this.certSerialNumberField;
            }
            set {
                this.certSerialNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string finaStartDate {
            get {
                return this.finaStartDateField;
            }
            set {
                this.finaStartDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kquagdich.services.van.ihtkk.seatechit/types")]
    public partial class mesgTKError {
        
        private string tthaiField;
        
        private string tbaoloiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tthai {
            get {
                return this.tthaiField;
            }
            set {
                this.tthaiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI")]
        public string tbaoloi {
            get {
                return this.tbaoloiField;
            }
            set {
                this.tbaoloiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void traKQuaGDichCompletedEventHandler(object sender, traKQuaGDichCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class traKQuaGDichCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal traKQuaGDichCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void traKQuaPhienGDichCompletedEventHandler(object sender, traKQuaPhienGDichCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class traKQuaPhienGDichCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal traKQuaPhienGDichCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void traTTinMaSoThueCompletedEventHandler(object sender, traTTinMaSoThueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class traTTinMaSoThueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal traTTinMaSoThueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public viewTin Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((viewTin)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void traTThaiMaSoThueCompletedEventHandler(object sender, traTThaiMaSoThueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class traTThaiMaSoThueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal traTThaiMaSoThueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void traDanhMucCompletedEventHandler(object sender, traDanhMucCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class traDanhMucCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal traDanhMucCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void traDsachTKhaiLoiCompletedEventHandler(object sender, traDsachTKhaiLoiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class traDsachTKhaiLoiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal traDsachTKhaiLoiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void traTTinLoiTKhaiCompletedEventHandler(object sender, traTTinLoiTKhaiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class traTTinLoiTKhaiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal traTTinLoiTKhaiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public mesgTKError Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((mesgTKError)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591