using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace idn.Skycic.Inventory.Utils
{
    public class Error
    {
        public static string GetErrDict(string errCode)
        {
            string errContent = "";
            Dictionary<string, string> errDict = new Dictionary<string, string>() { 
////{"Ma loi","Dich loi!"},



{"Erridn.Skycic.Inventory.Mst_Brand_CheckDB_BrandCodeNotFound","Không tìm thấy mã Brand"},
{"Erridn.Skycic.Inventory.Mst_Brand_CheckDB_BrandCodeExist","Mã Brand này đã tồn tại"},
{"Erridn.Skycic.Inventory.Mst_Brand_CheckDB_FlagActiveNotMatched","Trạng thái brand không phù hợp "},
{"Erridn.Skycic.Inventory.Mst_Brand_Get","Lỗi khi lấy dữ liệu từ mã Brand"},
{"Erridn.Skycic.Inventory.Mst_Brand_Create","Lỗi khi tạo brand"},
{"Erridn.Skycic.Inventory.Mst_Brand_Create_InvalidBrandCode","Lỗi tạo mã brand không hợp lệ"},
{"Erridn.Skycic.Inventory.Mst_Brand_Create_InvalidBrandName","Lỗi tạo tên brand không hợp lệ"},
{"Erridn.Skycic.Inventory.Mst_Brand_Update","Lỗi cập nhật brand"},
{"Erridn.Skycic.Inventory.Mst_Brand_Update_InvalidBrandName","Lỗi cập nhật tên  brand không hợp lệ"},
{"Erridn.Skycic.Inventory.Mst_Brand_Delete","Lỗi khi xóa brand"},
{"Erridn.Skycic.Inventory.WAS_Mst_Brand_Get","Lỗi lấy dữ liệu từ nhãn hiệu"},
{"Erridn.Skycic.Inventory.WAS_Mst_Brand_Create","Lỗi tạo mới nhãn hiệu"},
{"Erridn.Skycic.Inventory.WAS_Mst_Brand_Update","Lỗi cập nhật nhãn hiệu"},
{"Erridn.Skycic.Inventory.WAS_Mst_Brand_Delete","Lỗi xóa nhãn hiệu"},
{"Erridn.Skycic.Inventory.Mst_Model_CheckDB_ModelCodeNotFound","check DB không tìm thấy mã Model"},
{"Erridn.Skycic.Inventory.Mst_Model_CheckDB_ModelCodeExist","check DB mã model này đã tồn tại"},
{"Erridn.Skycic.Inventory.Mst_Model_CheckDB_FlagActiveNotMatched","Trạng thái model không hợp lệ"},
{"Erridn.Skycic.Inventory.Mst_Model_Get","Lỗi khi lấy dữ liệu từ mã model"},
{"Erridn.Skycic.Inventory.WAS_Mst_Model_Get","Lỗi khi lấy dữ liệu từ mã model"},
{"Erridn.Skycic.Inventory.WAS_Mst_Model_Create","Lỗi tạo mã model không hợp lệ"},
{"Erridn.Skycic.Inventory.WAS_Mst_Model_Update","Lỗi cập nhật mã model"},
{"Erridn.Skycic.Inventory.WAS_Mst_Model_Delete","Lỗi khi xóa model"},
{"Erridn.Skycic.Inventory.Mst_Model_Create","Lỗi khi tạo model"},
{"Erridn.Skycic.Inventory.Mst_Model_Create_InvalidModelCode","Lỗi tạo mã model không hợp lệ"},
{"Erridn.Skycic.Inventory.Mst_Model_Create_InvalidModelName","Lỗi tạo tên model không hợp lệ"},
{"Erridn.Skycic.Inventory.Mst_Model_Update","Lỗi update model"},
{"Erridn.Skycic.Inventory.Mst_Model_Update_InvalidModelName","Lỗi cập nhật tên model không hợp lệ"},
{"Erridn.Skycic.Inventory.Mst_Model_Delete","Lỗi khi xóa model"},
{"Erridn.Skycic.Inventory.Mst_Spec_CheckDB_SpecNotFound","Lỗi không tìm thấy spec trong database"},
{"Erridn.Skycic.Inventory.Mst_Spec_CheckDB_SpecExist","Lỗi đã tồn tại spec này trong database"},
{"Erridn.Skycic.Inventory.Mst_Spec_CheckDB_FlagActiveNotMatched","Lỗi Trạng thái spec không hợp lệ"},
{"Erridn.Skycic.Inventory.Mst_Spec_CheckDB_FlagHasSerialNotMatched","Lỗi trạng thái sản phẩm trong mã spec này không hợp lệ"},
{"Erridn.Skycic.Inventory.Mst_Spec_CheckDB_FlagHasLOTNotMatched","Lỗi trạng thái số LOT không hợp lệ"},
{"Erridn.Skycic.Inventory.Mst_Spec_Get","Lỗi khi lấy dữ liệu từ spec"},
{"Erridn.Skycic.Inventory.WAS_Mst_Spec_Get","Lỡi lấy dữ liệu từ Spec"},
{"Erridn.Skycic.Inventory.Mst_Spec_Add","Lỗi thêm mới spec"},
{"Erridn.Skycic.Inventory.Mst_Spec_Add_InvalidSpecCode","Lỗi thêm mới mã spec bị sai"},
{"Erridn.Skycic.Inventory.Mst_Spec_Add_InvalidModelName","Lỗi thêm tên model bị sai"},
{"Erridn.Skycic.Inventory.Mst_Spec_Add_Input_Mst_SpecImageTblNotFound","Lỗi  không tìm thấy ảnh của spec"},
{"Erridn.Skycic.Inventory.Mst_Spec_Add_Input_Mst_SpecFilesTblNotFound","Lỗi  không tìm thấy file của spec"},
{"Erridn.Skycic.Inventory.WAS_Mst_Spec_Add","Lỗi thêm mới spec"},
{"Erridn.Skycic.Inventory.Mst_Spec_Upd","Lỗi cập nhật spec"},
{"Erridn.Skycic.Inventory.Mst_Spec_Upd_InvalidSpecCode","Lỗi mã spec không hợp lệ"},
{"Erridn.Skycic.Inventory.Mst_Spec_Upd_InvalidSpecName","Lỗi tên spec không hợp lệ"},
{"Erridn.Skycic.Inventory.Mst_Spec_Upd_Input_Mst_SpecImageTblNotFound","Lỗi cập nhật spec:  không tìm thấy ảnh spec"},
{"Erridn.Skycic.Inventory.Mst_Spec_Upd_Input_Mst_SpecFilesTblNotFound","Lỗi cập nhật spec: không tìm thấy file spec"},
{"Erridn.Skycic.Inventory.WAS_Mst_Spec_Upd","Lỗi cập nhật spec"},
{"Erridn.Skycic.Inventory.Mst_Spec_Del","Lỗi khi xóa Spec"},
{"Erridn.Skycic.Inventory.WAS_Mst_Spec_Del","Lỗi xóa spec"},
{"Erridn.Skycic.Inventory.Mst_SpecCustomField_CheckDB_CustomFieldNotFound","Lỗi không tìm thấy customField trong spec"},
{"Erridn.Skycic.Inventory.Mst_SpecCustomField_CheckDB_CustomFieldExist","Lỗi đã tồn tại customField trong spec"},
{"Erridn.Skycic.Inventory.Mst_SpecCustomField_CheckDB_FlagActiveNotMatched","Lỗi trạng thái customField trong spec không hợp lệ"},
{"Erridn.Skycic.Inventory.Mst_SpecCustomField_Get","Lỗi khi lấy dữ liệu từ customField của Spec"},
{"Erridn.Skycic.Inventory.Mst_SpecCustomField_Update","Lỗi khi cập nhật dữ liệu từ customField của Spec"},
{"Erridn.Skycic.Inventory.Mst_SpecCustomField_Update_InvalidSpecCustomFieldName","Lỗi cập nhật tên customField cho Spec"},
{"Erridn.Skycic.Inventory.WAS_Mst_SpecCustomField_Get","Lỗi lấy dữ liệu từ customfield của spec"},
{"Erridn.Skycic.Inventory.WAS_Mst_SpecCustomField_Update","Lỗi cập nhật dữ liệu customfield của spec"},
{"ErrTCGQLTV.Mst_Unit_CheckDB_UnitCodeNotFound","Không tìm thấy mã đơn vị trong danh mục đơn vị"},
{"ErrTCGQLTV.Mst_Unit_CheckDB_UnitCodeExist","Mã đơn vị đã tồn tại "},
{"ErrTCGQLTV.Mst_Unit_CheckDB_FlagActiveNotMatched","Trạng thái đơn vị không hợp lệ"},
{"ErrTCGQLTV.Mst_Unit_Get","Lỗi lấy dữ liệu từ đơn vị"},
{"ErrTCGQLTV.Mst_Unit_Create","Lỗi khi tạo đơn vị"},
{"ErrTCGQLTV.Mst_Unit_Create_InvalidUnitCode","Lỗi tạo mã đơn vị"},
{"ErrTCGQLTV.Mst_Unit_Create_InvalidUnitName","Lỗi tạo tên đơn vị"},
{"ErrTCGQLTV.Mst_Unit_Update","Lỗi cập nhật đơn vị"},
{"ErrTCGQLTV.Mst_Unit_Update_InvalidUnitName","Lỗi cập nhật tên đơn vị"},
{"ErrTCGQLTV.Mst_Unit_Delete","Lỗi xóa đơn vị"},
{"ErrTCGQLTV.WAS_Mst_Unit_Create","Lỗi tạo mã đơn vị"},
{"ErrTCGQLTV.WAS_Mst_Unit_Update","Lỗi khi cập nhật đơn vị"},
{"ErrTCGQLTV.WAS_Mst_Unit_Delete","Lỗi khi xóa đơn vị"},
{"ErrTCGQLTV.WAS_Mst_Unit_Get","Lỗi lấy dữ liệu từ danh mục đơn vị"},
{"ErrTCGQLTV.Mst_SpecUnit_CheckDB_SpecUnitNotFound","Không tìm thấy đơn vị của spec"},
{"ErrTCGQLTV.Mst_SpecUnit_CheckDB_SpecUnitExist","Đơn vị của spec đã tồn tại trong hệ thống "},
{"ErrTCGQLTV.Mst_SpecUnit_CheckDB_FlagActiveNotMatched","Trạng thái đơn vị của spec không hợp lệ"},
{"ErrTCGQLTV.Mst_SpecUnit_Get","Lỗi lấy dữ liệu đơn vị của spec"},
{"ErrTCGQLTV.Mst_SpecUnit_Create","Lỗi tạo đơn vị spec"},
{"ErrTCGQLTV.Mst_SpecUnit_Update","Lỗi cập nhật đơn vị cho spec"},
{"ErrTCGQLTV.Mst_SpecUnit_Delete","Lỗi xóa đơn vị spec"},
{"ErrTCGQLTV.WAS_Mst_SpecUnit_Get","Lỗi lấy dữ liệu đơn vị của spec"},
{"ErrTCGQLTV.WAS_Mst_SpecUnit_Create","Lỗi tạo đơn vị spec"},
{"ErrTCGQLTV.WAS_Mst_SpecUnit_Update","Lỗi cập nhật đơn vị cho spec"},
{"ErrTCGQLTV.WAS_Mst_SpecUnit_Delete","Lỗi xóa đơn vị spec"},
{"ErrTCGQLTV.Mst_CurrencyEx_CheckDB_CurrencyCodeNotFound","Không tìm thấy mã tỷ giá"},
{"ErrTCGQLTV.Mst_CurrencyEx_CheckDB_CurrencyCodeExist","Mã tỷ giá đã tồn tại"},
{"ErrTCGQLTV.Mst_CurrencyEx_CheckDB_FlagActiveNotMatched","Trạng thái tỷ giá không hợp lệ"},
{"ErrTCGQLTV.Mst_CurrencyEx_Get","Lỗi lấy dữ liệu từ hàm tỷ giá"},
{"ErrTCGQLTV.Mst_CurrencyEx_Create","Lỗi tạo mới tỷ giá"},
{"ErrTCGQLTV.Mst_CurrencyEx_Create_InvalidCurrencyName","Lỗi tạo mới tên tỷ giá không hợp lệ"},
{"ErrTCGQLTV.Mst_CurrencyEx_Update","Lỗi cập nhật tỷ giá"},
{"ErrTCGQLTV.Mst_CurrencyEx_Update_InvalidCurrencyName","Lỗi cập nhật tên tỷ giá bị sai"},
{"ErrTCGQLTV.Mst_CurrencyEx_Delete","Lỗi xóa tỷ giá"},
{"ErrTCGQLTV.WAS_Mst_CurrencyEx_Get","Lỗi khi lấy dữ liệu từ tỷ giá"},
{"ErrTCGQLTV.WAS_Mst_CurrencyEx_Create","Lỗi khi tạo mới tỷ giá"},
{"ErrTCGQLTV.WAS_Mst_CurrencyEx_Update","Lỗi khi cập nhật tỷ giá"},
{"ErrTCGQLTV.WAS_Mst_CurrencyEx_Delete","Lỗi khi xóa tỷ giá"},
{"ErrTCGQLTV.Mst_SpecPrice_CheckDB_SpecPriceNotFound","Lỗi không tìm thấy giá của spec"},
{"ErrTCGQLTV.Mst_SpecPrice_CheckDB_SpecPriceExist","Lỗi giá của spec này đã tồn tại"},
{"ErrTCGQLTV.Mst_SpecPrice_CheckDB_FlagActiveNotMatched","Trạng thái giá spec không hợp lệ"},
{"ErrTCGQLTV.Mst_SpecPrice_Get","Lỗi lấy dữ liệu giá spec"},
{"ErrTCGQLTV.Mst_SpecPrice_Create","Lỗi tạo mới giá spec"},
{"ErrTCGQLTV.Mst_SpecPrice_Update","Lỗi cập nhật giá spec"},
{"ErrTCGQLTV.Mst_SpecPrice_Delete","lỗi xóa giá spec"},
{"ErrTCGQLTV.WAS_Mst_SpecPrice_Get","Lỗi lấy dữ liệu từ giá spec"},
{"ErrTCGQLTV.WAS_Mst_SpecPrice_Create","Lỗi tạo mới giá spec"},
{"ErrTCGQLTV.WAS_Mst_SpecPrice_Update","Lỗi cập nhật giá spec"},
{"ErrTCGQLTV.WAS_Mst_SpecPrice_Delete","lỗi xóa giá spec"},
{"ErrTCGQLTV.Prd_ProductID_CheckDB_ProductIDNotFound","Không tìm thấy mã sản phẩm"},
{"ErrTCGQLTV.Prd_ProductID_CheckDB_ProductIDExist","Mã sản phẩm đã tồn tại"},
{"ErrTCGQLTV.Prd_ProductID_CheckDB_ProductIDStatusNotMatched","Trạng thái mã sản phẩm không hợp lệ"},
{"ErrTCGQLTV.Prd_ProductID_Get","Lỗi lấy dữ liệu từ mã sản phẩm"},
{"ErrTCGQLTV.Prd_ProductID_Create","Lỗi tạo mới sản phẩm"},
{"ErrTCGQLTV.Prd_ProductID_Create_InvalidProductID","Lỗi tạo mới mã sản phẩm"},
{"ErrTCGQLTV.Prd_ProductID_Update","Lỗi cập nhật sản phẩm"},
{"ErrTCGQLTV.Prd_ProductID_Delete","Lỗi xóa sản phẩm"},
{"ErrTCGQLTV.WAS_Prd_ProductID_Get","Lỗi lấy dữ liệu từ sản phẩm"},
{"ErrTCGQLTV.WAS_Prd_ProductID_Create","Lỗi tạo mới sản phẩm"},
{"ErrTCGQLTV.WAS_Prd_ProductID_Update","Lỗi cập nhật sản phẩm"},
{"ErrTCGQLTV.WAS_Prd_ProductID_Delete","Lỗi xóa sản phẩm"},
{"ErrTCGQLTV.Prd_PrdIDCustomField_CheckDB_PrdIDCustomFieldNotFound","Lỗi không tìm thấy customfield của sản phẩm"},
{"ErrTCGQLTV.Prd_PrdIDCustomField_CheckDB_PrdIDCustomFieldExist","Lỗi customfield của sản phẩm đã tồn tại"},
{"ErrTCGQLTV.Prd_PrdIDCustomField_CheckDB_FlagActiveNotMatched","Lỗi trạng thái customField trong sản phẩm không hợp lệ"},
{"ErrTCGQLTV.Prd_PrdIDCustomField_Get","Lỗi lấy dữ liệu customfield sản phẩm"},
{"ErrTCGQLTV.Prd_PrdIDCustomField_Update","Lỗi cập nhật customfield sản phẩm"},
{"ErrTCGQLTV.WAS_Prd_PrdIDCustomField_Get","Lỗi lấy dữ liệu customfield sản phẩm"},
{"ErrTCGQLTV.WAS_Prd_PrdIDCustomField_Create","Lỗi tạo mới customfield sản phẩm"},
{"ErrTCGQLTV.WAS_Prd_PrdIDCustomField_Update","Lỗi cập nhật customfield sản phẩm"},
{"ErrTCGQLTV.WAS_Prd_PrdIDCustomField_Delete","Lỗi xóa customfield sản phẩm"},
{"Erridn.Skycic.Inventory.Mst_VATRate_CheckDB_VATRateCodeNotFound","Lỗi không tìm thấy mã thuế suất"},
{"Erridn.Skycic.Inventory.Mst_VATRate_CheckDB_VATRateCodeExist","Lỗi mã thuế suất đã tồn tại"},
{"Erridn.Skycic.Inventory.Mst_VATRate_CheckDB_FlagActiveNotMatched","Trạng thái thuế suất không hợp lệ"},
{"Erridn.Skycic.Inventory.Mst_VATRate_Get","Lỗi lấy dữ liệu thuế suất"},
{"Erridn.Skycic.Inventory.Mst_VATRate_Create","Lỗi tạo mới thuế suất"},
{"Erridn.Skycic.Inventory.Mst_VATRate_Create_InvalidVATRateCode","Lỗii tạo mới mã thuế suất"},
{"Erridn.Skycic.Inventory.Mst_VATRate_Create_InvalidVATRateName","Lỗi tạo mới tên thuế suất"},
{"Erridn.Skycic.Inventory.Mst_VATRate_Update","Lỗi cập nhật thuế suất"},
{"Erridn.Skycic.Inventory.Mst_VATRate_Update_InvalidVATRateName","Lỗi cập nhật tên thuế suất"},
{"Erridn.Skycic.Inventory.Mst_VATRate_Delete","Lỗi xóa thuế suất"},
{"Erridn.Skycic.Inventory.WAS_Mst_VATRate_Get","Lỗi hàm lấy dữ liệu thuế suất"},
{"Erridn.Skycic.Inventory.WAS_Mst_VATRate_Create","Lỗi hàm tạo mới thuế suất"},
{"Erridn.Skycic.Inventory.WAS_Mst_VATRate_Update","Lỗi cập nhật thuế suất"},
{"Erridn.Skycic.Inventory.WAS_Mst_VATRate_Delete","Lỗi xóa thuế suất                                                                                 "},
{"Erridn.Skycic.Inventory.Mst_SpecType1_CheckDB_SpecType1NotFound","Lỗi không tìm thấy loại sản phẩm"},
{"Erridn.Skycic.Inventory.Mst_SpecType1_CheckDB_SpecType1Exist","Lỗi loại sản phẩm đã tồn tại"},
{"Erridn.Skycic.Inventory.Mst_SpecType1_CheckDB_FlagActiveNotMatched","Trạng thái loại sản phẩm không hợp lệ"},
{"Erridn.Skycic.Inventory.Mst_SpecType1_Get","Lỗi lấy dữ liệu loại sản phẩm"},
{"Erridn.Skycic.Inventory.Mst_SpecType1_Create","Lỗi tạo mới loại sản phẩm"},
{"Erridn.Skycic.Inventory.Mst_SpecType1_Create_InvalidSpecType1","Lỗi tạo mới mã loại sản phẩm"},
{"Erridn.Skycic.Inventory.Mst_SpecType1_Create_InvalidSpecType1Name","Lỗi tạo mới tên loại sản phẩm"},
{"Erridn.Skycic.Inventory.Mst_SpecType1_Update","Lỗi cập nhật loại sản phẩm"},
{"Erridn.Skycic.Inventory.Mst_SpecType1_Update_InvalidSpecType1Name","Lỗi cập nhật tên loại sản phẩm"},
{"Erridn.Skycic.Inventory.Mst_SpecType1_Delete","Lỗi xóa loại sản phẩm"},
{"Erridn.Skycic.Inventory.WAS_Mst_SpecType1_Get","Lỗi lấy dữ liệu loại sản phẩm"},
{"Erridn.Skycic.Inventory.WAS_Mst_SpecType1_Create","Lỗi tạo mới loại sản phẩm"},
{"Erridn.Skycic.Inventory.WAS_Mst_SpecType1_Update","Lỗi cập nhật loại sản phẩm"},
{"Erridn.Skycic.Inventory.WAS_Mst_SpecType1_Delete","Lỗi xóa loại sản phẩm"},
{"Erridn.Skycic.Inventory.Mst_SpecType2_CheckDB_SpecType2NotFound","Lỗi không tìm thấy nhóm sản phẩm"},
{"Erridn.Skycic.Inventory.Mst_SpecType2_CheckDB_SpecType2Exist","Lỗi nhóm sản phẩm đã tồn tại"},
{"Erridn.Skycic.Inventory.Mst_SpecType2_CheckDB_FlagActiveNotMatched","Lỗi trạng thái của nhóm sản phẩm không hợp lệ"},
{"Erridn.Skycic.Inventory.Mst_SpecType2_Get","Lỗi lấy dữ liệu nhóm sản phẩm"},
{"Erridn.Skycic.Inventory.Mst_SpecType2_Create","Lỗi tạo mới nhóm sản phẩm"},
{"Erridn.Skycic.Inventory.Mst_SpecType2_Create_InvalidSpecType2","Lỗi tạo mới mã nhóm sản phẩm"},
{"Erridn.Skycic.Inventory.Mst_SpecType2_Create_InvalidSpecType2Name","Lỗi tạo mới tên nhóm sản phẩm"},
{"Erridn.Skycic.Inventory.Mst_SpecType2_Update","Lỗi cập nhật nhóm sản phẩm"},
{"Erridn.Skycic.Inventory.Mst_SpecType2_Update_InvalidSpecType2Name","Lỗi cập nhật tên nhóm sản phẩm"},
{"Erridn.Skycic.Inventory.Mst_SpecType2_Delete","Lỗi xóa nhóm sản phẩm"},
{"Erridn.Skycic.Inventory.WAS_Mst_SpecType2_Get","Lỗi lấy dữ liệu nhóm sản phẩm"},
{"Erridn.Skycic.Inventory.WAS_Mst_SpecType2_Create","Lỗi tạo mới nhóm sản phẩm"},
{"Erridn.Skycic.Inventory.WAS_Mst_SpecType2_Update","Lỗi cập nhật nhóm sản phẩm"},
{"Erridn.Skycic.Inventory.WAS_Mst_SpecType2_Delete","Lỗi xóa nhóm sản phẩm"},
{"ErridnInventory.MstSv_Sys_Administrator_CheckDB_AdministratorNotFound","Lỗi không tìm thấy người quản trị "},
{"ErridnInventory.MstSv_Sys_Administrator_CheckDB_AdministratorExist","Lỗi người quản trị đã tồn tại"},
{"ErridnInventory.MstSv_Sys_Administrator_CheckDB_FlagActiveNotMatched","Lỗi trạng thái người quản không hợp lệ"},
{"ErridnInventory.MstSv_Sys_Administrator_CheckDeny","Lỗi từ chối kiểm tra người quản trị"},
{"ErridnInventory.MstSv_Sys_User_CheckDB_UserNotFound","Lỗi không tìm thấy người dùng"},
{"ErridnInventory.MstSv_Sys_User_CheckDB_UserExist","Lỗi người dùng đã tồn tại"},
{"ErridnInventory.MstSv_Sys_User_CheckDB_FlagActiveNotMatched","Lỗi trạng thái người dùng không hợp lệ"},
{"ErridnInventory.MstSv_Sys_User_Login","Lỗi đăng nhập người dùng"},
{"ErridnInventory.MstSv_Sys_User_Login_InvalidPassword","Lỗi đăng nhập người dùng mật khẩu  không hợp lệ"},
{"ErridnInventory.MstSv_Sys_User_Get","Lỗi lấy dữ liệu người dùng"},
{"ErridnInventory.MstSv_Sys_User_Add","Lỗi thêm mới người dùng"},
{"ErridnInventory.MstSv_Sys_User_Add_InvalidUserCode","Lỗi thêm mới mã người dùng  không hợp lệ"},
{"ErridnInventory.MstSv_Sys_User_Add_InvalidUserName","Lỗi thêm mới tên người dùng  không hợp lệ"},
{"ErridnInventory.MstSv_Sys_User_Update","Lỗi cập nhật người dùng"},
{"ErridnInventory.MstSv_Sys_User_Update_InvalidBrandName","Lỗi cập nhật tên nhãn hiệu không hợp lệ"},
{"ErridnInventory.MstSv_Sys_User_Delete","Lỗi xóa người dùng"},
{"ErridnInventory.WAS_MstSv_Sys_User_Get","Lỗi lấy dữ liệu người dùng"},
{"ErridnInventory.WAS_MstSv_Sys_User_Login","Lỗi đăng nhập người dùng"},
{"ErridnInventory.WAS_MstSv_Sys_User_Add","Lỗi thêm người dùng"},
{"ErridnInventory.WAS_MstSv_Sys_User_Update","Lỗi cập nhật người dùng"},
{"ErridnInventory.WAS_MstSv_Sys_User_Delete","Lỗi xóa người dùng"},
{"ErridnInventory.MstSv_Mst_Network_CheckDB_NetworkNotFound","Lỗi Không tìm thấy network trong hệ thống"},
{"ErridnInventory.MstSv_Mst_Network_CheckDB_NetworkExist","Lỗi network đã tồn tại trong hệ thống"},
{"ErridnInventory.MstSv_Mst_Network_CheckDB_FlagActiveNotMatched","Lỗi trạng thái network không phù hợp"},
{"ErridnInventory.MstSv_Mst_Network_Get","Lỗi lấy dữ liệu từ network"},
{"ErridnInventory.WAS_MstSv_Mst_Network_Get","Lỗi lấy dữ liệu từ network"},
{"ErridnInventory.MstSv_Mst_Network_Create","Lỗi tạo mới network"},
{"ErridnInventory.MstSv_Mst_Network_Create_InvalidNetworkID","Lỗi tạo mới mã network không hợp lệ"},
{"ErridnInventory.MstSv_Mst_Network_Create_InvalidNetworkName","Lỗi tạo mới tên network không hợp lệ"},
{"ErridnInventory.WAS_MstSv_Mst_Network_Create","Lỗi tạo mới network"},
{"ErridnInventory.MstSv_Mst_Network_Update","Lỗi cập nhật network"},
{"ErridnInventory.MstSv_Mst_Network_Update_InvalidNetworkName","Lỗi cập nhật network: tên network không hợp lệ"},
{"ErridnInventory.WAS_MstSv_Mst_Network_Update","Lỗi cập nhật network"},
{"ErridnInventory.MstSv_Mst_Network_Delete","Lỗi xóa network"},
{"ErridnInventory.WAS_MstSv_Mst_Network_Delete","Lỗi xóa network"},
{"ErridnInventory.MstSv_Sys_UserInNetWork_CheckDB_UserInNetWorkNotFound","Lỗi không tìm thấy người dùng trong network"},
{"ErridnInventory.MstSv_Sys_UserInNetWork_CheckDB_UserInNetWorkExist","Lỗi người dùng đã tồn tại trong network"},
{"ErridnInventory.MstSv_Sys_UserInNetWork_CheckDB_FlagActiveNotMatched","Lỗi trạng thái người dùng trong network không phù hợp"},
{"ErridnInventory.MstSv_Inos_User_CheckDB_UserNotFound","Lỗi không tìm thấy người dùng"},
{"ErridnInventory.MstSv_Inos_User_CheckDB_UserExist","Lỗi người dùng đã tồn tại"},
{"ErridnInventory.MstSv_Inos_User_CheckDB_FlagActiveNotMatched","Lỗi trạng thái người dùng không phù hợp"},
{"ErridnInventory.MstSv_Inos_User_Get","Lỗi lấy dữ liệu người dùng"},
{"ErridnInventory.WAS_MstSv_Inos_User_Get","Lỗi lấy dữ liệu người dùng"},
{"ErridnInventory.MstSv_Inos_User_Add","Lỗi thêm mới người dùng"},
{"ErridnInventory.MstSv_Inos_User_Add_Input_MstSv_Inos_OrgTblNotFound","Lỗi không tìm thấy tổ chức khi thêm mới người dùng"},
{"ErridnInventory.MstSv_Inos_User_Add_Input_MstSv_Inos_OrgUserTblNotFound","Lỗi không tìm người dùng trong tổ chức"},
{"ErridnInventory.MstSv_Inos_User_Add_Input_MstSv_Inos_PackageTblNotFound","Lỗi không tìm thấy gói khi thêm người dùng"},
{"ErridnInventory.MstSv_Inos_User_Add_Input_MstSv_Inos_OrgInviteTblNotFound","Mã lỗi: ErridnInventory.MstSv_Inos_User_Add_Input_MstSv_Inos_OrgInviteTblNotFound"},
{"ErridnInventory.MstSv_Inos_User_Activate","Lỗi trạng thái người dùng"},
{"ErridnInventory.WAS_MstSv_Inos_User_Activate","Lỗi trạng thái người dùng"},
{"ErridnInventory.MstSv_Inos_User_Create","Lỗi tạo mới người dùng"},
{"ErridnInventory.MstSv_Inos_User_Create_InvalidNetworkID","Lỗi tạo người dùng: mã network không hợp lệ"},
{"ErridnInventory.MstSv_Inos_User_Create_InvalidNetworkName","Lỗi tạo người dùng: tên network không hợp lệ"},
{"ErridnInventory.WAS_MstSv_Inos_User_Create","Lỗi tạo mới người dùng"},
{"ErridnInventory.MstSv_Inos_User_Update","Lỗi cập nhật người dùng"},
{"ErridnInventory.MstSv_Inos_User_Update_InvalidNetworkName","Lỗi cập nhật người dùng: tên network không hợp lệ"},
{"ErridnInventory.WAS_MstSv_Inos_User_Update","Lỗi cập nhật người dùng"},
{"ErridnInventory.MstSv_Inos_User_Delete","Lỗi xóa người dùng"},
{"ErridnInventory.WAS_MstSv_Inos_User_Delete","Lỗi xóa người dùng"},
{"ErridnInventory.MstSv_Inos_Org_CheckDB_OrgNotFound","Lỗi không tìm thấy tổ chức"},
{"ErridnInventory.MstSv_Inos_Org_CheckDB_OrgExist","Lỗi tổ chức đã tồn tại"},
{"ErridnInventory.MstSv_Inos_Org_CheckDB_FlagActiveNotMatched","Lỗi trạng thái tổ chức không phù hợp"},
{"ErridnInventory.MstSv_Inos_Org_Get","Lỗi lấy dữ liệu tổ chức"},
{"ErridnInventory.WAS_MstSv_Inos_Org_Get","Lỗi lấy dữ liệu tổ chức"},
{"ErridnInventory.MstSv_Inos_Org_Add","Lỗi thêm mới tổ chức"},
{"ErridnInventory.MstSv_Inos_Org_Add_Input_MstSv_Inos_OrgTblNotFound","Lỗi thêm mới tổ chức : không tìm thấy tổ chức trong bảng"},
{"ErridnInventory.MstSv_Inos_Org_Add_Input_MstSv_Inos_OrgUserTblNotFound","Lỗi thêm mới tổ chức : không tìm thấy tổ chức trong bảng người dùng"},
{"ErridnInventory.MstSv_Inos_Org_Add_Input_MstSv_Inos_OrgInviteTblNotFound","Lỗi thêm mới tổ chức : không tìm thấy tổ chức"},
{"ErridnInventory.MstSv_Inos_Org_Activate","Lỗi trạng thái tổ chức"},
{"ErridnInventory.WAS_MstSv_Inos_Org_Activate","Lỗi trạng thái tổ chức"},
{"ErridnInventory.MstSv_Inos_Org_BuildAndCreate","Lỗi xây dựng và tạo mới tổ chức"},
{"ErridnInventory.WAS_MstSv_Inos_Org_BuildAndCreate","Lỗi xây dựng và tạo mới tổ chức"},
{"ErridnInventory.MstSv_Inos_Org_Create","Lỗi tạo mới tổ chức"},
{"ErridnInventory.MstSv_Inos_Org_Create_InvalidNetworkID","Lỗi tạo mới tổ chức: mã network không hợp lệ"},
{"ErridnInventory.MstSv_Inos_Org_Create_InvalidNetworkName","Lỗi tạo mới tổ chức: tên network không hợp lệ"},
{"ErridnInventory.WAS_MstSv_Inos_Org_Create","Lỗi tạo tổ chức"},
{"ErridnInventory.MstSv_Inos_Org_Update","Lỗi cập nhật tổ chức"},
{"ErridnInventory.MstSv_Inos_Org_Update_InvalidNetworkName","Lỗi cập nhật tổ chức: tên network không hợp lệ"},
{"ErridnInventory.WAS_MstSv_Inos_Org_Update","Lỗi cập nhật tổ chức"},
{"ErridnInventory.MstSv_Inos_Org_Delete","Lỗi xóa tổ chức"},
{"ErridnInventory.WAS_MstSv_Inos_Org_Delete","Lỗi xóa tổ chức"},
{"ErridnInventory.Inos_AccountService_Register","Lỗi tài khoản đăng kí dịch vụ "},
{"ErridnInventory.OS_Inos_Package_Get","Lỗi lấy dữ liệu gói tổ chức"},
{"ErridnInventory.WAS_OS_Inos_Package_Get","Lỗi lấy dữ liệu gói tổ chức"},
{"ErridnInventory.MstSv_OrgInNetwork_CheckDB_OrgInNetworkNotFound","Lỗi không tìm thấy tổ chức trong network"},
{"ErridnInventory.MstSv_OrgInNetwork_CheckDB_OrgInNetworkExist","Lỗi tổ chức đã tồn tại trong network"},
{"ErridnInventory.MstSv_OrgInNetwork_CheckDB_FlagActiveNotMatched","Lỗi trạng thái tổ chức trong nettwork không phù hợp"},
{"ErridnInventory.MstSv_OrgInNetwork_GetOrgIDSln","Mã lỗi: ErridnInventory.MstSv_OrgInNetwork_GetOrgIDSln"},
{"ErridnInventory.WAS_MstSv_OrgInNetwork_GetOrgIDSln","Mã lỗi: ErridnInventory.WAS_MstSv_OrgInNetwork_GetOrgIDSln"},
{"ErridnInventory.MstSv_OrgInNetwork_GetByOrgIDSln","Mã lỗi: ErridnInventory.MstSv_OrgInNetwork_GetByOrgIDSln"},
{"ErridnInventory.WAS_MstSv_OrgInNetwork_GetByOrgIDSln","Mã lỗi: ErridnInventory.WAS_MstSv_OrgInNetwork_GetByOrgIDSln"},
{"ErridnInventory.OS_MstSvTVAN_MstSv_Sys_User_Login","Lỗi đăngnhập"},
{"ErridnInventory.RptSv_Invoice_Invoice_Get","Lỗi lấy dữ liệu hóa đơn"},
{"ErridnInventory.WAS_RptSv_Invoice_Invoice_Get","Lỗi lấy dữ liệu hóa đơn"},
{"ErridnInventory.Rpt_InvoiceForDashboard","Lỗi màn hình điều khiển hóa đơn"},
{"ErridnInventory.WAS_Rpt_InvoiceForDashboard","Lỗi màn hình điều khiển hóa đơn"},
{"ErridnInventory.Invoice_Invoice_CheckDB_InvoiceNotFound","Lỗi không tìm thấy hóa đơn"},
{"ErridnInventory.Invoice_Invoice_CheckDB_InvoiceExist","Lỗi hóa đơn đã tồn tại"},
{"ErridnInventory.Invoice_Invoice_CheckDB_CheckDB_InvoiceStatusNotMatched","Lỗi trạng thái hóa đơn không phù hợp"},
{"ErridnInventory.Invoice_Invoice_Get","Lỗi lấy dữ liệu cho hóa đơn"},
{"ErridnInventory.Invoice_Invoice_GetNoSession","Mã lỗi: ErridnInventory.Invoice_Invoice_GetNoSession"},
{"ErridnInventory.WAS_Invoice_Invoice_GetNoSession","Mã lỗi: ErridnInventory.WAS_Invoice_Invoice_GetNoSession"},
{"ErridnInventory.Invoice_Invoice_SaveX","Lỗi lưu hóa đơn"},
{"ErridnInventory.Invoice_Invoice_SaveX_InvalidInvoiceCode","Lỗi lưu hóa đơn, mã hóa đơn không hợp lệ"},
{"ErridnInventory.Invoice_Invoice_SaveX_StatusNotMatched","Lỗi lưu mã hóa đơn, trạng thái không phù hợp"},
{"ErridnInventory.Invoice_Invoice_SaveX_Input_InvoiceDtlTblNotFound","Lỗi không tìm thấy chi tiết bảng hóa đơn"},
{"ErridnInventory.Invoice_Invoice_SaveX_Input_InvoiceDtlTblInvalid","Bảng chi tiết hóa đơn không hợp lệ"},
{"ErridnInventory.Invoice_Invoice_SaveX_Input_InvoicePrdTblInvalid","Lỗi bảng sản phẩm hóa đơn không hợp lệ"},
{"ErridnInventory.Invoice_Invoice_SaveX_InvoiceAdjTypeIsNotNull","Lỗi loại hóa đơn điều chỉnh không được 0trống"},
{"ErridnInventory.Invoice_Invoice_SaveX_ExistInvoiceNo","Lỗi hóa đơn không tồn tại"},
{"ErridnInventory.Invoice_Invoice_SaveX_NotDelete","Lỗi không được xóa hóa đơn"},
{"ErridnInventory.Invoice_Invoice_SaveX_InvalidInvoiceDateUTCBeforeLastInvoiceDateUTC","Ngày hóa đơn cấp sau phải >= ngày hóa đơn cấp trước"},
{"ErridnInventory.Invoice_Invoice_SaveX_InvalidMSTOfNNTAndCustomer","Lỗi mã số thuế  của người nộp thuế và khách hàng không hợp lệ"},
{"ErridnInventory.Invoice_Invoice_SaveX_InvalidMSTOfNNTAndTempInvoice","Lỗi mã số thuế của người nộp thuế và  mẫu hóa đơn không hợp lệ"},
{"ErridnInventory.Invoice_Invoice_SaveX_InvalidQtyIssueRemain","Đã dùng hết hóa đơn, vui lòng phát hành thêm"},
{"ErridnInventory.Invoice_Invoice_SaveX_InputInvoice_InvoicePrdTblNotFound","Lỗi không tìm thấy bảng sản phẩm"},
{"ErridnInventory.Invoice_Invoice_SaveX_Input_Invoice_InvoicePrdTblInvalid","Lỗi bảng sản phẩm hóa đơn không hợp lệ"},
{"ErridnInventory.Invoice_Invoice_SaveX_Input_Invoice_InvaliInvoiceDateUTCAfterSysDate","Lỗi ngày cấp số hóa đơn  không hợp lệ"},
{"ErridnInventory.Invoice_Invoice_Save_Replace","Lỗi lưu hóa đơn thay thế"},
{"ErridnInventory.WAS_Invoice_Invoice_Save_Root","Lỗi lưu hóa đơn gốc"},
{"ErridnInventory.WAS_Invoice_Invoice_Save_Adj","Lỗi lưu hóa điều chỉnh"},
{"ErridnInventory.WAS_Invoice_Invoice_Save_Replace","Lỗi lưu hóa đơn thay thế"},
{"ErridnInventory.Invoice_Invoice_Save_Adj","Lỗi lưu hóa đơn điều chỉnh"},
{"ErridnInventory.Invoice_Invoice_Save_Root","Lỗi lưu hóa đơn gốc"},
{"ErridnInventory.WAS_Invoice_Invoice_Cancel","Lỗi hủy hóa đơn"},
{"ErridnInventory.Invoice_Invoice_Cancel","Lỗi hủy hóa đơn"},
{"ErridnInventory.Invoice_Invoice_Cancel_InvoiceDtlNotFound","Lỗi không tìm thấy chi tiết hóa đơn "},
{"ErridnInventory.Invoice_Invoice_Cancel_InvoiceNoIsNotNull","Lỗi hóa đơn chưa được cấp số ( số hóa đơn không được trống)"},
{"ErridnInventory.Invoice_Invoice_Cancel_InvalidMST","Lỗi mã số thuế không hợp lệ"},
{"ErridnInventory.WAS_Invoice_Invoice_Approved","Lỗi hóa đơn ở trạng thái đã ký điện tử"},
{"ErridnInventory.Invoice_Invoice_Approved","Lỗi hóa đơn ở trạng thái đã ký điện tử"},
{"ErridnInventory.Invoice_Invoice_Approved_InvoiceDtlNotFound","Lỗi không tìm thấy chi tiết hóa đơn"},
{"ErridnInventory.Invoice_Invoice_Approved_InvoiceNoIsNotNull","Lỗi hóa đơn chưa được cấp số ( số hóa đơn không được trống)"},
{"ErridnInventory.Invoice_Invoice_Approved_InvalidMST","Lỗi mã số thuế không hợp lệ"},
{"ErridnInventory.WAS_Invoice_Invoice_Issued","Lỗi hóa đơn đã gửi khách hàng"},
{"ErridnInventory.Invoice_Invoice_Issued","Lỗi hóa đơn đã gửi khách hàng"},
{"ErridnInventory.Invoice_Invoice_Issued_InvoiceDtlNotFound","Lỗi không tìm thấy chi tiết hóa đơn"},
{"ErridnInventory.Invoice_Invoice_Issued_InvalidMST","Lỗi mã số thuế không hợp lệ"},
{"ErridnInventory.WAS_Invoice_Invoice_Deleted","Lỗi hóa đơn đã xóa"},
{"ErridnInventory.Invoice_Invoice_Deleted","Lỗi hóa đơn đã xóa"},
{"ErridnInventory.Invoice_Invoice_Deleted_InvoiceDtlNotFound","Không tìm thấy chi tiết hóa đơn"},
{"ErridnInventory.Invoice_Invoice_Deleted_InvalidMST","Mã số thuế không hợp lệ"},
{"ErridnInventory.WAS_Invoice_Invoice_AllocatedInv","Lỗi hóa đơn phân bổ"},
{"ErridnInventory.Invoice_Invoice_AllocatedInv","Lỗi hóa đơn phân bổ"},
{"ErridnInventory.Invoice_Invoice_AllocatedInv_InvoiceDtlNotFound","Lỗi Không tìm thấy chi tiết hóa đơn"},
{"ErridnInventory.Invoice_Invoice_AllocatedInv_NotAllowAllocatedInv","Lỗi không cho phép phân bổ hóa đơn"},
{"ErridnInventory.Invoice_Invoice_AllocatedInv_InvalidInvoiceDateUTCBeforeLastInvoiceDateUTC","Ngày hóa đơn cấp sau phải >= ngày hóa đơn cấp trước"},
{"ErridnInventory.Invoice_Invoice_AllocatedInv_InvalidInvoiceDateUTCBeforeEffDateStart","Ngày tạo hóa đơn phải >= today."},
{"ErridnInventory.Invoice_Invoice_AllocatedInv_InvoiceDateUTCIsNotNull","Ngày hóa đơn không được trống"},
{"ErridnInventory.Invoice_Invoice_AllocatedInv_InvalidMST","Mã số thuế không hợp lệ"},
{"ErridnInventory.Invoice_Invoice_AllocatedInv_InvaliInvoiceDateUTCAfterSysDate","Ngày hóa đơn cấp sau không hợp lệ"},
{"ErridnInventory.WAS_Invoice_Invoice_AllocatedAndApprovedAndIssued","Phân bổ giữa kí điện tử và gửi khách hàng"},
{"ErridnInventory.Invoice_Invoice_AllocatedAndApprovedAndIssued","Phân bổ giữa kí điện tử và gửi khách hàng"},
{"ErridnInventory.WAS_Invoice_Invoice_Change","Lỗi hóa đơn chuyển đổi"},
{"ErridnInventory.Invoice_Invoice_Change","Lỗi hóa đơn chuyển đổi"},
{"ErridnInventory.Invoice_Invoice_Change_InvoiceDtlNotFound","Không tìm thấy chi tiết hóa đơn"},
{"ErridnInventory.Invoice_Invoice_Change_InvalidFlagChange","Trạng thái chuyển đổi hóa đơn không hợp lệ"},
{"ErridnInventory.myCheck_Invoice_TempInvoice_Invoice_InvalidValue","Giá trị mẫu hóa đơn không hợp lệ"},
{"ErridnInventory.myCheck_Invoice_Invoice_InvoiceNoNotUnique","Hóa đơn phải duy nhất"},
{"ErridnInventory.myCheck_Invoice_Invoice_RefNo_ExistRefNo","Hóa đơn tồn tại trạng thái từ chối"},
{"ErridnInventory.myCheck_Invoice_Invoice_Total_InvalidValue","Giá trị hóa đơn không hợp lệ"},
{"ErridnInventory.Mst_SourceInvoice_CheckDB_SourceInvoiceNotFound","Không tìm thấy hóa đơn nguồn"},
{"ErridnInventory.Mst_SourceInvoice_CheckDB_SourceInvoiceExist","Tồn tại hóa đơn nguồn"},
{"ErridnInventory.Mst_SourceInvoice_CheckDB_CheckDB_InvoiceStatusNotMatched","Trạng thái hóa đơn không phù hợp "},
{"ErridnInventory.myCache_ViewAbility_CheckAccessMSTWrite","Kiểm tra truy cập mã số thuế"},
{"ErridnInventory.Invoice_TempInvoice_CheckDB_TempInvoiceNotFound","Không tìm thấy mẫu hóa đơn"},
{"ErridnInventory.Invoice_TempInvoice_CheckDB_TempInvoiceExist","Mẫu hóa đơn đã tồn tại"},
{"ErridnInventory.Invoice_TempInvoice_CheckDB_FlagActiveNotMatched","Trạng thái mẫu hóa đơn không phù hợp"},
{"ErridnInventory.Invoice_TempInvoice_CheckDB_StatusNotMatched","Trạng thái mẫu hóa đơn không phù hợp"},
{"ErridnInventory.Invoice_TempInvoice_CheckFormNo_ExistFormNo","Hình thức đã tồn tại"},
{"ErridnInventory.Invoice_license_TotalQtyIssued","Lỗi tổng số lượng hóa đơn đã gửi khách hàng"},
{"ErridnInventory.Invoice_license_TotalQtyIssued_InvalidValue","Tổng số hóa đơn phát hành theo mẫu vượt quá số lượng hóa đơn trong License"},
{"ErridnInventory.Invoice_license_TotalQtyUsed","Lỗi số lượng hóa đơn phát hành đã sử dụng"},
{"ErridnInventory.Invoice_license_TotalQtyUsed_InvalidValue","Tổng số lượng hóa đơn phát hành của mẫu không hợp lệ"},
{"ErridnInventory.Invoice_TempInvoice_CheckFormNoFormat","Mẫu không đúng định dạng"},
{"ErridnInventory.Invoice_TempInvoice_CheckFormatSign","Lỗi kiểm tra định dạng ký tên"},
{"ErridnInventory.Seq_FormNo_Get","Lỗi lấy dữ liệu từ mẫu"},
{"ErridnInventory.Invoice_TempInvoice_Get","Lỗi lấy dữ liệu mẫu hóa đơn"},
{"ErridnInventory.Invoice_TempInvoice_SaveX","Lỗi lưu mẫu hóa đơn"},
{"ErridnInventory.Invoice_TempInvoice_SaveX_InvalidTInvoiceCode","Mã hóa đơn không hợp lệ"},
{"ErridnInventory.Invoice_TempInvoice_SaveX_StatusNotMatched","Trạng thái không phù hợp"},
{"ErridnInventory.Invoice_TempInvoice_SaveX_InvalidFormNo","Hình thức không hợp lệ"},
{"ErridnInventory.Invoice_TempInvoice_SaveX_InvalidSign","Chữ ký không hợp lệ"},
{"ErridnInventory.Invoice_TempInvoice_SaveX_NNTNotUsedInvoiceTGroupCode","Người nộp thuế không sử dụng hóa đơn"},
{"ErridnInventory.Invoice_TempInvoice_Save","Lỗi lưu mẫu hóa đơn"},
{"ErridnInventory.Invoice_TempInvoice_UpdQtyInvoiceNo","Lỗi số lượng hóa đơn phát hành"},
{"ErridnInventory.Invoice_TempInvoice_UpdQtyInvoiceNoX_InvalidValue","Số lượng hóa đơn phát hành của mẫu không hợp lệ"},
{"ErridnInventory.Invoice_TempInvoice_Issued","Lỗi mẫu hóa đơn đã gửi khách hàng"},
{"ErridnInventory.Invoice_TempInvoice_InActive","Lỗi trạng thái mẫu hóa đơn"},
{"ErridnInventory.WAS_Invoice_TempInvoice_UpdQtyInvoiceNo","Lỗi số lượng hóa đơn phát hành của mẫu "},
{"ErridnInventory.WAS_Invoice_TempInvoice_Issued","Lỗi hóa đơn đã gửi khách hàng"},
{"ErridnInventory.Invoice_TempInvoice_IssuedX","Lỗi hóa đơn đã gửi khách hàng"},
{"ErridnInventory.Invoice_TempInvoice_IssuedX_InvalidEndInvoiceNoAndStatrInvoiceNo","Số lượng hóa đơn không hợp lệ (hoặc chưa phát hành số lượng hóa đơn"},
{"ErridnInventory.Invoice_TempInvoice_IssuedX_InvalidIEffDateStartAfterSysDate","Ngày phát hành mẫu phải <= today."},
{"ErridnInventory.WAS_Invoice_TempInvoice_InActive","Lỗi trạng thái mẫu hóa đơn"},
{"ErridnInventory.Mst_InvoiceType_CheckDB_TempInvoiceNotFound","Không tìm thấy mẫu hóa đơn"},
{"ErridnInventory.Mst_InvoiceType_CheckDB_TempInvoiceExist","Mẫu hóa đơn đã tồn tại"},
{"ErridnInventory.Mst_InvoiceType_CheckDB_FlagActiveNotMatched","Trạng thái không phù hợp"},
{"ErridnInventory.Mst_InvoiceType_CheckDB_StatusNotMatched","Trạng thái không phù hợp"},
{"ErridnInventory.Mst_InvoiceType_Get","Lỗi lấy dữ liệu từ loại hóa đơn"},
{"ErridnInventory.WAS_Mst_InvoiceType_Get","Lỗi lấy dữ liệu từ loại hóa đơn"},
{"ErridnInventory.Mst_PaymentMethods_CheckDB_PaymentMethodsNotFound","Không tìm thấy phương thức thanh toán"},
{"ErridnInventory.Mst_PaymentMethods_CheckDB_PaymentMethodsExist","Phương thức thanh toán đã tồn tại"},
{"ErridnInventory.Mst_PaymentMethods_CheckDB_FlagActiveNotMatched","Trạng thái không phù hợp"},
{"ErridnInventory.Mst_PaymentMethods_CheckDB_StatusNotMatched","Trạng thái không phù hợp"},
{"ErridnInventory.Mst_PaymentMethods_Get","Lỗi lấy dữ liệu từ phương thức thanh toán"},
{"ErridnInventory.WAS_Mst_PaymentMethods_Get","Lỗi lấy dữ liệu từ phương thức thanh toán"},
{"ErridnInventory.Mst_VATRate_CheckDB_VATRateNotFound","Không tìm thấy thuế suất VAT"},
{"ErridnInventory.Mst_VATRate_CheckDB_VATRateExist","Thuế suất đã tồn tại"},
{"ErridnInventory.Mst_VATRate_CheckDB_FlagActiveNotMatched","Trạng thái không phù hợp"},
{"ErridnInventory.Mst_VATRate_Get","Lỗi lấy dữ liệu từ thuế suất"},
{"ErridnInventory.WAS_Mst_VATRate_Get","Lỗi lấy dữ liệu từ thuế suất"},
{"ErridnInventory.Mst_GovIDType_CheckDB_GovIDTypeNotFound","Không tìm thấy mã cơ quan thuế"},
{"ErridnInventory.Mst_GovIDType_CheckDB_GovIDTypeExist","Mã cơ quan thuế đã tồn tại"},
{"ErridnInventory.Mst_GovIDType_CheckDB_FlagActiveNotMatched","Trạng thái không phù hợp"},
{"ErridnInventory.Mst_GovIDType_Get","Lỗi lấy dữ liệu cơ quan thuế"},
{"ErridnInventory.WAS_Mst_GovIDType_Get","Lỗi lấy dữ liệu cơ quan thuế"},
{"ErridnInventory.Mst_CustomerNNT_CheckDB_CustomerNNTNotFound","Không tìm thấy khách hàng"},
{"ErridnInventory.Mst_CustomerNNT_CheckDB_CustomerNNTExist","Khách hàng đã tồn tại"},
{"ErridnInventory.Mst_CustomerNNT_CheckDB_FlagActiveNotMatched","Trạng thái không phù hợp"},
{"ErridnInventory.Mst_CustomerNNT_Get","Lỗi lấy dữ liệu từ khách hàng"},
{"ErridnInventory.Mst_CustomerNNT_Create","Lỗi tạo mới khách hàng"},
{"ErridnInventory.Mst_CustomerNNT_Create_InvalidCustomerNNTCode","Mã khách hàng không hợp lệ"},
{"ErridnInventory.Mst_CustomerNNT_Create_InvalidMST","Mã số thuế không hợp lệ"},
{"ErridnInventory.Mst_CustomerNNT_Create_InvalidCustomerNNTName","Tên khách hàng không hợp lệ"},
{"ErridnInventory.Mst_CustomerNNT_Create_InvalidCustomerNNTType","Loại khách hàng không hợp lệ"},
{"ErridnInventory.Mst_CustomerNNT_Create_InvalidContactEmail","Địa chỉ email không hợp lệ"},
{"ErridnInventory.Mst_CustomerNNT_Update","Lỗi cập nhật khách hàng"},
{"ErridnInventory.Mst_CustomerNNT_Update_InvalidCustomerNNTName","Tên khách hàng không hợp lệ"},
{"ErridnInventory.Mst_CustomerNNT_Update_InvalidCustomerNNTType","Loại khách hàng không hợp lệ"},
{"ErridnInventory.Mst_CustomerNNT_Update_InvalidContactEmail","Địa chỉ email không hợp lệ"},
{"ErridnInventory.Mst_CustomerNNT_Delete","Lỗi xóa khách hàng"},
{"ErridnInventory.WAS_Mst_CustomerNNT_Get","Lỗi lấy dữ liệu khách hàng"},
{"ErridnInventory.WAS_Mst_CustomerNNT_Create","Lỗi tạo mới khách hàng"},
{"ErridnInventory.WAS_Mst_CustomerNNT_Update","Lỗi cập nhật khách hàng"},
{"ErridnInventory.WAS_Mst_CustomerNNT_Delete","Lỗi xóa khách hàng"},
{"ErridnInventory.Invoice_license_CheckDB_licenseNotFound","Không tìm thấy giấy phép"},
{"ErridnInventory.Invoice_license_CheckDB_licenseExist","Giấy phép đã tồn tại"},
{"ErridnInventory.Invoice_license_CheckDB_FlagActiveNotMatched","Trạng thái không phù hợp"},
{"ErridnInventory.Invoice_license_Get","Lỗi lấy dữ liệu từ license hóa đơn"},
{"ErridnInventory.WAS_Invoice_license_Get","Lỗi lấy dữ liệu từ license hóa đơn"},
{"ErridnInventory.iNOS_Mst_BizType_Get","Mã lỗi: ErridnInventory.iNOS_Mst_BizType_Get"},
{"ErridnInventory.WAS_iNOS_Mst_BizType_Get","Mã lỗi: ErridnInventory.WAS_iNOS_Mst_BizType_Get"},
{"ErridnInventory.iNOS_Mst_BizSize_Get","Mã lỗi: ErridnInventory.iNOS_Mst_BizSize_Get"},
{"ErridnInventory.WAS_iNOS_Mst_BizSize_Get","Mã lỗi: ErridnInventory.WAS_iNOS_Mst_BizSize_Get"},
{"ErridnInventory.iNOS_Mst_BizField_Get","Mã lỗi: ErridnInventory.iNOS_Mst_BizField_Get"},
{"ErridnInventory.WAS_iNOS_Mst_BizField_Get","Mã lỗi: ErridnInventory.WAS_iNOS_Mst_BizField_Get"},
{"ErridnInventory.Mst_Organ_CheckDB_OrganNotFound","Không tìm thấy tổ chức"},
{"ErridnInventory.Mst_Organ_CheckDB_OrganExist","Tổ chức đã tồn tại"},
{"ErridnInventory.Mst_Organ_CheckDB_FlagActiveNotMatched","Trạng thái không phù hợp"},
{"ErridnInventory.Mst_Organ_Get","Lỗi lấy dữ liệu từ tổ chức"},
{"ErridnInventory.WAS_Mst_Organ_Get","Lỗi lấy dữ liệu từ tổ chức"},
{"ErridnInventory.Mst_Organ_GetForCurrentUser","Mã lỗi: ErridnInventory.Mst_Organ_GetForCurrentUser"},
{"ErridnInventory.WAS_Mst_Organ_GetForCurrentUser","Mã lỗi: ErridnInventory.WAS_Mst_Organ_GetForCurrentUser"},
{"ErridnInventory.WAS_Mst_Organ_Create","Lỗi tạo mới tổ chức"},
{"ErridnInventory.Mst_Organ_Create","Lỗi tạo mới tổ chức"},
{"ErridnInventory.Mst_Organ_Create_InvalidOrganCode","Mã tổ chức không hợp lệ"},
{"ErridnInventory.Mst_Organ_Create_InvalidOrganName","Tên tổ chức không hợp lệ"},
{"ErridnInventory.Mst_Organ_Update","Lỗi cập nhật tổ chức"},
{"ErridnInventory.WAS_Mst_Organ_Update","Lỗi cập nhật tổ chức"},
{"ErridnInventory.Mst_Organ_UpdateX","Lỗi cập nhật tổ chức"},
{"ErridnInventory.Mst_Organ_UpdateX_InvalidOrganName","Tên tổ chức không hợp lệ"},
{"ErridnInventory.WAS_Mst_Organ_Delete","Lỗi xóa tổ chức"},
{"ErridnInventory.Mst_Organ_Delete","Lỗi xóa tổ chức"},
{"ErridnInventory.Mst_Department_CheckDB_DepartmentNotFound","Không tìm thấy phòng ban bộ phận"},
{"ErridnInventory.Mst_Department_CheckDB_DepartmentExist","Phòng ban bộ phận đã tồn tại"},
{"ErridnInventory.Mst_Department_CheckDB_FlagActiveNotMatched","Trạng thái không phù hợp"},
{"ErridnInventory.Mst_Department_Get","Lỗi lấy dữ liệu từ bộ phận phòng ban"},
{"ErridnInventory.WAS_Mst_Department_Get","Lỗi lấy dữ liệu từ bộ phận phòng ban"},
{"ErridnInventory.WAS_Mst_Department_Create","Lỗi tạo mới dữ liệu bộ phận phòng ban"},
{"ErridnInventory.Mst_Department_Create","Lỗi tạo mới dữ liệu bộ phận phòng ban"},
{"ErridnInventory.Mst_Department_Create_InvalidDepartmentCode","Mã bộ phận phòng ban không hợp lệ"},
{"ErridnInventory.Mst_Department_Create_InvalidDepartmentName","Tên bộ phận phòng ban không hợp lệ"},
{"ErridnInventory.Mst_Department_Create_InvalidOrganCode","Mã tổ chức không hợp lệ"},
{"ErridnInventory.WAS_Mst_Department_Update","Lỗi cập nhật bộ phận phòng ban"},
{"ErridnInventory.Mst_Department_Update","Lỗi cập nhật bộ phận phòng ban"},
{"ErridnInventory.WAS_Mst_Department_Delete","Lỗi xóa bộ phận phòng ban"},
{"ErridnInventory.Mst_Department_Delete","Lỗi xóa bộ phận phòng ban"},
{"ErridnInventory.Mst_Department_UpdateX","Lỗi cập nhật bộ phận phòng ban"},
{"ErridnInventory.Mst_Department_UpdateX_InvalidDepartmentName","Tên phòng ban không hợp lệ"},
{"ErridnInventory.Mst_Department_UpdateX_InvalidOrganCode","Mã tổ chức không hợp lệ"},
{"ErridnInventory.Mst_PaymentPartnerType_CheckDB_PaymentPartnerTypeNotFound","Không tìm thấy đơn vị thanh toán"},
{"ErridnInventory.Mst_PaymentPartnerType_CheckDB_PaymentPartnerTypeExist","Đơn vị thanh toán đã tồn tại"},
{"ErridnInventory.Mst_PaymentPartnerType_CheckDB_FlagActiveNotMatched","Trạng thái không phù hợp"},
{"ErridnInventory.Mst_PaymentPartnerType_Get","Lỗi lấy dữ liệu đơn vị thanh toán"},
{"ErridnInventory.WAS_Mst_PaymentPartnerType_Get","Lỗi lấy dữ liệu đơn vị thanh toán"},
{"ErridnInventory.WAS_Mst_PaymentPartnerType_Create","Lỗi tạo mới loại đơn vị thanh toán"},
{"ErridnInventory.Mst_PaymentPartnerType_Create","Lỗi tạo mới loại đơn vị thanh toán"},
{"ErridnInventory.Mst_PaymentPartnerType_CreateX","Lỗi tạo mới loại đơn vị thanh toán"},
{"ErridnInventory.Mst_PaymentPartnerType_CreateX_InvalidPaymentPartnerType","Loại đơn vị thanh toán không hợp lệ"},
{"ErridnInventory.Mst_PaymentPartnerType_CreateX_InvalidPaymentPartnerTypeName","Tên loại đơn vị thanh toán không hợp lệ"},
{"ErridnInventory.WAS_Mst_PaymentPartnerType_Update","Lỗi cập nhật loại đơn vị thanh toán"},
{"ErridnInventory.Mst_PaymentPartnerType_Update","Lỗi cập nhật loại đơn vị thanh toán"},
{"ErridnInventory.Mst_PaymentPartnerType_UpdateX","Lỗi cập nhật loại đơn vị thanh toán"},
{"ErridnInventory.Mst_PaymentPartnerType_UpdateX_InvalidPaymentPartnerTypeName","Tên loại đơn vị thanh toán không hợp lệ"},
{"ErridnInventory.WAS_Mst_PaymentPartnerType_Delete","Lỗi xóa loại đơn vị thanh toán"},
{"ErridnInventory.Mst_PaymentPartnerType_Delete","Lỗi xóa loại đơn vị thanh toán"},
{"ErridnInventory.Mst_PaymentPartnerType_DeleteX","Lỗi xóa loại đơn vị thanh toán"},
{"ErridnInventory.Mst_PaymentPartner_CheckDB_PaymentPartnerNotFound","Không tìm thấy đơn vị thanh toán"},
{"ErridnInventory.Mst_PaymentPartner_CheckDB_PaymentPartnerExist","Đơn vị thanh toán đã tồn tại"},
{"ErridnInventory.Mst_PaymentPartner_CheckDB_FlagActiveNotMatched","Trạng thái không phù hợp"},
{"ErridnInventory.WAS_Mst_PaymentPartner_Get","Lỗi lấy dữ liệu đơn vị thanh toán"},
{"ErridnInventory.Mst_PaymentPartner_Get","Lỗi lấy dữ liệu đơn vị thanh toán"},
{"ErridnInventory.WAS_Mst_PaymentPartner_Create","Lỗi tạo dữ liệu đơn vị thanh toán"},
{"ErridnInventory.Mst_PaymentPartner_Create","Lỗi tạo dữ liệu đơn vị thanh toán"},
{"ErridnInventory.Mst_PaymentPartner_CreateX","Lỗi tạo dữ liệu đơn vị thanh toán"},
{"ErridnInventory.Mst_PaymentPartner_CreateX_InvalidPaymentPartnerCode","Mã đơn vị thanh toán không hợp lệ"},
{"ErridnInventory.Mst_PaymentPartner_CreateX_InvalidPaymentPartnerName","Tên đơn vị thanh toán không hợp lệ"},
{"ErridnInventory.WAS_Mst_PaymentPartner_Update","Lỗi cập nhật đơn vị thanh toán"},
{"ErridnInventory.Mst_PaymentPartner_Update","Lỗi cập nhật đơn vị thanh toán"},
{"ErridnInventory.Mst_PaymentPartner_UpdateX","Lỗi cập nhật đơn vị thanh toán"},
{"ErridnInventory.Mst_PaymentPartner_UpdateX_InvalidPaymentPartnerName","Tên đơn vị thanh toán không hợp lệ"},
{"ErridnInventory.WAS_Mst_PaymentPartner_Delete","Lỗi xóa đơn vị thanh toán"},
{"ErridnInventory.Mst_PaymentPartner_Delete","Lỗi xóa đơn vị thanh toán"},
{"ErridnInventory.Mst_PaymentPartner_DeleteX","Lỗi xóa đơn vị thanh toán"},
{"ErridnInventory.Mst_Representative_CheckDB_RepresentativeNotFound","Không tìm thấyngười đại diện"},
{"ErridnInventory.Mst_Representative_CheckDB_RepresentativeExist","Người đại diện đã tồn tại"},
{"ErridnInventory.Mst_Representative_CheckDB_FlagActiveNotMatched","Trạng thái không phù hợp"},
{"ErridnInventory.WAS_Mst_Representative_Get","Lỗi lấy dữ liệu từ người đại diện"},
{"ErridnInventory.Mst_Representative_Get","Lỗi lấy dữ liệu từ người đại diện"},
{"ErridnInventory.Mst_Representative_Create","Lỗi tạo mới người đại diện"},
{"ErridnInventory.WAS_Mst_Representative_Create","Lỗi tạo mới người đại diện"},
{"ErridnInventory.Mst_Representative_CreateX","Lỗi tạo mới người đại diện"},
{"ErridnInventory.Mst_Representative_CreateX_InvalidRepresentativeCode","Mã người đại diện không hợp lệ"},
{"ErridnInventory.Mst_Representative_CreateX_InvalidRepresentativeName","Tên người đại diện không hợp lệ"},
{"ErridnInventory.Mst_Representative_CreateX_InvalidOrganCode","Mã tổ chức không hợp lệ"},
{"ErridnInventory.Mst_Representative_CreateX_IDCardDateIssueAfterIDCardDateExpiry","Ngày phát hành phải trước ngày hết hạn"},
{"ErridnInventory.Mst_Representative_CreateX_ProxyDateIssueAfterProxyDateExpiry","Ngày phát hành phải trước ngày ủy quyền"},
{"ErridnInventory.Mst_Representative_CreateX_InputRepresentativeFileUploadTblNotFound","Không tìm thấy file tải lên"},
{"ErridnInventory.Mst_Representative_CreateX_InputRepresentativeFileUploadTblInvalid","File tải lên không hợp lệ"},
{"ErridnInventory.Mst_Representative_Update","Lỗi cập nhật người đại diện"},
{"ErridnInventory.WAS_Mst_Representative_Update","Lỗi cập nhật người đại diện"},
{"ErridnInventory.Mst_Representative_UpdateX","Lỗi cập nhật người đại diện"},
{"ErridnInventory.Mst_Representative_UpdateX_InvalidRepresentativeCode","Mã người đại diện không hợp lệ"},
{"ErridnInventory.Mst_Representative_UpdateX_InvalidRepresentativeName","Tên người đại diện không hợp lệ"},
{"ErridnInventory.Mst_Representative_UpdateX_IDCardDateIssueAfterIDCardDateExpiry","Ngày bắt đầu của giấy tờ phải nhỏ  hơn ngày kết thúc "},
{"ErridnInventory.Mst_Representative_UpdateX_ProxyDateIssueAfterProxyDateExpiry","Ngày ban hành ủy quyền phải trước ngày hết hạn"},
{"ErridnInventory.Mst_Representative_UpdateX_InputRepresentativeFileUploadTblNotFound","Không tìm thấy file tải lên"},
{"ErridnInventory.Mst_Representative_UpdateX_InputRepresentativeFileUploadTblInvalid","File tải lên không hợp lệ"},
{"ErridnInventory.Mst_Representative_Delete","Lỗi xóa người đại diện"},
{"ErridnInventory.WAS_Mst_Representative_Delete","Lỗi xóa người đại diện"},
{"ErridnInventory.Mst_RepresentativeFileUpload_CheckDB_AutoIdNotFound","Không tìm thấy mục tự động"},
{"ErridnInventory.Mst_RepresentativeFileUpload_CheckDB_AutoIdExist","Mục tự động đã tồn tại"},
{"ErridnInventory.Mst_RepresentativeFileUpload_CheckDB_FlagActiveNotMatched","Trạng thái không phù hợp"},
{"ErridnInventory.WAS_Mst_RepresentativeFileUpload_Get","Lỗi lấy dữ liệu từ file đang tải lên"},
{"ErridnInventory.Mst_RepresentativeFileUpload_Get","Lỗi lấy dữ liệu từ file đang tải lên"},
{"ErridnInventory.WAS_Mst_RepresentativeFileUpload_Create","Lỗi tạo mới file người đại diện"},
{"ErridnInventory.Mst_RepresentativeFileUpload_Create","Lỗi tạo mới file người đại diện"},
{"ErridnInventory.Mst_RepresentativeFileUpload_Create_InvalidFilePath","Đường dẫn tệp không hợp lệ"},
{"ErridnInventory.Mst_RepresentativeFileUpload_Update","Lỗi cập nhật file"},
{"ErridnInventory.WAS_Mst_RepresentativeFileUpload_Update","Lỗi cập nhật file"},
{"ErridnInventory.Mst_RepresentativeFileUpload_UpdateX","Lỗi cập nhật file"},
{"ErridnInventory.Mst_RepresentativeFileUpload_UpdateX_InvalidFilePath","Đường dẫn tệp không hợp lệ"},
{"ErridnInventory.Mst_RepresentativeFileUpload_Delete","Lỗi xóa file"},
{"ErridnInventory.WAS_Mst_RepresentativeFileUpload_Delete","Lỗi xóa file"},
{"ErridnInventory.Rpt_InvoiceInvoice_ResultUsed","Nguyên nhân sử dụng"},
{"ErridnInventory.WAS_Rpt_InvoiceInvoice_ResultUsed","Nguyên nhân sử dụng"},
{"ErridnInventory.Rpt_Budget_ProjectPlan","Mã lỗi: ErridnInventory.Rpt_Budget_ProjectPlan"},
{"ErridnInventory.WAS_Rpt_Budget_ProjectPlan","Mã lỗi: ErridnInventory.WAS_Rpt_Budget_ProjectPlan"},
{"ErridnInventory.Rpt_OrganDebt","Mã lỗi: ErridnInventory.Rpt_OrganDebt"},
{"ErridnInventory.WAS_Rpt_OrganDebt","Mã lỗi: ErridnInventory.WAS_Rpt_OrganDebt"},
{"ErridnInventory._Rpt_KUNN_KUNNDtl_01","Mã lỗi: ErridnInventory._Rpt_KUNN_KUNNDtl_01"},
{"ErridnInventory.WAS_Rpt_KUNN_KUNNDtl_01","Mã lỗi: ErridnInventory.WAS_Rpt_KUNN_KUNNDtl_01"},
{"ErridnInventory.Rpt_KUNN_CalcValLaiPeriod","Mã lỗi: ErridnInventory.Rpt_KUNN_CalcValLaiPeriod"},
{"ErridnInventory.WAS_Rpt_KUNN_CalcValLaiPeriod","Mã lỗi: ErridnInventory.WAS_Rpt_KUNN_CalcValLaiPeriod"},
{"Erridn.Skycic.Inventory.Seq_Common","Mã lỗi: Erridn.Skycic.Inventory.Seq_Common"},
{"Erridn.Skycic.Inventory.WAS_Seq_Common_Get","Lỗi lấy dữ liệu chung"},
{"Erridn.Skycic.Inventory.WAS_Seq_FormNo_Get","Lỗi lấy dữ liệu mẫu "},
{"Erridn.Skycic.Inventory.Seq_TCTTranNo_Get","Mã lỗi: Erridn.Skycic.Inventory.Seq_TCTTranNo_Get"},
{"Erridn.Skycic.Inventory.Seq_InvoiceCode_Get","Lỗi mã hóa đơn"},
{"Erridn.Skycic.Inventory.WAS_Seq_TCTTranNo_Get","Mã lỗi: Erridn.Skycic.Inventory.WAS_Seq_TCTTranNo_Get"},
{"Erridn.Skycic.Inventory.WAS_Seq_InvoiceCode_Get","Lỗi mã hóa đơn"},
{"Erridn.Skycic.Inventory.Seq_TVANTranNo_Get","Mã lỗi: Erridn.Skycic.Inventory.Seq_TVANTranNo_Get"},
{"Erridn.Skycic.Inventory.WAS_Seq_TVANTranNo_Get","Mã lỗi: Erridn.Skycic.Inventory.WAS_Seq_TVANTranNo_Get"},
{"Erridn.Skycic.Inventory.TCT_Err","Mã lỗi: Erridn.Skycic.Inventory.TCT_Err"},
{"ErridnInventory.TCT_NhanHSoThue_BaseWCF","Mã lỗi: ErridnInventory.TCT_NhanHSoThue_BaseWCF"},
{"ErridnInventory.WAS_TCT_NhanHSoThue_BaseWCF","Mã lỗi: ErridnInventory.WAS_TCT_NhanHSoThue_BaseWCF"},
{"ErridnInventory.TCT_TraKQuaGDich_BaseHTTPReq","Mã lỗi: ErridnInventory.TCT_TraKQuaGDich_BaseHTTPReq"},
{"ErridnInventory.WAS_TCT_TraKQuaGDich_BaseHTTPReq","Mã lỗi: ErridnInventory.WAS_TCT_TraKQuaGDich_BaseHTTPReq"},
{"ErridnInventory.TCT_TraTTinMaSoThue_BaseHTTPReq","Mã lỗi: ErridnInventory.TCT_TraTTinMaSoThue_BaseHTTPReq"},
{"ErridnInventory.WAS_TCT_TraTTinMaSoThue_BaseHTTPReq","Mã lỗi: ErridnInventory.WAS_TCT_TraTTinMaSoThue_BaseHTTPReq"},
{"ErridnInventory.TCT_TraTThaiMaSoThue_BaseHTTPReq","Mã lỗi: ErridnInventory.TCT_TraTThaiMaSoThue_BaseHTTPReq"},
{"ErridnInventory.WAS_TCT_TraTThaiMaSoThue_BaseHTTPReq","Mã lỗi: ErridnInventory.WAS_TCT_TraTThaiMaSoThue_BaseHTTPReq"},
{"ErridnInventory.WAS_TCT_NhanHSoXML_BaseWCF","Mã lỗi: ErridnInventory.WAS_TCT_NhanHSoXML_BaseWCF"},
{"ErridnInventory.TCT_NhanHSoXML_BaseWCF","Mã lỗi: ErridnInventory.TCT_NhanHSoXML_BaseWCF"},
{"ErridnInventory.TCT_NhanPLucHSoThue_BaseWCF","Mã lỗi: ErridnInventory.TCT_NhanPLucHSoThue_BaseWCF"},
{"ErridnInventory.WAS_TCT_NhanPLucHSoThue_BaseWCF","Mã lỗi: ErridnInventory.WAS_TCT_NhanPLucHSoThue_BaseWCF"},
{"ErridnInventory.WAS_TCT_NhanHSoXML_BaseHTTPReq","Mã lỗi: ErridnInventory.WAS_TCT_NhanHSoXML_BaseHTTPReq"},
{"ErridnInventory.TCT_NhanHSoXML_BaseHTTPReq","Mã lỗi: ErridnInventory.TCT_NhanHSoXML_BaseHTTPReq"},
{"ErridnInventory.TCT_TraKQuaPhienGDich_BaseHTTPReq","Mã lỗi: ErridnInventory.TCT_TraKQuaPhienGDich_BaseHTTPReq"},
{"ErridnInventory.WAS_TCT_TraKQuaPhienGDich_BaseHTTPReq","Mã lỗi: ErridnInventory.WAS_TCT_TraKQuaPhienGDich_BaseHTTPReq"},
{"ErrHTC.Email_BatchSendEmail_CheckDB_BatchSendEmailNotFound","Không tìm thấy email người nhận"},
{"ErrHTC.Email_BatchSendEmail_CheckDB_BatchSendEmailExist","Email người nhận đã tồn tại"},
{"ErrHTC.Email_BatchSendEmail_CheckDB_StatusNotMatched","Trạng thái không phù hợp"},
{"ErrHTC.Email_BatchSendEmail_Send","Lỗi gửi email"},
{"ErrHTC.Email_BatchSendEmail_SaveAndSend","Lỗi lưu và gửi email"},
{"ErrHTC.Email_BatchSendEmail_MstSv_Inos_User_Send","Email gửi cho người dùng bị lỗi"},
{"ErrHTC.WAS_Email_BatchSendEmail_SaveAndSend","Lưu và gửi email bị lỗi"},
{"ErrHTC.WAS_Email_BatchSendEmail_MstSv_Inos_User_Send","Email gửi cho người dùng bị lỗi"},
{"ErrHTC.Email_BatchSendEmail_SaveX","Lỗi gửi email"},
{"ErrHTC.Email_BatchSendEmail_SaveX_InvalidDlrSignStatus","Trạng thái chữ ký không hợp lệ"},
{"ErrHTC.Email_BatchSendEmail_SaveX_InvalidValue","Giá trị không hợp lệ"},
{"ErrHTC.Email_BatchSendEmail_SaveX_InvalidT24_Status","Trạng thái T24 không hợp lệ"},
{"ErrHTC.Email_BatchSendEmail_SaveX_Input_Email_BatchSendEmailToTblNotFound","Không tìm thấy email người nhận"},
{"ErrHTC.Email_BatchSendEmail_SaveX_Input_Email_BatchSendEmailToTblInvalid","Địa chỉ email người nhận không hợp lệ"},
{"ErrHTC.Email_BatchSendEmail_SaveX_Input_Email_BatchSendEmailCCTblNotFound","Không tìm thấy email người nhận"},
{"ErrHTC.Email_BatchSendEmail_SaveX_Input_Email_BatchSendEmailCCTblInvalid","Địa chỉ email người nhận không hợp lệ"},
{"ErrHTC.Email_BatchSendEmail_SaveX_Input_Email_BatchSendEmailBCCTblNotFound","Không tìm thấy hàng loạt email gửi"},
{"ErrHTC.Email_BatchSendEmail_SaveX_Input_Email_BatchSendEmailBCCTblInvalid","Địa chỉ email người nhận không hợp lệ"},
{"ErrHTC.Email_BatchSendEmail_SaveX_Input_Email_BatchSendEmailFileAttachTblNotFound","Không tìm thấy file đính kèm"},
{"ErrHTC.Email_BatchSendEmail_SaveX_Input_Email_BatchSendEmailFileAttachTblInvalid","File đính kèm không hợp lệ"},
{"ErrHTC.Email_BatchSendEmail_SaveX_Input_DMS40_CT_DealerContractDtlTbl_InvalidT24_CIFKH","T24 không hợp lệ"},
{"ErrHTC.Email_BatchSendEmail_SaveX_Input_InvalidPaymentType","Loại thanh toán không hợp lệ"},
{"ErrHTC.Email_BatchSendEmail_SaveX_InvalidOneAssemblyStatus","Tình trạng không hợp lệ"},
{"ErrHTC.Email_BatchSendEmail_SaveX_InvalidOneSOType","Mã lỗi: ErrHTC.Email_BatchSendEmail_SaveX_InvalidOneSOType"},
{"ErrHTC.Email_BatchSendEmail_SendForDealerContractUpdBankCodeMD","Mã lỗi: ErrHTC.Email_BatchSendEmail_SendForDealerContractUpdBankCodeMD"},
{"ErrHTC.Email_BatchSendEmail_SendForDealerContractUpdBankCodeMDX","Mã lỗi: ErrHTC.Email_BatchSendEmail_SendForDealerContractUpdBankCodeMDX"},
{"ErrHTC.Invoice_TempGroup_CheckDB_InvoiceTGroupCodeNotFound","Không tìm thấy nhóm người dùng"},
{"ErrHTC.Invoice_TempGroup_CheckDB_InvoiceTGroupCodeExist","Nhóm người dùng đã tồn tại"},
{"ErrHTC.Invoice_TempGroup_CheckDB_FlagActiveNotMatched","Trạng thái không phù hợp"},
{"ErrHTC.Invoice_TempGroup_Get","Lỗi lấy dữ liệu nhóm mẫu hóa đơn"},
{"ErrHTC.Invoice_TempGroup_Create","Lỗi tạo mới dữ liệu nhóm mẫu hóa đơn"},
{"ErrHTC.Invoice_TempGroup_Create_InvalidInvoiceTGroupCode","Mã nhóm người dùng không hợp lệ"},
{"ErrHTC.Invoice_TempGroup_Create_InvalidInvoiceTGroupName","Tên nhóm người dùng không hợp lệ"},
{"ErrHTC.Invoice_TempGroup_Create_InvalidSpec_Prd_Type","Loại sản phẩm không hợp lệ"},
{"ErrHTC.Invoice_TempGroup_Update","Lỗi cập nhật nhóm mẫu hóa đơn"},
{"ErrHTC.Invoice_TempGroup_Update_InvalidProvinceName","Tên tỉnh không hợp lệ"},
{"ErrHTC.Invoice_TempGroup_Update_InvalidSpec_Prd_Type","Loại sản phẩm không hợp lệ"},
{"ErrHTC.Invoice_TempGroup_Delete","Lỗi xóa nhóm mẫu hóa đơn"},
{"ErrHTC.WAS_Invoice_TempGroup_Get","Lỗi lấy dữ liệu nhóm mẫu hóa đơn"},
{"ErrHTC.WAS_Invoice_TempGroup_Create","Lỗi tạo mới nhóm mẫu hóa đơn"},
{"ErrHTC.WAS_Invoice_TempGroup_Update","Lỗi cập nhật nhóm mẫu hóa đơn"},
{"ErrHTC.WAS_Invoice_TempGroup_Delete","Lỗi xóa nhóm mẫu hóa đơn"},
{"ErridnInventory.Sys_User_CheckAuthentication_InvalidPassword","Mật khẩu người dùng không đúng"},
{"ErridnInventory.Sys_User_CheckDB_UserCodeNotFound","Người dùng không tồn tại"},
{"ErrorCode: Sys_Access_CheckDeny","Lỗi không cho phép truy cập"},
{"ErrorCode: ErridnInventory.Mst_NNT_CheckDB_NNTExist","Người nộp thuế đã tồn tại"},
{"ErrorCode: ErridnInventory.Inos_AccountService_CreateUser","Email liên hệ đã tồn tại"},
{"ErrorCode: ErridnInventory.Inos_OrderService_GetDiscountCode","Mã giảm giá không tồn tại"},
{"ErrorCode: ErridnInventory.Inos_AccountService_RequestToken","Email hoặc mật khẩu không hợp lệ. Vui lòng kiểm tra lại."},
{"ErrorCode: ErridnInventory.Invoice_Invoice_SaveX_Input_InvoiceDtl_SpecCodeDuplicate","Mã hàng hóa bị trùng"},
{"ErrorCode: ErridnInventory.myCheck_Invoice_InvoiceDtl_Total_InvalidValue","Giá trị hóa đơn không hợp lệ"},
{"ErrorCode: ErridnInventory.Invoice_Invoice_UpdAfterAllocatedX_InvalidInvoiceDateUTC","Ngày hóa đơn không hợp lệ"},
{"ErridnInventory.Inos_OrderService_GetDiscountCode","Mã giảm giá ko hợp lệ"}

////

			};
            if (errDict.ContainsKey(errCode))
            {
                errContent = errDict[errCode];
            }
            else
            {
                errContent = "Lỗi!";
            }

            return errContent;
        }

        public static string GetErrorMessage(string strkey)
        {
            var error = "";
            error = GetErrDict(strkey);
            return error;
        }
    }
}
