//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace idn.Skycic.Inventory.Biz.WSNhanHSoThue {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", ConfigurationName="WSNhanHSoThue.NhanHSoThueService")]
    public interface NhanHSoThueService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        idn.Skycic.Inventory.Biz.WSNhanHSoThue.getDsachTbaoResponse getDsachTbao(idn.Skycic.Inventory.Biz.WSNhanHSoThue.getDsachTbaoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSNhanHSoThue.getDsachTbaoResponse> getDsachTbaoAsync(idn.Skycic.Inventory.Biz.WSNhanHSoThue.getDsachTbaoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        idn.Skycic.Inventory.Biz.WSNhanHSoThue.getTbaoResponse getTbao(idn.Skycic.Inventory.Biz.WSNhanHSoThue.getTbaoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSNhanHSoThue.getTbaoResponse> getTbaoAsync(idn.Skycic.Inventory.Biz.WSNhanHSoThue.getTbaoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        idn.Skycic.Inventory.Biz.WSNhanHSoThue.getxmlTBaoLan2Response getxmlTBaoLan2(idn.Skycic.Inventory.Biz.WSNhanHSoThue.getxmlTBaoLan2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSNhanHSoThue.getxmlTBaoLan2Response> getxmlTBaoLan2Async(idn.Skycic.Inventory.Biz.WSNhanHSoThue.getxmlTBaoLan2Request request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        idn.Skycic.Inventory.Biz.WSNhanHSoThue.getTBaoLan2Response getTBaoLan2(idn.Skycic.Inventory.Biz.WSNhanHSoThue.getTBaoLan2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSNhanHSoThue.getTBaoLan2Response> getTBaoLan2Async(idn.Skycic.Inventory.Biz.WSNhanHSoThue.getTBaoLan2Request request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoThueResponse nhanHSoThue(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoThueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoThueResponse> nhanHSoThueAsync(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoThueRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanToKhaiThueResponse nhanToKhaiThue(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanToKhaiThueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanToKhaiThueResponse> nhanToKhaiThueAsync(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanToKhaiThueRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanPLucHSoThueResponse nhanPLucHSoThue(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanPLucHSoThueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanPLucHSoThueResponse> nhanPLucHSoThueAsync(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanPLucHSoThueRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanPLucHSoHoanThueResponse nhanPLucHSoHoanThue(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanPLucHSoHoanThueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanPLucHSoHoanThueResponse> nhanPLucHSoHoanThueAsync(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanPLucHSoHoanThueRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoQTThueTNCNResponse nhanHSoQTThueTNCN(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoQTThueTNCNRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoQTThueTNCNResponse> nhanHSoQTThueTNCNAsync(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoQTThueTNCNRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoQTThueTNCNCoIdResponse nhanHSoQTThueTNCNCoId(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoQTThueTNCNCoIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoQTThueTNCNCoIdResponse> nhanHSoQTThueTNCNCoIdAsync(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoQTThueTNCNCoIdRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanBCAnChiResponse nhanBCAnChi(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanBCAnChiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanBCAnChiResponse> nhanBCAnChiAsync(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanBCAnChiRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanBCAnChiTuDLTResponse nhanBCAnChiTuDLT(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanBCAnChiTuDLTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanBCAnChiTuDLTResponse> nhanBCAnChiTuDLTAsync(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanBCAnChiTuDLTRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanPLucHSoThueTuDLTResponse nhanPLucHSoThueTuDLT(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanPLucHSoThueTuDLTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanPLucHSoThueTuDLTResponse> nhanPLucHSoThueTuDLTAsync(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanPLucHSoThueTuDLTRequest request);
        
        // CODEGEN: Generating message contract since the operation nhanHSoXML is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoXMLResponse1 nhanHSoXML(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoXMLResponse1> nhanHSoXMLAsync(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoXMLRequest request);
        
        // CODEGEN: Generating message contract since the operation nhanHSoXMLCoId is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoXMLCoIdResponse1 nhanHSoXMLCoId(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoXMLCoIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoXMLCoIdResponse1> nhanHSoXMLCoIdAsync(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoXMLCoIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDsachTbao", WrapperNamespace="http://nhanhsothue.van.gdt.gov.vn/", IsWrapped=true)]
    public partial class getDsachTbaoRequest {
        
        public getDsachTbaoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDsachTbaoResponse", WrapperNamespace="http://nhanhsothue.van.gdt.gov.vn/", IsWrapped=true)]
    public partial class getDsachTbaoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public getDsachTbaoResponse() {
        }
        
        public getDsachTbaoResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTbao", WrapperNamespace="http://nhanhsothue.van.gdt.gov.vn/", IsWrapped=true)]
    public partial class getTbaoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=0)]
        public string idTbao;
        
        public getTbaoRequest() {
        }
        
        public getTbaoRequest(string idTbao) {
            this.idTbao = idTbao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTbaoResponse", WrapperNamespace="http://nhanhsothue.van.gdt.gov.vn/", IsWrapped=true)]
    public partial class getTbaoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string @return;
        
        public getTbaoResponse() {
        }
        
        public getTbaoResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getxmlTBaoLan2", WrapperNamespace="http://nhanhsothue.van.gdt.gov.vn/", IsWrapped=true)]
    public partial class getxmlTBaoLan2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string maTbao;
        
        public getxmlTBaoLan2Request() {
        }
        
        public getxmlTBaoLan2Request(string maTbao) {
            this.maTbao = maTbao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getxmlTBaoLan2Response", WrapperNamespace="http://nhanhsothue.van.gdt.gov.vn/", IsWrapped=true)]
    public partial class getxmlTBaoLan2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string @return;
        
        public getxmlTBaoLan2Response() {
        }
        
        public getxmlTBaoLan2Response(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTBaoLan2", WrapperNamespace="http://nhanhsothue.van.gdt.gov.vn/", IsWrapped=true)]
    public partial class getTBaoLan2Request {
        
        public getTBaoLan2Request() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTBaoLan2Response", WrapperNamespace="http://nhanhsothue.van.gdt.gov.vn/", IsWrapped=true)]
    public partial class getTBaoLan2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public getTBaoLan2Response() {
        }
        
        public getTBaoLan2Response(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="nhanHSoThue", WrapperNamespace="http://nhanhsothue.van.gdt.gov.vn/", IsWrapped=true)]
    public partial class nhanHSoThueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string maLoaiGDich;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string dlieuHSo;
        
        public nhanHSoThueRequest() {
        }
        
        public nhanHSoThueRequest(string maLoaiGDich, string dlieuHSo) {
            this.maLoaiGDich = maLoaiGDich;
            this.dlieuHSo = dlieuHSo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="nhanHSoThueResponse", WrapperNamespace="http://nhanhsothue.van.gdt.gov.vn/", IsWrapped=true)]
    public partial class nhanHSoThueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public nhanHSoThueResponse() {
        }
        
        public nhanHSoThueResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="nhanToKhaiThue", WrapperNamespace="http://nhanhsothue.van.gdt.gov.vn/", IsWrapped=true)]
    public partial class nhanToKhaiThueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string lanNop;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string dlieuHSo;
        
        public nhanToKhaiThueRequest() {
        }
        
        public nhanToKhaiThueRequest(string lanNop, string dlieuHSo) {
            this.lanNop = lanNop;
            this.dlieuHSo = dlieuHSo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="nhanToKhaiThueResponse", WrapperNamespace="http://nhanhsothue.van.gdt.gov.vn/", IsWrapped=true)]
    public partial class nhanToKhaiThueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public nhanToKhaiThueResponse() {
        }
        
        public nhanToKhaiThueResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="nhanPLucHSoThue", WrapperNamespace="http://nhanhsothue.van.gdt.gov.vn/", IsWrapped=true)]
    public partial class nhanPLucHSoThueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tIN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string maTKhai;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string loaiTKhai;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string kyKKhai;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string maCQTNoiNop;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string maPLuc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string dlieuHSo;
        
        public nhanPLucHSoThueRequest() {
        }
        
        public nhanPLucHSoThueRequest(string tIN, string maTKhai, string loaiTKhai, string kyKKhai, string maCQTNoiNop, string maPLuc, string dlieuHSo) {
            this.tIN = tIN;
            this.maTKhai = maTKhai;
            this.loaiTKhai = loaiTKhai;
            this.kyKKhai = kyKKhai;
            this.maCQTNoiNop = maCQTNoiNop;
            this.maPLuc = maPLuc;
            this.dlieuHSo = dlieuHSo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="nhanPLucHSoThueResponse", WrapperNamespace="http://nhanhsothue.van.gdt.gov.vn/", IsWrapped=true)]
    public partial class nhanPLucHSoThueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public nhanPLucHSoThueResponse() {
        }
        
        public nhanPLucHSoThueResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="nhanPLucHSoHoanThue", WrapperNamespace="http://nhanhsothue.van.gdt.gov.vn/", IsWrapped=true)]
    public partial class nhanPLucHSoHoanThueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string idHso;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string maGTBS;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string hthanhGTBS;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string ndungFile;
        
        public nhanPLucHSoHoanThueRequest() {
        }
        
        public nhanPLucHSoHoanThueRequest(string idHso, string maGTBS, string hthanhGTBS, string ndungFile) {
            this.idHso = idHso;
            this.maGTBS = maGTBS;
            this.hthanhGTBS = hthanhGTBS;
            this.ndungFile = ndungFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="nhanPLucHSoHoanThueResponse", WrapperNamespace="http://nhanhsothue.van.gdt.gov.vn/", IsWrapped=true)]
    public partial class nhanPLucHSoHoanThueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public nhanPLucHSoHoanThueResponse() {
        }
        
        public nhanPLucHSoHoanThueResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="nhanHSoQTThueTNCN", WrapperNamespace="http://nhanhsothue.van.gdt.gov.vn/", IsWrapped=true)]
    public partial class nhanHSoQTThueTNCNRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tIN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string maTKhai;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string loaiTKhai;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string kyKKhai;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string maCQTNoiNop;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string dlieuHSo;
        
        public nhanHSoQTThueTNCNRequest() {
        }
        
        public nhanHSoQTThueTNCNRequest(string tIN, string maTKhai, string loaiTKhai, string kyKKhai, string maCQTNoiNop, string dlieuHSo) {
            this.tIN = tIN;
            this.maTKhai = maTKhai;
            this.loaiTKhai = loaiTKhai;
            this.kyKKhai = kyKKhai;
            this.maCQTNoiNop = maCQTNoiNop;
            this.dlieuHSo = dlieuHSo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="nhanHSoQTThueTNCNResponse", WrapperNamespace="http://nhanhsothue.van.gdt.gov.vn/", IsWrapped=true)]
    public partial class nhanHSoQTThueTNCNResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public nhanHSoQTThueTNCNResponse() {
        }
        
        public nhanHSoQTThueTNCNResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="nhanHSoQTThueTNCNCoId", WrapperNamespace="http://nhanhsothue.van.gdt.gov.vn/", IsWrapped=true)]
    public partial class nhanHSoQTThueTNCNCoIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tIN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string maTKhai;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string loaiTKhai;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string kyKKhai;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string maCQTNoiNop;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IdHso;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string dlieuHSo;
        
        public nhanHSoQTThueTNCNCoIdRequest() {
        }
        
        public nhanHSoQTThueTNCNCoIdRequest(string tIN, string maTKhai, string loaiTKhai, string kyKKhai, string maCQTNoiNop, string IdHso, string dlieuHSo) {
            this.tIN = tIN;
            this.maTKhai = maTKhai;
            this.loaiTKhai = loaiTKhai;
            this.kyKKhai = kyKKhai;
            this.maCQTNoiNop = maCQTNoiNop;
            this.IdHso = IdHso;
            this.dlieuHSo = dlieuHSo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="nhanHSoQTThueTNCNCoIdResponse", WrapperNamespace="http://nhanhsothue.van.gdt.gov.vn/", IsWrapped=true)]
    public partial class nhanHSoQTThueTNCNCoIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public nhanHSoQTThueTNCNCoIdResponse() {
        }
        
        public nhanHSoQTThueTNCNCoIdResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="nhanBCAnChi", WrapperNamespace="http://nhanhsothue.van.gdt.gov.vn/", IsWrapped=true)]
    public partial class nhanBCAnChiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tIN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string maTKhai;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string kyKKhai;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string dlieuHSo;
        
        public nhanBCAnChiRequest() {
        }
        
        public nhanBCAnChiRequest(string tIN, string maTKhai, string kyKKhai, string dlieuHSo) {
            this.tIN = tIN;
            this.maTKhai = maTKhai;
            this.kyKKhai = kyKKhai;
            this.dlieuHSo = dlieuHSo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="nhanBCAnChiResponse", WrapperNamespace="http://nhanhsothue.van.gdt.gov.vn/", IsWrapped=true)]
    public partial class nhanBCAnChiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public nhanBCAnChiResponse() {
        }
        
        public nhanBCAnChiResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="nhanBCAnChiTuDLT", WrapperNamespace="http://nhanhsothue.van.gdt.gov.vn/", IsWrapped=true)]
    public partial class nhanBCAnChiTuDLTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tIN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string maTKhai;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string kyKKhai;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string dlieuHSo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mstDLyThue;
        
        public nhanBCAnChiTuDLTRequest() {
        }
        
        public nhanBCAnChiTuDLTRequest(string tIN, string maTKhai, string kyKKhai, string dlieuHSo, string mstDLyThue) {
            this.tIN = tIN;
            this.maTKhai = maTKhai;
            this.kyKKhai = kyKKhai;
            this.dlieuHSo = dlieuHSo;
            this.mstDLyThue = mstDLyThue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="nhanBCAnChiTuDLTResponse", WrapperNamespace="http://nhanhsothue.van.gdt.gov.vn/", IsWrapped=true)]
    public partial class nhanBCAnChiTuDLTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public nhanBCAnChiTuDLTResponse() {
        }
        
        public nhanBCAnChiTuDLTResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="nhanPLucHSoThueTuDLT", WrapperNamespace="http://nhanhsothue.van.gdt.gov.vn/", IsWrapped=true)]
    public partial class nhanPLucHSoThueTuDLTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tIN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string maTKhai;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string loaiTKhai;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string kyKKhai;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string maCQTNoiNop;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string maPLuc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string dlieuHSo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mstDLyThue;
        
        public nhanPLucHSoThueTuDLTRequest() {
        }
        
        public nhanPLucHSoThueTuDLTRequest(string tIN, string maTKhai, string loaiTKhai, string kyKKhai, string maCQTNoiNop, string maPLuc, string dlieuHSo, string mstDLyThue) {
            this.tIN = tIN;
            this.maTKhai = maTKhai;
            this.loaiTKhai = loaiTKhai;
            this.kyKKhai = kyKKhai;
            this.maCQTNoiNop = maCQTNoiNop;
            this.maPLuc = maPLuc;
            this.dlieuHSo = dlieuHSo;
            this.mstDLyThue = mstDLyThue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="nhanPLucHSoThueTuDLTResponse", WrapperNamespace="http://nhanhsothue.van.gdt.gov.vn/", IsWrapped=true)]
    public partial class nhanPLucHSoThueTuDLTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public nhanPLucHSoThueTuDLTResponse() {
        }
        
        public nhanPLucHSoThueTuDLTResponse(string @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/")]
    public partial class nhanHSoXML : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tINField;
        
        private string maTKhaiField;
        
        private string loaiTKhaiField;
        
        private string kyKKhaiField;
        
        private string dlieuHSoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string tIN {
            get {
                return this.tINField;
            }
            set {
                this.tINField = value;
                this.RaisePropertyChanged("tIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string maTKhai {
            get {
                return this.maTKhaiField;
            }
            set {
                this.maTKhaiField = value;
                this.RaisePropertyChanged("maTKhai");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string loaiTKhai {
            get {
                return this.loaiTKhaiField;
            }
            set {
                this.loaiTKhaiField = value;
                this.RaisePropertyChanged("loaiTKhai");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string kyKKhai {
            get {
                return this.kyKKhaiField;
            }
            set {
                this.kyKKhaiField = value;
                this.RaisePropertyChanged("kyKKhai");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=4)]
        public string dlieuHSo {
            get {
                return this.dlieuHSoField;
            }
            set {
                this.dlieuHSoField = value;
                this.RaisePropertyChanged("dlieuHSo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/")]
    public partial class nhanHSoXMLCoIdResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/")]
    public partial class nhanHSoXMLCoId : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tINField;
        
        private string maTKhaiField;
        
        private string loaiTKhaiField;
        
        private string kyKKhaiField;
        
        private string idHsoField;
        
        private string dlieuHSoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string tIN {
            get {
                return this.tINField;
            }
            set {
                this.tINField = value;
                this.RaisePropertyChanged("tIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string maTKhai {
            get {
                return this.maTKhaiField;
            }
            set {
                this.maTKhaiField = value;
                this.RaisePropertyChanged("maTKhai");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string loaiTKhai {
            get {
                return this.loaiTKhaiField;
            }
            set {
                this.loaiTKhaiField = value;
                this.RaisePropertyChanged("loaiTKhai");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string kyKKhai {
            get {
                return this.kyKKhaiField;
            }
            set {
                this.kyKKhaiField = value;
                this.RaisePropertyChanged("kyKKhai");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string IdHso {
            get {
                return this.idHsoField;
            }
            set {
                this.idHsoField = value;
                this.RaisePropertyChanged("IdHso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=5)]
        public string dlieuHSo {
            get {
                return this.dlieuHSoField;
            }
            set {
                this.dlieuHSoField = value;
                this.RaisePropertyChanged("dlieuHSo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/")]
    public partial class nhanHSoXMLResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nhanHSoXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=0)]
        public idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoXML nhanHSoXML;
        
        public nhanHSoXMLRequest() {
        }
        
        public nhanHSoXMLRequest(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoXML nhanHSoXML) {
            this.nhanHSoXML = nhanHSoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nhanHSoXMLResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=0)]
        public idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoXMLResponse nhanHSoXMLResponse;
        
        public nhanHSoXMLResponse1() {
        }
        
        public nhanHSoXMLResponse1(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoXMLResponse nhanHSoXMLResponse) {
            this.nhanHSoXMLResponse = nhanHSoXMLResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nhanHSoXMLCoIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=0)]
        public idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoXMLCoId nhanHSoXMLCoId;
        
        public nhanHSoXMLCoIdRequest() {
        }
        
        public nhanHSoXMLCoIdRequest(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoXMLCoId nhanHSoXMLCoId) {
            this.nhanHSoXMLCoId = nhanHSoXMLCoId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nhanHSoXMLCoIdResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/", Order=0)]
        public idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoXMLCoIdResponse nhanHSoXMLCoIdResponse;
        
        public nhanHSoXMLCoIdResponse1() {
        }
        
        public nhanHSoXMLCoIdResponse1(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoXMLCoIdResponse nhanHSoXMLCoIdResponse) {
            this.nhanHSoXMLCoIdResponse = nhanHSoXMLCoIdResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NhanHSoThueServiceChannel : idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NhanHSoThueServiceClient : System.ServiceModel.ClientBase<idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService>, idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService {
        
        public NhanHSoThueServiceClient() {
        }
        
        public NhanHSoThueServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NhanHSoThueServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NhanHSoThueServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NhanHSoThueServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        idn.Skycic.Inventory.Biz.WSNhanHSoThue.getDsachTbaoResponse idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService.getDsachTbao(idn.Skycic.Inventory.Biz.WSNhanHSoThue.getDsachTbaoRequest request) {
            return base.Channel.getDsachTbao(request);
        }
        
        public string getDsachTbao() {
            idn.Skycic.Inventory.Biz.WSNhanHSoThue.getDsachTbaoRequest inValue = new idn.Skycic.Inventory.Biz.WSNhanHSoThue.getDsachTbaoRequest();
            idn.Skycic.Inventory.Biz.WSNhanHSoThue.getDsachTbaoResponse retVal = ((idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService)(this)).getDsachTbao(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSNhanHSoThue.getDsachTbaoResponse> idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService.getDsachTbaoAsync(idn.Skycic.Inventory.Biz.WSNhanHSoThue.getDsachTbaoRequest request) {
            return base.Channel.getDsachTbaoAsync(request);
        }
        
        public System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSNhanHSoThue.getDsachTbaoResponse> getDsachTbaoAsync() {
            idn.Skycic.Inventory.Biz.WSNhanHSoThue.getDsachTbaoRequest inValue = new idn.Skycic.Inventory.Biz.WSNhanHSoThue.getDsachTbaoRequest();
            return ((idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService)(this)).getDsachTbaoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        idn.Skycic.Inventory.Biz.WSNhanHSoThue.getTbaoResponse idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService.getTbao(idn.Skycic.Inventory.Biz.WSNhanHSoThue.getTbaoRequest request) {
            return base.Channel.getTbao(request);
        }
        
        public string getTbao(string idTbao) {
            idn.Skycic.Inventory.Biz.WSNhanHSoThue.getTbaoRequest inValue = new idn.Skycic.Inventory.Biz.WSNhanHSoThue.getTbaoRequest();
            inValue.idTbao = idTbao;
            idn.Skycic.Inventory.Biz.WSNhanHSoThue.getTbaoResponse retVal = ((idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService)(this)).getTbao(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSNhanHSoThue.getTbaoResponse> idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService.getTbaoAsync(idn.Skycic.Inventory.Biz.WSNhanHSoThue.getTbaoRequest request) {
            return base.Channel.getTbaoAsync(request);
        }
        
        public System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSNhanHSoThue.getTbaoResponse> getTbaoAsync(string idTbao) {
            idn.Skycic.Inventory.Biz.WSNhanHSoThue.getTbaoRequest inValue = new idn.Skycic.Inventory.Biz.WSNhanHSoThue.getTbaoRequest();
            inValue.idTbao = idTbao;
            return ((idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService)(this)).getTbaoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        idn.Skycic.Inventory.Biz.WSNhanHSoThue.getxmlTBaoLan2Response idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService.getxmlTBaoLan2(idn.Skycic.Inventory.Biz.WSNhanHSoThue.getxmlTBaoLan2Request request) {
            return base.Channel.getxmlTBaoLan2(request);
        }
        
        public string getxmlTBaoLan2(string maTbao) {
            idn.Skycic.Inventory.Biz.WSNhanHSoThue.getxmlTBaoLan2Request inValue = new idn.Skycic.Inventory.Biz.WSNhanHSoThue.getxmlTBaoLan2Request();
            inValue.maTbao = maTbao;
            idn.Skycic.Inventory.Biz.WSNhanHSoThue.getxmlTBaoLan2Response retVal = ((idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService)(this)).getxmlTBaoLan2(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSNhanHSoThue.getxmlTBaoLan2Response> idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService.getxmlTBaoLan2Async(idn.Skycic.Inventory.Biz.WSNhanHSoThue.getxmlTBaoLan2Request request) {
            return base.Channel.getxmlTBaoLan2Async(request);
        }
        
        public System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSNhanHSoThue.getxmlTBaoLan2Response> getxmlTBaoLan2Async(string maTbao) {
            idn.Skycic.Inventory.Biz.WSNhanHSoThue.getxmlTBaoLan2Request inValue = new idn.Skycic.Inventory.Biz.WSNhanHSoThue.getxmlTBaoLan2Request();
            inValue.maTbao = maTbao;
            return ((idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService)(this)).getxmlTBaoLan2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        idn.Skycic.Inventory.Biz.WSNhanHSoThue.getTBaoLan2Response idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService.getTBaoLan2(idn.Skycic.Inventory.Biz.WSNhanHSoThue.getTBaoLan2Request request) {
            return base.Channel.getTBaoLan2(request);
        }
        
        public string getTBaoLan2() {
            idn.Skycic.Inventory.Biz.WSNhanHSoThue.getTBaoLan2Request inValue = new idn.Skycic.Inventory.Biz.WSNhanHSoThue.getTBaoLan2Request();
            idn.Skycic.Inventory.Biz.WSNhanHSoThue.getTBaoLan2Response retVal = ((idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService)(this)).getTBaoLan2(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSNhanHSoThue.getTBaoLan2Response> idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService.getTBaoLan2Async(idn.Skycic.Inventory.Biz.WSNhanHSoThue.getTBaoLan2Request request) {
            return base.Channel.getTBaoLan2Async(request);
        }
        
        public System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSNhanHSoThue.getTBaoLan2Response> getTBaoLan2Async() {
            idn.Skycic.Inventory.Biz.WSNhanHSoThue.getTBaoLan2Request inValue = new idn.Skycic.Inventory.Biz.WSNhanHSoThue.getTBaoLan2Request();
            return ((idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService)(this)).getTBaoLan2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoThueResponse idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService.nhanHSoThue(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoThueRequest request) {
            return base.Channel.nhanHSoThue(request);
        }
        
        public string nhanHSoThue(string maLoaiGDich, string dlieuHSo) {
            idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoThueRequest inValue = new idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoThueRequest();
            inValue.maLoaiGDich = maLoaiGDich;
            inValue.dlieuHSo = dlieuHSo;
            idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoThueResponse retVal = ((idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService)(this)).nhanHSoThue(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoThueResponse> idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService.nhanHSoThueAsync(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoThueRequest request) {
            return base.Channel.nhanHSoThueAsync(request);
        }
        
        public System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoThueResponse> nhanHSoThueAsync(string maLoaiGDich, string dlieuHSo) {
            idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoThueRequest inValue = new idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoThueRequest();
            inValue.maLoaiGDich = maLoaiGDich;
            inValue.dlieuHSo = dlieuHSo;
            return ((idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService)(this)).nhanHSoThueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanToKhaiThueResponse idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService.nhanToKhaiThue(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanToKhaiThueRequest request) {
            return base.Channel.nhanToKhaiThue(request);
        }
        
        public string nhanToKhaiThue(string lanNop, string dlieuHSo) {
            idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanToKhaiThueRequest inValue = new idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanToKhaiThueRequest();
            inValue.lanNop = lanNop;
            inValue.dlieuHSo = dlieuHSo;
            idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanToKhaiThueResponse retVal = ((idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService)(this)).nhanToKhaiThue(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanToKhaiThueResponse> idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService.nhanToKhaiThueAsync(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanToKhaiThueRequest request) {
            return base.Channel.nhanToKhaiThueAsync(request);
        }
        
        public System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanToKhaiThueResponse> nhanToKhaiThueAsync(string lanNop, string dlieuHSo) {
            idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanToKhaiThueRequest inValue = new idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanToKhaiThueRequest();
            inValue.lanNop = lanNop;
            inValue.dlieuHSo = dlieuHSo;
            return ((idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService)(this)).nhanToKhaiThueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanPLucHSoThueResponse idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService.nhanPLucHSoThue(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanPLucHSoThueRequest request) {
            return base.Channel.nhanPLucHSoThue(request);
        }
        
        public string nhanPLucHSoThue(string tIN, string maTKhai, string loaiTKhai, string kyKKhai, string maCQTNoiNop, string maPLuc, string dlieuHSo) {
            idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanPLucHSoThueRequest inValue = new idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanPLucHSoThueRequest();
            inValue.tIN = tIN;
            inValue.maTKhai = maTKhai;
            inValue.loaiTKhai = loaiTKhai;
            inValue.kyKKhai = kyKKhai;
            inValue.maCQTNoiNop = maCQTNoiNop;
            inValue.maPLuc = maPLuc;
            inValue.dlieuHSo = dlieuHSo;
            idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanPLucHSoThueResponse retVal = ((idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService)(this)).nhanPLucHSoThue(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanPLucHSoThueResponse> idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService.nhanPLucHSoThueAsync(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanPLucHSoThueRequest request) {
            return base.Channel.nhanPLucHSoThueAsync(request);
        }
        
        public System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanPLucHSoThueResponse> nhanPLucHSoThueAsync(string tIN, string maTKhai, string loaiTKhai, string kyKKhai, string maCQTNoiNop, string maPLuc, string dlieuHSo) {
            idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanPLucHSoThueRequest inValue = new idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanPLucHSoThueRequest();
            inValue.tIN = tIN;
            inValue.maTKhai = maTKhai;
            inValue.loaiTKhai = loaiTKhai;
            inValue.kyKKhai = kyKKhai;
            inValue.maCQTNoiNop = maCQTNoiNop;
            inValue.maPLuc = maPLuc;
            inValue.dlieuHSo = dlieuHSo;
            return ((idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService)(this)).nhanPLucHSoThueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanPLucHSoHoanThueResponse idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService.nhanPLucHSoHoanThue(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanPLucHSoHoanThueRequest request) {
            return base.Channel.nhanPLucHSoHoanThue(request);
        }
        
        public string nhanPLucHSoHoanThue(string idHso, string maGTBS, string hthanhGTBS, string ndungFile) {
            idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanPLucHSoHoanThueRequest inValue = new idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanPLucHSoHoanThueRequest();
            inValue.idHso = idHso;
            inValue.maGTBS = maGTBS;
            inValue.hthanhGTBS = hthanhGTBS;
            inValue.ndungFile = ndungFile;
            idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanPLucHSoHoanThueResponse retVal = ((idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService)(this)).nhanPLucHSoHoanThue(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanPLucHSoHoanThueResponse> idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService.nhanPLucHSoHoanThueAsync(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanPLucHSoHoanThueRequest request) {
            return base.Channel.nhanPLucHSoHoanThueAsync(request);
        }
        
        public System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanPLucHSoHoanThueResponse> nhanPLucHSoHoanThueAsync(string idHso, string maGTBS, string hthanhGTBS, string ndungFile) {
            idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanPLucHSoHoanThueRequest inValue = new idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanPLucHSoHoanThueRequest();
            inValue.idHso = idHso;
            inValue.maGTBS = maGTBS;
            inValue.hthanhGTBS = hthanhGTBS;
            inValue.ndungFile = ndungFile;
            return ((idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService)(this)).nhanPLucHSoHoanThueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoQTThueTNCNResponse idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService.nhanHSoQTThueTNCN(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoQTThueTNCNRequest request) {
            return base.Channel.nhanHSoQTThueTNCN(request);
        }
        
        public string nhanHSoQTThueTNCN(string tIN, string maTKhai, string loaiTKhai, string kyKKhai, string maCQTNoiNop, string dlieuHSo) {
            idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoQTThueTNCNRequest inValue = new idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoQTThueTNCNRequest();
            inValue.tIN = tIN;
            inValue.maTKhai = maTKhai;
            inValue.loaiTKhai = loaiTKhai;
            inValue.kyKKhai = kyKKhai;
            inValue.maCQTNoiNop = maCQTNoiNop;
            inValue.dlieuHSo = dlieuHSo;
            idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoQTThueTNCNResponse retVal = ((idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService)(this)).nhanHSoQTThueTNCN(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoQTThueTNCNResponse> idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService.nhanHSoQTThueTNCNAsync(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoQTThueTNCNRequest request) {
            return base.Channel.nhanHSoQTThueTNCNAsync(request);
        }
        
        public System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoQTThueTNCNResponse> nhanHSoQTThueTNCNAsync(string tIN, string maTKhai, string loaiTKhai, string kyKKhai, string maCQTNoiNop, string dlieuHSo) {
            idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoQTThueTNCNRequest inValue = new idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoQTThueTNCNRequest();
            inValue.tIN = tIN;
            inValue.maTKhai = maTKhai;
            inValue.loaiTKhai = loaiTKhai;
            inValue.kyKKhai = kyKKhai;
            inValue.maCQTNoiNop = maCQTNoiNop;
            inValue.dlieuHSo = dlieuHSo;
            return ((idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService)(this)).nhanHSoQTThueTNCNAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoQTThueTNCNCoIdResponse idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService.nhanHSoQTThueTNCNCoId(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoQTThueTNCNCoIdRequest request) {
            return base.Channel.nhanHSoQTThueTNCNCoId(request);
        }
        
        public string nhanHSoQTThueTNCNCoId(string tIN, string maTKhai, string loaiTKhai, string kyKKhai, string maCQTNoiNop, string IdHso, string dlieuHSo) {
            idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoQTThueTNCNCoIdRequest inValue = new idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoQTThueTNCNCoIdRequest();
            inValue.tIN = tIN;
            inValue.maTKhai = maTKhai;
            inValue.loaiTKhai = loaiTKhai;
            inValue.kyKKhai = kyKKhai;
            inValue.maCQTNoiNop = maCQTNoiNop;
            inValue.IdHso = IdHso;
            inValue.dlieuHSo = dlieuHSo;
            idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoQTThueTNCNCoIdResponse retVal = ((idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService)(this)).nhanHSoQTThueTNCNCoId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoQTThueTNCNCoIdResponse> idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService.nhanHSoQTThueTNCNCoIdAsync(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoQTThueTNCNCoIdRequest request) {
            return base.Channel.nhanHSoQTThueTNCNCoIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoQTThueTNCNCoIdResponse> nhanHSoQTThueTNCNCoIdAsync(string tIN, string maTKhai, string loaiTKhai, string kyKKhai, string maCQTNoiNop, string IdHso, string dlieuHSo) {
            idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoQTThueTNCNCoIdRequest inValue = new idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoQTThueTNCNCoIdRequest();
            inValue.tIN = tIN;
            inValue.maTKhai = maTKhai;
            inValue.loaiTKhai = loaiTKhai;
            inValue.kyKKhai = kyKKhai;
            inValue.maCQTNoiNop = maCQTNoiNop;
            inValue.IdHso = IdHso;
            inValue.dlieuHSo = dlieuHSo;
            return ((idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService)(this)).nhanHSoQTThueTNCNCoIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanBCAnChiResponse idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService.nhanBCAnChi(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanBCAnChiRequest request) {
            return base.Channel.nhanBCAnChi(request);
        }
        
        public string nhanBCAnChi(string tIN, string maTKhai, string kyKKhai, string dlieuHSo) {
            idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanBCAnChiRequest inValue = new idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanBCAnChiRequest();
            inValue.tIN = tIN;
            inValue.maTKhai = maTKhai;
            inValue.kyKKhai = kyKKhai;
            inValue.dlieuHSo = dlieuHSo;
            idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanBCAnChiResponse retVal = ((idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService)(this)).nhanBCAnChi(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanBCAnChiResponse> idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService.nhanBCAnChiAsync(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanBCAnChiRequest request) {
            return base.Channel.nhanBCAnChiAsync(request);
        }
        
        public System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanBCAnChiResponse> nhanBCAnChiAsync(string tIN, string maTKhai, string kyKKhai, string dlieuHSo) {
            idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanBCAnChiRequest inValue = new idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanBCAnChiRequest();
            inValue.tIN = tIN;
            inValue.maTKhai = maTKhai;
            inValue.kyKKhai = kyKKhai;
            inValue.dlieuHSo = dlieuHSo;
            return ((idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService)(this)).nhanBCAnChiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanBCAnChiTuDLTResponse idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService.nhanBCAnChiTuDLT(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanBCAnChiTuDLTRequest request) {
            return base.Channel.nhanBCAnChiTuDLT(request);
        }
        
        public string nhanBCAnChiTuDLT(string tIN, string maTKhai, string kyKKhai, string dlieuHSo, string mstDLyThue) {
            idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanBCAnChiTuDLTRequest inValue = new idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanBCAnChiTuDLTRequest();
            inValue.tIN = tIN;
            inValue.maTKhai = maTKhai;
            inValue.kyKKhai = kyKKhai;
            inValue.dlieuHSo = dlieuHSo;
            inValue.mstDLyThue = mstDLyThue;
            idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanBCAnChiTuDLTResponse retVal = ((idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService)(this)).nhanBCAnChiTuDLT(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanBCAnChiTuDLTResponse> idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService.nhanBCAnChiTuDLTAsync(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanBCAnChiTuDLTRequest request) {
            return base.Channel.nhanBCAnChiTuDLTAsync(request);
        }
        
        public System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanBCAnChiTuDLTResponse> nhanBCAnChiTuDLTAsync(string tIN, string maTKhai, string kyKKhai, string dlieuHSo, string mstDLyThue) {
            idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanBCAnChiTuDLTRequest inValue = new idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanBCAnChiTuDLTRequest();
            inValue.tIN = tIN;
            inValue.maTKhai = maTKhai;
            inValue.kyKKhai = kyKKhai;
            inValue.dlieuHSo = dlieuHSo;
            inValue.mstDLyThue = mstDLyThue;
            return ((idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService)(this)).nhanBCAnChiTuDLTAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanPLucHSoThueTuDLTResponse idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService.nhanPLucHSoThueTuDLT(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanPLucHSoThueTuDLTRequest request) {
            return base.Channel.nhanPLucHSoThueTuDLT(request);
        }
        
        public string nhanPLucHSoThueTuDLT(string tIN, string maTKhai, string loaiTKhai, string kyKKhai, string maCQTNoiNop, string maPLuc, string dlieuHSo, string mstDLyThue) {
            idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanPLucHSoThueTuDLTRequest inValue = new idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanPLucHSoThueTuDLTRequest();
            inValue.tIN = tIN;
            inValue.maTKhai = maTKhai;
            inValue.loaiTKhai = loaiTKhai;
            inValue.kyKKhai = kyKKhai;
            inValue.maCQTNoiNop = maCQTNoiNop;
            inValue.maPLuc = maPLuc;
            inValue.dlieuHSo = dlieuHSo;
            inValue.mstDLyThue = mstDLyThue;
            idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanPLucHSoThueTuDLTResponse retVal = ((idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService)(this)).nhanPLucHSoThueTuDLT(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanPLucHSoThueTuDLTResponse> idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService.nhanPLucHSoThueTuDLTAsync(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanPLucHSoThueTuDLTRequest request) {
            return base.Channel.nhanPLucHSoThueTuDLTAsync(request);
        }
        
        public System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanPLucHSoThueTuDLTResponse> nhanPLucHSoThueTuDLTAsync(string tIN, string maTKhai, string loaiTKhai, string kyKKhai, string maCQTNoiNop, string maPLuc, string dlieuHSo, string mstDLyThue) {
            idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanPLucHSoThueTuDLTRequest inValue = new idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanPLucHSoThueTuDLTRequest();
            inValue.tIN = tIN;
            inValue.maTKhai = maTKhai;
            inValue.loaiTKhai = loaiTKhai;
            inValue.kyKKhai = kyKKhai;
            inValue.maCQTNoiNop = maCQTNoiNop;
            inValue.maPLuc = maPLuc;
            inValue.dlieuHSo = dlieuHSo;
            inValue.mstDLyThue = mstDLyThue;
            return ((idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService)(this)).nhanPLucHSoThueTuDLTAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoXMLResponse1 idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService.nhanHSoXML(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoXMLRequest request) {
            return base.Channel.nhanHSoXML(request);
        }
        
        public idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoXMLResponse nhanHSoXML(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoXML nhanHSoXML1) {
            idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoXMLRequest inValue = new idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoXMLRequest();
            inValue.nhanHSoXML = nhanHSoXML1;
            idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoXMLResponse1 retVal = ((idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService)(this)).nhanHSoXML(inValue);
            return retVal.nhanHSoXMLResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoXMLResponse1> idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService.nhanHSoXMLAsync(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoXMLRequest request) {
            return base.Channel.nhanHSoXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoXMLResponse1> nhanHSoXMLAsync(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoXML nhanHSoXML) {
            idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoXMLRequest inValue = new idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoXMLRequest();
            inValue.nhanHSoXML = nhanHSoXML;
            return ((idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService)(this)).nhanHSoXMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoXMLCoIdResponse1 idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService.nhanHSoXMLCoId(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoXMLCoIdRequest request) {
            return base.Channel.nhanHSoXMLCoId(request);
        }
        
        public idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoXMLCoIdResponse nhanHSoXMLCoId(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoXMLCoId nhanHSoXMLCoId1) {
            idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoXMLCoIdRequest inValue = new idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoXMLCoIdRequest();
            inValue.nhanHSoXMLCoId = nhanHSoXMLCoId1;
            idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoXMLCoIdResponse1 retVal = ((idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService)(this)).nhanHSoXMLCoId(inValue);
            return retVal.nhanHSoXMLCoIdResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoXMLCoIdResponse1> idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService.nhanHSoXMLCoIdAsync(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoXMLCoIdRequest request) {
            return base.Channel.nhanHSoXMLCoIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoXMLCoIdResponse1> nhanHSoXMLCoIdAsync(idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoXMLCoId nhanHSoXMLCoId) {
            idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoXMLCoIdRequest inValue = new idn.Skycic.Inventory.Biz.WSNhanHSoThue.nhanHSoXMLCoIdRequest();
            inValue.nhanHSoXMLCoId = nhanHSoXMLCoId;
            return ((idn.Skycic.Inventory.Biz.WSNhanHSoThue.NhanHSoThueService)(this)).nhanHSoXMLCoIdAsync(inValue);
        }
    }
}
