//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ZTest01.vn.gov.gdt.daotaonhantokhai.NhanHSoThueService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://www.w3.org/ns/ws-policy' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="NhanHSoThueService", Namespace="http://nhanhsothue.van.gdt.gov.vn/")]
    public partial class NhanHSoThueService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getDsachTbaoOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTbaoOperationCompleted;
        
        private System.Threading.SendOrPostCallback getxmlTBaoLan2OperationCompleted;
        
        private System.Threading.SendOrPostCallback getTBaoLan2OperationCompleted;
        
        private System.Threading.SendOrPostCallback nhanHSoThueOperationCompleted;
        
        private System.Threading.SendOrPostCallback nhanToKhaiThueOperationCompleted;
        
        private System.Threading.SendOrPostCallback nhanPLucHSoThueOperationCompleted;
        
        private System.Threading.SendOrPostCallback nhanPLucHSoHoanThueOperationCompleted;
        
        private System.Threading.SendOrPostCallback nhanHSoQTThueTNCNOperationCompleted;
        
        private System.Threading.SendOrPostCallback nhanHSoQTThueTNCNCoIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback nhanBCAnChiOperationCompleted;
        
        private System.Threading.SendOrPostCallback nhanBCAnChiTuDLTOperationCompleted;
        
        private System.Threading.SendOrPostCallback nhanPLucHSoThueTuDLTOperationCompleted;
        
        private System.Threading.SendOrPostCallback nhanHSoXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback nhanHSoXMLCoIdOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public NhanHSoThueService() {
            this.Url = global::ZTest01.Properties.Settings.Default.ZTest01_vn_gov_gdt_daotaonhantokhai_NhanHSoThueService_NhanHSoThueService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getDsachTbaoCompletedEventHandler getDsachTbaoCompleted;
        
        /// <remarks/>
        public event getTbaoCompletedEventHandler getTbaoCompleted;
        
        /// <remarks/>
        public event getxmlTBaoLan2CompletedEventHandler getxmlTBaoLan2Completed;
        
        /// <remarks/>
        public event getTBaoLan2CompletedEventHandler getTBaoLan2Completed;
        
        /// <remarks/>
        public event nhanHSoThueCompletedEventHandler nhanHSoThueCompleted;
        
        /// <remarks/>
        public event nhanToKhaiThueCompletedEventHandler nhanToKhaiThueCompleted;
        
        /// <remarks/>
        public event nhanPLucHSoThueCompletedEventHandler nhanPLucHSoThueCompleted;
        
        /// <remarks/>
        public event nhanPLucHSoHoanThueCompletedEventHandler nhanPLucHSoHoanThueCompleted;
        
        /// <remarks/>
        public event nhanHSoQTThueTNCNCompletedEventHandler nhanHSoQTThueTNCNCompleted;
        
        /// <remarks/>
        public event nhanHSoQTThueTNCNCoIdCompletedEventHandler nhanHSoQTThueTNCNCoIdCompleted;
        
        /// <remarks/>
        public event nhanBCAnChiCompletedEventHandler nhanBCAnChiCompleted;
        
        /// <remarks/>
        public event nhanBCAnChiTuDLTCompletedEventHandler nhanBCAnChiTuDLTCompleted;
        
        /// <remarks/>
        public event nhanPLucHSoThueTuDLTCompletedEventHandler nhanPLucHSoThueTuDLTCompleted;
        
        /// <remarks/>
        public event nhanHSoXMLCompletedEventHandler nhanHSoXMLCompleted;
        
        /// <remarks/>
        public event nhanHSoXMLCoIdCompletedEventHandler nhanHSoXMLCoIdCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://nhanhsothue.van.gdt.gov.vn/", ResponseNamespace="http://nhanhsothue.van.gdt.gov.vn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string getDsachTbao() {
            object[] results = this.Invoke("getDsachTbao", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getDsachTbaoAsync() {
            this.getDsachTbaoAsync(null);
        }
        
        /// <remarks/>
        public void getDsachTbaoAsync(object userState) {
            if ((this.getDsachTbaoOperationCompleted == null)) {
                this.getDsachTbaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDsachTbaoOperationCompleted);
            }
            this.InvokeAsync("getDsachTbao", new object[0], this.getDsachTbaoOperationCompleted, userState);
        }
        
        private void OngetDsachTbaoOperationCompleted(object arg) {
            if ((this.getDsachTbaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDsachTbaoCompleted(this, new getDsachTbaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://nhanhsothue.van.gdt.gov.vn/", ResponseNamespace="http://nhanhsothue.van.gdt.gov.vn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", DataType="anyURI")]
        public string getTbao(string idTbao) {
            object[] results = this.Invoke("getTbao", new object[] {
                        idTbao});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getTbaoAsync(string idTbao) {
            this.getTbaoAsync(idTbao, null);
        }
        
        /// <remarks/>
        public void getTbaoAsync(string idTbao, object userState) {
            if ((this.getTbaoOperationCompleted == null)) {
                this.getTbaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTbaoOperationCompleted);
            }
            this.InvokeAsync("getTbao", new object[] {
                        idTbao}, this.getTbaoOperationCompleted, userState);
        }
        
        private void OngetTbaoOperationCompleted(object arg) {
            if ((this.getTbaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTbaoCompleted(this, new getTbaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://nhanhsothue.van.gdt.gov.vn/", ResponseNamespace="http://nhanhsothue.van.gdt.gov.vn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", DataType="anyURI")]
        public string getxmlTBaoLan2([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string maTbao) {
            object[] results = this.Invoke("getxmlTBaoLan2", new object[] {
                        maTbao});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getxmlTBaoLan2Async(string maTbao) {
            this.getxmlTBaoLan2Async(maTbao, null);
        }
        
        /// <remarks/>
        public void getxmlTBaoLan2Async(string maTbao, object userState) {
            if ((this.getxmlTBaoLan2OperationCompleted == null)) {
                this.getxmlTBaoLan2OperationCompleted = new System.Threading.SendOrPostCallback(this.OngetxmlTBaoLan2OperationCompleted);
            }
            this.InvokeAsync("getxmlTBaoLan2", new object[] {
                        maTbao}, this.getxmlTBaoLan2OperationCompleted, userState);
        }
        
        private void OngetxmlTBaoLan2OperationCompleted(object arg) {
            if ((this.getxmlTBaoLan2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getxmlTBaoLan2Completed(this, new getxmlTBaoLan2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://nhanhsothue.van.gdt.gov.vn/", ResponseNamespace="http://nhanhsothue.van.gdt.gov.vn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string getTBaoLan2() {
            object[] results = this.Invoke("getTBaoLan2", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getTBaoLan2Async() {
            this.getTBaoLan2Async(null);
        }
        
        /// <remarks/>
        public void getTBaoLan2Async(object userState) {
            if ((this.getTBaoLan2OperationCompleted == null)) {
                this.getTBaoLan2OperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTBaoLan2OperationCompleted);
            }
            this.InvokeAsync("getTBaoLan2", new object[0], this.getTBaoLan2OperationCompleted, userState);
        }
        
        private void OngetTBaoLan2OperationCompleted(object arg) {
            if ((this.getTBaoLan2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTBaoLan2Completed(this, new getTBaoLan2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://nhanhsothue.van.gdt.gov.vn/", ResponseNamespace="http://nhanhsothue.van.gdt.gov.vn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string nhanHSoThue([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string maLoaiGDich, [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")] string dlieuHSo) {
            object[] results = this.Invoke("nhanHSoThue", new object[] {
                        maLoaiGDich,
                        dlieuHSo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void nhanHSoThueAsync(string maLoaiGDich, string dlieuHSo) {
            this.nhanHSoThueAsync(maLoaiGDich, dlieuHSo, null);
        }
        
        /// <remarks/>
        public void nhanHSoThueAsync(string maLoaiGDich, string dlieuHSo, object userState) {
            if ((this.nhanHSoThueOperationCompleted == null)) {
                this.nhanHSoThueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnhanHSoThueOperationCompleted);
            }
            this.InvokeAsync("nhanHSoThue", new object[] {
                        maLoaiGDich,
                        dlieuHSo}, this.nhanHSoThueOperationCompleted, userState);
        }
        
        private void OnnhanHSoThueOperationCompleted(object arg) {
            if ((this.nhanHSoThueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nhanHSoThueCompleted(this, new nhanHSoThueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://nhanhsothue.van.gdt.gov.vn/", ResponseNamespace="http://nhanhsothue.van.gdt.gov.vn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string nhanToKhaiThue([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string lanNop, [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")] string dlieuHSo) {
            object[] results = this.Invoke("nhanToKhaiThue", new object[] {
                        lanNop,
                        dlieuHSo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void nhanToKhaiThueAsync(string lanNop, string dlieuHSo) {
            this.nhanToKhaiThueAsync(lanNop, dlieuHSo, null);
        }
        
        /// <remarks/>
        public void nhanToKhaiThueAsync(string lanNop, string dlieuHSo, object userState) {
            if ((this.nhanToKhaiThueOperationCompleted == null)) {
                this.nhanToKhaiThueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnhanToKhaiThueOperationCompleted);
            }
            this.InvokeAsync("nhanToKhaiThue", new object[] {
                        lanNop,
                        dlieuHSo}, this.nhanToKhaiThueOperationCompleted, userState);
        }
        
        private void OnnhanToKhaiThueOperationCompleted(object arg) {
            if ((this.nhanToKhaiThueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nhanToKhaiThueCompleted(this, new nhanToKhaiThueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://nhanhsothue.van.gdt.gov.vn/", ResponseNamespace="http://nhanhsothue.van.gdt.gov.vn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string nhanPLucHSoThue([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string tIN, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string maTKhai, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string loaiTKhai, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string kyKKhai, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string maCQTNoiNop, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string maPLuc, [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")] string dlieuHSo) {
            object[] results = this.Invoke("nhanPLucHSoThue", new object[] {
                        tIN,
                        maTKhai,
                        loaiTKhai,
                        kyKKhai,
                        maCQTNoiNop,
                        maPLuc,
                        dlieuHSo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void nhanPLucHSoThueAsync(string tIN, string maTKhai, string loaiTKhai, string kyKKhai, string maCQTNoiNop, string maPLuc, string dlieuHSo) {
            this.nhanPLucHSoThueAsync(tIN, maTKhai, loaiTKhai, kyKKhai, maCQTNoiNop, maPLuc, dlieuHSo, null);
        }
        
        /// <remarks/>
        public void nhanPLucHSoThueAsync(string tIN, string maTKhai, string loaiTKhai, string kyKKhai, string maCQTNoiNop, string maPLuc, string dlieuHSo, object userState) {
            if ((this.nhanPLucHSoThueOperationCompleted == null)) {
                this.nhanPLucHSoThueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnhanPLucHSoThueOperationCompleted);
            }
            this.InvokeAsync("nhanPLucHSoThue", new object[] {
                        tIN,
                        maTKhai,
                        loaiTKhai,
                        kyKKhai,
                        maCQTNoiNop,
                        maPLuc,
                        dlieuHSo}, this.nhanPLucHSoThueOperationCompleted, userState);
        }
        
        private void OnnhanPLucHSoThueOperationCompleted(object arg) {
            if ((this.nhanPLucHSoThueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nhanPLucHSoThueCompleted(this, new nhanPLucHSoThueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://nhanhsothue.van.gdt.gov.vn/", ResponseNamespace="http://nhanhsothue.van.gdt.gov.vn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string nhanPLucHSoHoanThue([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string idHso, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string maGTBS, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string hthanhGTBS, [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")] string ndungFile) {
            object[] results = this.Invoke("nhanPLucHSoHoanThue", new object[] {
                        idHso,
                        maGTBS,
                        hthanhGTBS,
                        ndungFile});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void nhanPLucHSoHoanThueAsync(string idHso, string maGTBS, string hthanhGTBS, string ndungFile) {
            this.nhanPLucHSoHoanThueAsync(idHso, maGTBS, hthanhGTBS, ndungFile, null);
        }
        
        /// <remarks/>
        public void nhanPLucHSoHoanThueAsync(string idHso, string maGTBS, string hthanhGTBS, string ndungFile, object userState) {
            if ((this.nhanPLucHSoHoanThueOperationCompleted == null)) {
                this.nhanPLucHSoHoanThueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnhanPLucHSoHoanThueOperationCompleted);
            }
            this.InvokeAsync("nhanPLucHSoHoanThue", new object[] {
                        idHso,
                        maGTBS,
                        hthanhGTBS,
                        ndungFile}, this.nhanPLucHSoHoanThueOperationCompleted, userState);
        }
        
        private void OnnhanPLucHSoHoanThueOperationCompleted(object arg) {
            if ((this.nhanPLucHSoHoanThueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nhanPLucHSoHoanThueCompleted(this, new nhanPLucHSoHoanThueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://nhanhsothue.van.gdt.gov.vn/", ResponseNamespace="http://nhanhsothue.van.gdt.gov.vn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string nhanHSoQTThueTNCN([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string tIN, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string maTKhai, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string loaiTKhai, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string kyKKhai, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string maCQTNoiNop, [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")] string dlieuHSo) {
            object[] results = this.Invoke("nhanHSoQTThueTNCN", new object[] {
                        tIN,
                        maTKhai,
                        loaiTKhai,
                        kyKKhai,
                        maCQTNoiNop,
                        dlieuHSo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void nhanHSoQTThueTNCNAsync(string tIN, string maTKhai, string loaiTKhai, string kyKKhai, string maCQTNoiNop, string dlieuHSo) {
            this.nhanHSoQTThueTNCNAsync(tIN, maTKhai, loaiTKhai, kyKKhai, maCQTNoiNop, dlieuHSo, null);
        }
        
        /// <remarks/>
        public void nhanHSoQTThueTNCNAsync(string tIN, string maTKhai, string loaiTKhai, string kyKKhai, string maCQTNoiNop, string dlieuHSo, object userState) {
            if ((this.nhanHSoQTThueTNCNOperationCompleted == null)) {
                this.nhanHSoQTThueTNCNOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnhanHSoQTThueTNCNOperationCompleted);
            }
            this.InvokeAsync("nhanHSoQTThueTNCN", new object[] {
                        tIN,
                        maTKhai,
                        loaiTKhai,
                        kyKKhai,
                        maCQTNoiNop,
                        dlieuHSo}, this.nhanHSoQTThueTNCNOperationCompleted, userState);
        }
        
        private void OnnhanHSoQTThueTNCNOperationCompleted(object arg) {
            if ((this.nhanHSoQTThueTNCNCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nhanHSoQTThueTNCNCompleted(this, new nhanHSoQTThueTNCNCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://nhanhsothue.van.gdt.gov.vn/", ResponseNamespace="http://nhanhsothue.van.gdt.gov.vn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string nhanHSoQTThueTNCNCoId([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string tIN, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string maTKhai, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string loaiTKhai, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string kyKKhai, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string maCQTNoiNop, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string IdHso, [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")] string dlieuHSo) {
            object[] results = this.Invoke("nhanHSoQTThueTNCNCoId", new object[] {
                        tIN,
                        maTKhai,
                        loaiTKhai,
                        kyKKhai,
                        maCQTNoiNop,
                        IdHso,
                        dlieuHSo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void nhanHSoQTThueTNCNCoIdAsync(string tIN, string maTKhai, string loaiTKhai, string kyKKhai, string maCQTNoiNop, string IdHso, string dlieuHSo) {
            this.nhanHSoQTThueTNCNCoIdAsync(tIN, maTKhai, loaiTKhai, kyKKhai, maCQTNoiNop, IdHso, dlieuHSo, null);
        }
        
        /// <remarks/>
        public void nhanHSoQTThueTNCNCoIdAsync(string tIN, string maTKhai, string loaiTKhai, string kyKKhai, string maCQTNoiNop, string IdHso, string dlieuHSo, object userState) {
            if ((this.nhanHSoQTThueTNCNCoIdOperationCompleted == null)) {
                this.nhanHSoQTThueTNCNCoIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnhanHSoQTThueTNCNCoIdOperationCompleted);
            }
            this.InvokeAsync("nhanHSoQTThueTNCNCoId", new object[] {
                        tIN,
                        maTKhai,
                        loaiTKhai,
                        kyKKhai,
                        maCQTNoiNop,
                        IdHso,
                        dlieuHSo}, this.nhanHSoQTThueTNCNCoIdOperationCompleted, userState);
        }
        
        private void OnnhanHSoQTThueTNCNCoIdOperationCompleted(object arg) {
            if ((this.nhanHSoQTThueTNCNCoIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nhanHSoQTThueTNCNCoIdCompleted(this, new nhanHSoQTThueTNCNCoIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://nhanhsothue.van.gdt.gov.vn/", ResponseNamespace="http://nhanhsothue.van.gdt.gov.vn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string nhanBCAnChi([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string tIN, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string maTKhai, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string kyKKhai, [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")] string dlieuHSo) {
            object[] results = this.Invoke("nhanBCAnChi", new object[] {
                        tIN,
                        maTKhai,
                        kyKKhai,
                        dlieuHSo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void nhanBCAnChiAsync(string tIN, string maTKhai, string kyKKhai, string dlieuHSo) {
            this.nhanBCAnChiAsync(tIN, maTKhai, kyKKhai, dlieuHSo, null);
        }
        
        /// <remarks/>
        public void nhanBCAnChiAsync(string tIN, string maTKhai, string kyKKhai, string dlieuHSo, object userState) {
            if ((this.nhanBCAnChiOperationCompleted == null)) {
                this.nhanBCAnChiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnhanBCAnChiOperationCompleted);
            }
            this.InvokeAsync("nhanBCAnChi", new object[] {
                        tIN,
                        maTKhai,
                        kyKKhai,
                        dlieuHSo}, this.nhanBCAnChiOperationCompleted, userState);
        }
        
        private void OnnhanBCAnChiOperationCompleted(object arg) {
            if ((this.nhanBCAnChiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nhanBCAnChiCompleted(this, new nhanBCAnChiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://nhanhsothue.van.gdt.gov.vn/", ResponseNamespace="http://nhanhsothue.van.gdt.gov.vn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string nhanBCAnChiTuDLT([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string tIN, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string maTKhai, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string kyKKhai, [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")] string dlieuHSo, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string mstDLyThue) {
            object[] results = this.Invoke("nhanBCAnChiTuDLT", new object[] {
                        tIN,
                        maTKhai,
                        kyKKhai,
                        dlieuHSo,
                        mstDLyThue});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void nhanBCAnChiTuDLTAsync(string tIN, string maTKhai, string kyKKhai, string dlieuHSo, string mstDLyThue) {
            this.nhanBCAnChiTuDLTAsync(tIN, maTKhai, kyKKhai, dlieuHSo, mstDLyThue, null);
        }
        
        /// <remarks/>
        public void nhanBCAnChiTuDLTAsync(string tIN, string maTKhai, string kyKKhai, string dlieuHSo, string mstDLyThue, object userState) {
            if ((this.nhanBCAnChiTuDLTOperationCompleted == null)) {
                this.nhanBCAnChiTuDLTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnhanBCAnChiTuDLTOperationCompleted);
            }
            this.InvokeAsync("nhanBCAnChiTuDLT", new object[] {
                        tIN,
                        maTKhai,
                        kyKKhai,
                        dlieuHSo,
                        mstDLyThue}, this.nhanBCAnChiTuDLTOperationCompleted, userState);
        }
        
        private void OnnhanBCAnChiTuDLTOperationCompleted(object arg) {
            if ((this.nhanBCAnChiTuDLTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nhanBCAnChiTuDLTCompleted(this, new nhanBCAnChiTuDLTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://nhanhsothue.van.gdt.gov.vn/", ResponseNamespace="http://nhanhsothue.van.gdt.gov.vn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string nhanPLucHSoThueTuDLT([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string tIN, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string maTKhai, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string loaiTKhai, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string kyKKhai, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string maCQTNoiNop, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string maPLuc, [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")] string dlieuHSo, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string mstDLyThue) {
            object[] results = this.Invoke("nhanPLucHSoThueTuDLT", new object[] {
                        tIN,
                        maTKhai,
                        loaiTKhai,
                        kyKKhai,
                        maCQTNoiNop,
                        maPLuc,
                        dlieuHSo,
                        mstDLyThue});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void nhanPLucHSoThueTuDLTAsync(string tIN, string maTKhai, string loaiTKhai, string kyKKhai, string maCQTNoiNop, string maPLuc, string dlieuHSo, string mstDLyThue) {
            this.nhanPLucHSoThueTuDLTAsync(tIN, maTKhai, loaiTKhai, kyKKhai, maCQTNoiNop, maPLuc, dlieuHSo, mstDLyThue, null);
        }
        
        /// <remarks/>
        public void nhanPLucHSoThueTuDLTAsync(string tIN, string maTKhai, string loaiTKhai, string kyKKhai, string maCQTNoiNop, string maPLuc, string dlieuHSo, string mstDLyThue, object userState) {
            if ((this.nhanPLucHSoThueTuDLTOperationCompleted == null)) {
                this.nhanPLucHSoThueTuDLTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnhanPLucHSoThueTuDLTOperationCompleted);
            }
            this.InvokeAsync("nhanPLucHSoThueTuDLT", new object[] {
                        tIN,
                        maTKhai,
                        loaiTKhai,
                        kyKKhai,
                        maCQTNoiNop,
                        maPLuc,
                        dlieuHSo,
                        mstDLyThue}, this.nhanPLucHSoThueTuDLTOperationCompleted, userState);
        }
        
        private void OnnhanPLucHSoThueTuDLTOperationCompleted(object arg) {
            if ((this.nhanPLucHSoThueTuDLTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nhanPLucHSoThueTuDLTCompleted(this, new nhanPLucHSoThueTuDLTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("nhanHSoXMLResponse", Namespace="http://nhanhsothue.van.gdt.gov.vn/")]
        public nhanHSoXMLResponse nhanHSoXML([System.Xml.Serialization.XmlElementAttribute("nhanHSoXML", Namespace="http://nhanhsothue.van.gdt.gov.vn/")] nhanHSoXML nhanHSoXML1) {
            object[] results = this.Invoke("nhanHSoXML", new object[] {
                        nhanHSoXML1});
            return ((nhanHSoXMLResponse)(results[0]));
        }
        
        /// <remarks/>
        public void nhanHSoXMLAsync(nhanHSoXML nhanHSoXML1) {
            this.nhanHSoXMLAsync(nhanHSoXML1, null);
        }
        
        /// <remarks/>
        public void nhanHSoXMLAsync(nhanHSoXML nhanHSoXML1, object userState) {
            if ((this.nhanHSoXMLOperationCompleted == null)) {
                this.nhanHSoXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnhanHSoXMLOperationCompleted);
            }
            this.InvokeAsync("nhanHSoXML", new object[] {
                        nhanHSoXML1}, this.nhanHSoXMLOperationCompleted, userState);
        }
        
        private void OnnhanHSoXMLOperationCompleted(object arg) {
            if ((this.nhanHSoXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nhanHSoXMLCompleted(this, new nhanHSoXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("nhanHSoXMLCoIdResponse", Namespace="http://nhanhsothue.van.gdt.gov.vn/")]
        public nhanHSoXMLCoIdResponse nhanHSoXMLCoId([System.Xml.Serialization.XmlElementAttribute("nhanHSoXMLCoId", Namespace="http://nhanhsothue.van.gdt.gov.vn/")] nhanHSoXMLCoId nhanHSoXMLCoId1) {
            object[] results = this.Invoke("nhanHSoXMLCoId", new object[] {
                        nhanHSoXMLCoId1});
            return ((nhanHSoXMLCoIdResponse)(results[0]));
        }
        
        /// <remarks/>
        public void nhanHSoXMLCoIdAsync(nhanHSoXMLCoId nhanHSoXMLCoId1) {
            this.nhanHSoXMLCoIdAsync(nhanHSoXMLCoId1, null);
        }
        
        /// <remarks/>
        public void nhanHSoXMLCoIdAsync(nhanHSoXMLCoId nhanHSoXMLCoId1, object userState) {
            if ((this.nhanHSoXMLCoIdOperationCompleted == null)) {
                this.nhanHSoXMLCoIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnhanHSoXMLCoIdOperationCompleted);
            }
            this.InvokeAsync("nhanHSoXMLCoId", new object[] {
                        nhanHSoXMLCoId1}, this.nhanHSoXMLCoIdOperationCompleted, userState);
        }
        
        private void OnnhanHSoXMLCoIdOperationCompleted(object arg) {
            if ((this.nhanHSoXMLCoIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nhanHSoXMLCoIdCompleted(this, new nhanHSoXMLCoIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/")]
    public partial class nhanHSoXML {
        
        private string tINField;
        
        private string maTKhaiField;
        
        private string loaiTKhaiField;
        
        private string kyKKhaiField;
        
        private string dlieuHSoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tIN {
            get {
                return this.tINField;
            }
            set {
                this.tINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string maTKhai {
            get {
                return this.maTKhaiField;
            }
            set {
                this.maTKhaiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string loaiTKhai {
            get {
                return this.loaiTKhaiField;
            }
            set {
                this.loaiTKhaiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string kyKKhai {
            get {
                return this.kyKKhaiField;
            }
            set {
                this.kyKKhaiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string dlieuHSo {
            get {
                return this.dlieuHSoField;
            }
            set {
                this.dlieuHSoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/")]
    public partial class nhanHSoXMLCoIdResponse {
        
        private string returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/")]
    public partial class nhanHSoXMLCoId {
        
        private string tINField;
        
        private string maTKhaiField;
        
        private string loaiTKhaiField;
        
        private string kyKKhaiField;
        
        private string idHsoField;
        
        private string dlieuHSoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tIN {
            get {
                return this.tINField;
            }
            set {
                this.tINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string maTKhai {
            get {
                return this.maTKhaiField;
            }
            set {
                this.maTKhaiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string loaiTKhai {
            get {
                return this.loaiTKhaiField;
            }
            set {
                this.loaiTKhaiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string kyKKhai {
            get {
                return this.kyKKhaiField;
            }
            set {
                this.kyKKhaiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IdHso {
            get {
                return this.idHsoField;
            }
            set {
                this.idHsoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string dlieuHSo {
            get {
                return this.dlieuHSoField;
            }
            set {
                this.dlieuHSoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nhanhsothue.van.gdt.gov.vn/")]
    public partial class nhanHSoXMLResponse {
        
        private string returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void getDsachTbaoCompletedEventHandler(object sender, getDsachTbaoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDsachTbaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDsachTbaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void getTbaoCompletedEventHandler(object sender, getTbaoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTbaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTbaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void getxmlTBaoLan2CompletedEventHandler(object sender, getxmlTBaoLan2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getxmlTBaoLan2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getxmlTBaoLan2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void getTBaoLan2CompletedEventHandler(object sender, getTBaoLan2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTBaoLan2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTBaoLan2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void nhanHSoThueCompletedEventHandler(object sender, nhanHSoThueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nhanHSoThueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal nhanHSoThueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void nhanToKhaiThueCompletedEventHandler(object sender, nhanToKhaiThueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nhanToKhaiThueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal nhanToKhaiThueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void nhanPLucHSoThueCompletedEventHandler(object sender, nhanPLucHSoThueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nhanPLucHSoThueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal nhanPLucHSoThueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void nhanPLucHSoHoanThueCompletedEventHandler(object sender, nhanPLucHSoHoanThueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nhanPLucHSoHoanThueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal nhanPLucHSoHoanThueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void nhanHSoQTThueTNCNCompletedEventHandler(object sender, nhanHSoQTThueTNCNCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nhanHSoQTThueTNCNCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal nhanHSoQTThueTNCNCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void nhanHSoQTThueTNCNCoIdCompletedEventHandler(object sender, nhanHSoQTThueTNCNCoIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nhanHSoQTThueTNCNCoIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal nhanHSoQTThueTNCNCoIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void nhanBCAnChiCompletedEventHandler(object sender, nhanBCAnChiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nhanBCAnChiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal nhanBCAnChiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void nhanBCAnChiTuDLTCompletedEventHandler(object sender, nhanBCAnChiTuDLTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nhanBCAnChiTuDLTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal nhanBCAnChiTuDLTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void nhanPLucHSoThueTuDLTCompletedEventHandler(object sender, nhanPLucHSoThueTuDLTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nhanPLucHSoThueTuDLTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal nhanPLucHSoThueTuDLTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void nhanHSoXMLCompletedEventHandler(object sender, nhanHSoXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nhanHSoXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal nhanHSoXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public nhanHSoXMLResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((nhanHSoXMLResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void nhanHSoXMLCoIdCompletedEventHandler(object sender, nhanHSoXMLCoIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nhanHSoXMLCoIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal nhanHSoXMLCoIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public nhanHSoXMLCoIdResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((nhanHSoXMLCoIdResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591