using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace idn.Skycic.Inventory.Constants
{
    public class Error
    {
        public static string GetErrorMessage(string strkey)
        {
            var error = "";
            error = GetErrDict(strkey);
            return error;
        }

        public static string GetErrDict(string errCode)
        {
            var errContent = "";
            var errDict = new Dictionary<string, string>()
            {
                #region[""]
                {"ErridnInventory.Mst_Supplier_CheckDB_SupCodeNotFound","Không tìm thấy mã nhà cung cấp!"},
{"ErridnInventory.Mst_Supplier_CheckDB_SupCodeExist","Mã nhà cung cấp đã tồn tại!"},
{"ErridnInventory.Mst_Supplier_CheckDB_FlagActiveNotMatched","Trạng thái hoạt động của nhà cung cấp không hợp lệ!"},
{"ErridnInventory.Mst_Supplier_Get","Không lấy được thông tin nhà cung cấp!"},
{"ErridnInventory.WAS_Mst_Supplier_Get","Không lấy được thông tin nhà cung cấp!"},
{"ErridnInventory.WAS_Mst_Supplier_Create","Tạo mới nhà cung cấp không thành công!"},
{"ErridnInventory.Mst_Supplier_Create","Tạo mới nhà cung cấp không thành công!"},
{"ErridnInventory.Mst_Supplier_Create_InvalidSupCode","Mã nhà cung cấp không hợp lệ!"},
{"ErridnInventory.Mst_Supplier_Create_InvalidSupType","Loại nhà cung cấp không hợp lệ!"},
{"ErridnInventory.Mst_Supplier_Create_InvalidSupName","Tên nhà cung cấp không hợp lệ!"},
{"ErridnInventory.WAS_Mst_Supplier_Update","Cập nhật thông tin nhà cung cấp không thành công!"},
{"ErridnInventory.Mst_Supplier_Update","Cập nhật thông tin nhà cung cấp không thành công!"},
{"ErridnInventory.Mst_Supplier_Update_InvalidSupType","Loại nhà cung cấp không hợp lệ!"},
{"ErridnInventory.Mst_Supplier_Update_InvalidSupName","Tên nhà cung cấp không hợp lệ!"},
{"ErridnInventory.WAS_Mst_Supplier_Delete","Xóa nhà cung cấp không thành công!"},
{"ErridnInventory.Mst_Supplier_Delete","Xóa nhà cung cấp không thành công!"},
{"ErridnInventory.Mst_MoveOrdType_CheckDB_MoveOrdTypeNotFound","Không tìm thấy loại điều chuyển!"},
{"ErridnInventory.Mst_MoveOrdType_CheckDB_MoveOrdTypeExist","Loại điều chuyển đã tồn tại!"},
{"ErridnInventory.Mst_MoveOrdType_CheckDB_FlagActiveNotMatched","Trạng thái hoạt động của loại điều chuyển không hợp lệ!"},
{"ErridnInventory.Mst_MoveOrdType_Get","Không lấy được thông tin loại điều chuyển!"},
{"ErridnInventory.WAS_Mst_MoveOrdType_Get","Không lấy được thông tin loại điều chuyển!"},
{"ErridnInventory.Mst_CustomerType_CheckDB_CtmTypeNotFound","Không tìm thấy loại khách hàng!"},
{"ErridnInventory.Mst_CustomerType_CheckDB_CtmTypeExist","Loại khách hàng đã tồn tại!"},
{"ErridnInventory.Mst_CustomerType_CheckDB_FlagActiveNotMatched","Trạng thái hoạt động của loại khách hàng không phù hợp!"},
{"ErridnInventory.Mst_CustomerType_Get","Không lấy được thông tin loại khách hàng!"},
{"ErridnInventory.Mst_Customer_CheckDB_CustomerNotFound","Không tìm thấy khách hàng!"},
{"ErridnInventory.Mst_Customer_CheckDB_CustomerExist","Khách hàng đã tồn tại!"},
{"ErridnInventory.Mst_Customer_CheckDB_FlagActiveNotMatched","Trạng thái hoạt động của khách hàng không phù hợp!"},
{"ErridnInventory.Mst_Customer_CheckBiz_InvalidCtmType","Loại khách hàng không hợp lệ!"},
{"ErridnInventory.Mst_Customer_Get","Không lấy được thông tin khách hàng!"},
{"ErridnInventory.Mst_Customer_Create","Tạo khách hàng không thành công!"},
{"ErridnInventory.Mst_Customer_Create_InvalidCtmCode","Mã khách hàng không hợp lệ!"},
{"ErridnInventory.Mst_Customer_Create_InvalidCtmType","Loại khách hàng không hợp lệ!"},
{"ErridnInventory.Mst_Customer_Create_InvalidCtmName","Tên khách hàng không hợp lệ!"},
{"ErridnInventory.Mst_Customer_Update","Cập nhật khách hàng không thành công!"},
{"ErridnInventory.Mst_Customer_Update_InvalidCtmName","Tên khách hàng không hợp lệ!"},
{"ErridnInventory.Mst_Customer_Delete","Xóa khách hàng không thành công!"},
{"ErridnInventory.Mst_ProductGroup_CheckDB_ProductGroupNotFound","Không tìm thấy nhóm hàng hóa!"},
{"ErridnInventory.Mst_ProductGroup_CheckDB_ProductGroupExist","Nhóm hàng hóa đã tồn tại!"},
{"ErridnInventory.Mst_ProductGroup_CheckDB_FlagActiveNotMatched","Trạng thái hoạt động của nhóm hàng hóa không hợp lệ!"},
{"ErridnInventory.Mst_ProductGroup_Get","Không lấy được thông tin nhóm hàng!"},
{"ErridnInventory.WAS_Mst_ProductGroup_Get","Không lấy được thông tin nhóm hàng!"},
{"ErridnInventory.WAS_Mst_ProductGroup_Create","Tạo mới nhóm hàng không thành công!"},
{"ErridnInventory.Mst_ProductGroup_Create","Tạo mới nhóm hàng không thành công!"},
{"ErridnInventory.Mst_ProductGroup_Create_InvalidProductGrpCode","Mã nhóm hàng hóa không hợp lệ!"},
{"ErridnInventory.Mst_ProductGroup_Create_InvalidProductGrpName","Tên nhóm hàng hóa không hợp lệ!"},
{"ErridnInventory.Mst_ProductGroup_Update","Cập nhật nhóm hàng hóa không thành công!"},
{"ErridnInventory.WAS_Mst_ProductGroup_Update","Cập nhật nhóm hàng hóa không thành công!"},
{"ErridnInventory.Mst_ProductGroup_UpdateX","Cập nhật nhóm hàng hóa không thành công!"},
{"ErridnInventory.Mst_ProductGroup_UpdateX_InvalidProductGrpName","Tên nhóm hàng hóa không hợp lệ!"},
{"ErridnInventory.WAS_Mst_ProductGroup_Delete","Xóa nhóm hàng hóa không thành công!"},
{"ErridnInventory.Mst_ProductGroup_Delete","Xóa nhóm hàng hóa không thành công!"},
{"ErridnInventory.Mst_ProductGroup_SaveX_Input_ProductGroupTblNotFound","Không tìm thấy thông tin nhóm hàng hóa!"},
{"ErridnInventory.Mst_ProductGroup_SaveX_Input_ProductGroupTblInvalid","Thông tin nhóm hàng hóa không hợp lệ!"},
{"ErridnInventory.Mst_ProductGroup_Save","Lưu nhóm hàng hóa không thành công!"},
{"ErridnInventory.WAS_Mst_ProductGroup_Save","Lưu nhóm hàng hóa không thành công!"},
{"ErridnInventory.Prd_DynamicField_CheckDB_DynamicFieldNotFound","Không tìm thấy trường động!"},
{"ErridnInventory.Prd_DynamicField_CheckDB_DynamicFieldExist","Trường động đã tồn tại!"},
{"ErridnInventory.Prd_DynamicField_CheckDB_FlagActiveNotMatched","Trạng thái hoạt động của trường động không phù hợp!"},
{"ErridnInventory.Prd_DynamicField_Get","Không lấy được không tin trường động!"},
{"ErridnInventory.WAS_Prd_DynamicField_Get","Không lấy được không tin trường động!"},
{"ErridnInventory.WAS_Prd_DynamicField_Create","Tạo mới trường động không thành công!"},
{"ErridnInventory.Prd_DynamicField_Create","Tạo mới trường động không thành công!"},
{"ErridnInventory.Prd_DynamicField_Create_InvalidOrgID","Mã chi nhánh không hợp lệ!"},
{"ErridnInventory.Prd_DynamicField_Create_InvalidDynamicFieldName","Tên trường động không hợp lệ!"},
{"ErridnInventory.Prd_DynamicField_Update","Cập nhật trường động không thành công!"},
{"ErridnInventory.WAS_Prd_DynamicField_Update","Cập nhật trường động không thành công!"},
{"ErridnInventory.Prd_DynamicField_UpdateX","Cập nhật trường động không thành công!"},
{"ErridnInventory.Prd_DynamicField_UpdateX_InvalidDynamicFieldName","Tên trường động không hợp lệ!"},
{"ErridnInventory.WAS_Prd_DynamicField_Delete","Xóa trường động không thành công!"},
{"ErridnInventory.Prd_DynamicField_Delete","Xóa trường động không thành công!"},
{"ErridnInventory.Prd_DynamicField_SaveX_Input_DynamicFieldTblNotFound","Không tìm thấy thông tin trường động!"},
{"ErridnInventory.Prd_DynamicField_SaveX_Input_DynamicFieldTblInvalid","Thông tin trường động không hợp lệ!"},
{"ErridnInventory.Prd_DynamicField_Save","Lưu trường động không thành công!"},
{"ErridnInventory.WAS_Prd_DynamicField_Save","Lưu trường động không thành công!"},
{"ErridnInventory.WAS_Mst_Attribute_Save","Lưu thuộc tính không thành công!"},
{"ErridnInventory.Mst_Attribute_Save","Lưu thuộc tính không thành công!"},
{"ErridnInventory.Mst_Attribute_SaveX_Input_AttributeTblNotFound","Không tìm thấy thông tin thuộc tính!"},
{"ErridnInventory.Mst_Attribute_SaveX_Input_AttributeTblInvalid","Thông tin thuộc tính không hợp lệ!"},
{"ErridnDMS.WAS_Mst_Area_Save","Lưu khu vực không thành công!"},
{"ErridnDMS.Mst_Area_Save","Lưu khu vực không thành công!"},
{"ErridnDMS.Mst_Area_SaveX_Input_BrandTblNotFound","Không tìm thấy thông tin nhãn hiệu!"},
{"ErridnDMS.Mst_Area_SaveX_Input_BrandTblInvalid","Thông tin nhãn hiệu không hợp lệ!"},
{"ErridnDMS.Mst_Area_CheckDB_AreaNotFound","Không tìm thấy khu vực!"},
{"ErridnDMS.Mst_CustomerInCustomerGroup_CheckDB_AreaNotFound","Không tìm thấy khu vực!"},
{"ErridnDMS.Mst_CustomerInCustomerGroup_CheckDB_AreaExist","Khu vực đã tồn tại!"},
{"ErridnDMS.Mst_CustomerInCustomerGroup_CheckDB_FlagActiveNotMatched","Trạng thái hoạt động của khách hàng trong nhóm khách hàng không phù hợp!"},
{"ErridnDMS.Mst_CustomerInCustomerGroup_Get","Không lấy được thông tin khách hàng trong nhóm khách hàng!"},
{"ErridnDMS.Mst_CustomerInCustomerGroup_SaveX_Input_BrandTblNotFound","Không tìm thấy thông tin nhãn hiệu!"},
{"ErridnDMS.Mst_CustomerInCustomerGroup_SaveX_Input_BrandTblInvalid","Thông tin nhãn hiệu không hợp lệ!"},
{"ErridnDMS.Mst_CustomerInCustomerGroup_Save","Lưu khách hàng trong nhóm khách hàng không thành công!"},
{"ErridnDMS.WAS_Mst_CustomerInCustomerGroup_Save","Lưu khách hàng trong nhóm khách hàng không thành công!"},
{"ErridnDMS.Mst_CustomerType_Save","Lưu loại khách hàng không thành công!"},
{"ErridnDMS.Mst_CustomerType_Save_Input_Mst_CustomerTypeTblNotFound","Không tìm thấy thông tin loại khách hàng!"},
{"ErridnDMS.Mst_CustomerType_Update_Input_Mst_CustomerTypeImagesTblNotFound","Không tìm thấy thông tin hình ảnh loại khách hàng!"},
{"ErridnDMS.WAS_Mst_CustomerType_Save","Lưu loại khách hàng không thành công!"},
{"ErridnDMS.Mst_CustomerGroup_Save","Lưu loại khách hàng không thành công!"},
{"ErridnDMS.Mst_CustomerGroup_Save_Input_Mst_CustomerGroupTblNotFound","Không tìm thấy thông tin nhóm khách hàng!"},
{"ErridnDMS.Mst_CustomerGroup_Update_Input_Mst_CustomerGroupImagesTblNotFound","Không tìm thấy thông tin hình ảnh nhóm khách hàng!"},
{"ErridnDMS.WAS_Mst_CustomerGroup_Save","Lưu nhóm khách hàng không thành công!"},
{"ErridnDMS.Mst_CustomerSource_Save","Lưu nguồn khách hàng không thành công!"},
{"ErridnDMS.Mst_CustomerSource_Save_Input_Mst_CustomerSourceTblNotFound","Không tìm thấy thông tin nguồn khách hàng!"},
{"ErridnDMS.Mst_CustomerSource_Update_Input_Mst_CustomerSourceImagesTblNotFound","Không tìm thấy thông tin hình ảnh nguồn khách hàng!"},
{"ErridnDMS.WAS_Mst_CustomerSource_Save","Lưu nguồn khách hàng không thành công!"},
{"ErridnDMS.Customer_DynamicField_SaveX_Input_TblNotFound","Không tìm thấy thông tin!"},
{"ErridnDMS.Customer_DynamicField_SaveX_Input_TblInvalid","Thông tin không hợp lệ!"},
{"ErridnDMS.Customer_DynamicField_Save","Lưu không thành công!"},
{"ErridnDMS.WAS_Customer_DynamicField_Save","Lưu không thành công!"},
{"ErridnDMS.Mst_Customer_Save","Lưu khách hàng không thành công!"},
{"ErridnDMS.Mst_Customer_Save_Input_Mst_CustomerTblNotFound","Không tìm thấy thông tin khách hàng!"},
{"ErridnDMS.WAS_Mst_Customer_Save","Lưu khách hàng không thành công!"},
{"ErridnInventory.Mst_InventoryType_CheckDB_InvTypeNotFound","Không tìm thấy loại kho!"},
{"ErridnInventory.Mst_InventoryType_CheckDB_InvTypeExist","Loại kho đã tồn tại!"},
{"ErridnInventory.Mst_InventoryType_CheckDB_FlagActiveNotMatched","Trạng thái hoạt động của loại kho không hợp lệ!"},
{"ErridnInventory.Mst_InventoryType_Get","Không lấy được thông tin loại kho!"},
{"ErridnInventory.WAS_Mst_InventoryType_Get","Không lấy được thông tin loại kho!"},
{"ErridnInventory.Mst_InventoryType_CreateX","Tạo mới loại kho không thành công!"},
{"ErridnInventory.Mst_InventoryType_CreateX_InvalidOrgID","Mã chi nhánh không hợp lệ!"},
{"ErridnInventory.Mst_InventoryType_CreateX_InvalidInvType","Loại kho không hợp lệ!"},
{"ErridnInventory.Mst_InventoryType_CreateX_InvalidInvTypeName","Tên loại kho không hợp lệ!"},
{"ErridnInventory.WAS_Mst_InventoryType_Create","Tạo mới loại kho không thành công!"},
{"ErridnInventory.Mst_InventoryType_Create","Tạo mới loại kho không thành công!"},
{"ErridnInventory.Mst_InventoryType_UpdateX","Cập nhật loại kho không thành công!"},
{"ErridnInventory.Mst_InventoryType_Update","Cập nhật loại kho không thành công!"},
{"ErridnInventory.WAS_Mst_InventoryType_Update","Cập nhật loại kho không thành công!"},
{"ErridnInventory.Mst_InventoryType_UpdateX_InvalidInvTypeName","Tên loại kho không hợp lệ!"},
{"ErridnInventory.Mst_InventoryType_DeleteX","Xóa loại kho không thành công!"},
{"ErridnInventory.Mst_InventoryType_Delete","Xóa loại kho không thành công!"},
{"ErridnInventory.WAS_Mst_InventoryType_Delete","Xóa loại kho không thành công!"},
{"ErridnInventory.Mst_InventoryLevelType_CheckDB_InvLevelTypeNotFound","Không tìm thấy cấp kho!"},
{"ErridnInventory.Mst_InventoryLevelType_CheckDB_InvLevelTypeExist","Cấp kho đã tồn tại!"},
{"ErridnInventory.Mst_InventoryLevelType_CheckDB_FlagActiveNotMatched","Trạng thái hoạt động của cấp kho không hợp lệ!"},
{"ErridnInventory.Mst_InventoryLevelType_Get","Không lấy được thông tin cấp kho!"},
{"ErridnInventory.WAS_Mst_InventoryLevelType_Get","Không lấy được thông tin cấp kho!"},
{"ErridnInventory.Mst_InventoryLevelType_CreateX","Tạo mới cấp kho không thành công!"},
{"ErridnInventory.Mst_InventoryLevelType_CreateX_InvalidOrgID","Mã chi nhánh không hợp lệ!"},
{"ErridnInventory.Mst_InventoryLevelType_CreateX_InvalidInvLevelType","Cấp kho không hợp lệ!"},
{"ErridnInventory.Mst_InventoryLevelType_CreateX_InvalidInvLevelTypeName","Tên cấp kho không hợp lệ!"},
{"ErridnInventory.WAS_Mst_InventoryLevelType_Create","Tạo mới cấp kho không thành công!"},
{"ErridnInventory.Mst_InventoryLevelType_Create","Tạo mới cấp kho không thành công!"},
{"ErridnInventory.Mst_InventoryLevelType_UpdateX","Cập nhật cấp kho không thành công!"},
{"ErridnInventory.Mst_InventoryLevelType_Update","Cập nhật cấp kho không thành công!"},
{"ErridnInventory.WAS_Mst_InventoryLevelType_Update","Cập nhật cấp kho không thành công!"},
{"ErridnInventory.Mst_InventoryLevelType_UpdateX_InvalidInvLevelTypeName","Tên cấp kho không hợp lệ!"},
{"ErridnInventory.Mst_InventoryLevelType_DeleteX","Xóa cấp kho không thành công!"},
{"ErridnInventory.Mst_InventoryLevelType_Delete","Xóa cấp kho không thành công!"},
{"ErridnInventory.WAS_Mst_InventoryLevelType_Delete","Xóa cấp kho không thành công!"},
{"ErridnInventory.Mst_InvInType_CheckDB_InvInTypeNotFound","Không tìm thấy loại nhập kho!"},
{"ErridnInventory.Mst_InvInType_CheckDB_InvInTypeExist","Loại nhập kho đã tồn tại!"},
{"ErridnInventory.Mst_InvInType_CheckDB_FlagActiveNotMatched","Trạng thái hoạt động của loại nhập kho không phù hợp!"},
{"ErridnInventory.Mst_InvInType_CheckDB_FlagStatisticNotMatched",""},
{"ErridnInventory.Mst_InvInType_Get","Không lấy được thông tin loại nhập kho!"},
{"ErridnInventory.WAS_Mst_InvInType_Get","Không lấy được thông tin loại nhập kho!"},
{"ErridnInventory.Mst_InvInType_CreateX","Tạo mới loại nhập kho không thành công!"},
{"ErridnInventory.Mst_InvInType_CreateX_InvalidOrgID","Mã chi nhánh không hợp lệ!"},
{"ErridnInventory.Mst_InvInType_CreateX_InvalidInvInType","Loại nhập kho không hợp lệ!"},
{"ErridnInventory.Mst_InvInType_CreateX_InvalidInvInTypeName","Tên loại nhập kho không hợp lệ!"},
{"ErridnInventory.WAS_Mst_InvInType_Create","Tạo mới loại nhập kho không thành công!"},
{"ErridnInventory.Mst_InvInType_Create","Tạo mới loại nhập kho không thành công!"},
{"ErridnInventory.Mst_InvInType_UpdateX","Cập nhật loại nhập kho không thành công!"},
{"ErridnInventory.Mst_InvInType_Update","Cập nhật loại nhập kho không thành công!"},
{"ErridnInventory.WAS_Mst_InvInType_Update","Cập nhật loại nhập kho không thành công!"},
{"ErridnInventory.Mst_InvInType_UpdateX_InvalidInvInTypeName","Tên loại nhập kho không hợp lệ!"},
{"ErridnInventory.Mst_InvInType_DeleteX","Xóa loại nhập kho không thành công!"},
{"ErridnInventory.Mst_InvInType_Delete","Xóa loại nhập kho không thành công!"},
{"ErridnInventory.WAS_Mst_InvInType_Delete","Xóa loại nhập kho không thành công!"},
{"ErridnInventory.Mst_InvInType_Delete_InvInTypeNotAllowDelete","Không được phép xóa loại nhập kho!"},
{"ErridnInventory.Mst_InvOutType_CheckDB_InvOutTypeNotFound","Không tìm thấy loại xuất kho!"},
{"ErridnInventory.Mst_InvOutType_CheckDB_InvOutTypeExist","Loại xuất kho đã tồn tại!"},
{"ErridnInventory.Mst_InvOutType_CheckDB_FlagActiveNotMatched","Trạng thái hoạt động của loại xuất kho không phù hợp!"},
{"ErridnInventory.Mst_InvOutType_CheckDB_FlagStatisticNotMatched",""},
{"ErridnInventory.Mst_InvOutType_Get","Không lấy được thông tin loại xuất kho!"},
{"ErridnInventory.WAS_Mst_InvOutType_Get","Không lấy được thông tin loại xuất kho!"},
{"ErridnInventory.OS_Mst_InvOutType_Get","Không lấy được thông tin loại xuất kho!"},
{"ErridnInventory.WAS_OS_Mst_InvOutType_Get","Không lấy được thông tin loại xuất kho!"},
{"ErridnInventory.Mst_InvOutType_CreateX","Tạo mới loại xuất kho không thành công!"},
{"ErridnInventory.Mst_InvOutType_CreateX_InvalidOrgID","Mã chi nhánh không hợp lệ!"},
{"ErridnInventory.Mst_InvOutType_CreateX_InvalidInvOutType","Loại xuất kho không hợp lệ!"},
{"ErridnInventory.Mst_InvOutType_CreateX_InvalidInvOutTypeName","Tên loại xuất kho không hợp lệ!"},
{"ErridnInventory.WAS_Mst_InvOutType_Create","Tạo mới loại xuất kho không thành công!"},
{"ErridnInventory.Mst_InvOutType_Create","Tạo mới loại xuất kho không thành công!"},
{"ErridnInventory.Mst_InvOutType_UpdateX","Cập nhật loại xuất kho không thành công!"},
{"ErridnInventory.Mst_InvOutType_Update","Cập nhật loại xuất kho không thành công!"},
{"ErridnInventory.WAS_Mst_InvOutType_Update","Cập nhật loại xuất kho không thành công!"},
{"ErridnInventory.Mst_InvOutType_UpdateX_InvalidInvOutTypeName","Tên loại xuất kho không hợp lệ!"},
{"ErridnInventory.Mst_InvOutType_DeleteX","Xóa loại xuất kho không thành công!"},
{"ErridnInventory.Mst_InvOutType_Delete","Xóa loại xuất kho không thành công!"},
{"ErridnInventory.WAS_Mst_InvOutType_Delete","Xóa loại xuất kho không thành công!"},
{"ErridnInventory.Mst_InvOutType_Delete_InvOutTypeNotAllowDelete","Không được phép xóa loại xuất kho!"},
{"ErridnInventory.Mst_Inventory_CheckDB_InventoryNotFound","Không tìm thấy kho!"},
{"ErridnInventory.Mst_Inventory_CheckDB_InventoryExist","Kho đã tồn tại!"},
{"ErridnInventory.Mst_Inventory_CheckDB_InventoryStatusNotMatched","Trạng thái kho không phù hợp!"},
{"ErridnInventory.Mst_Inventory_CheckListDB_MstInventoryTbl_InventoryNotFound","Không tìm thấy kho!"},
{"ErridnInventory.Mst_Inventory_CheckListDB_MstInventoryTbl_InventoryExist","Kho đã tồn tại!"},
{"ErridnInventory.Mst_Inventory_CheckListDB_MstInventoryTbl_InventoryStatusNotMatched","Trạng thái kho không phù hợp!"},
{"ErridnInventory.Mst_Inventory_CheckListDB_MstInventoryTbl_FlagIn_OutNotMatched","Cờ nhập xuất của kho không phù hợp!"},
{"ErridnInventory.Mst_Inventory_Get","Không lấy được thông tin kho!"},
{"ErridnInventory.WAS_Mst_Inventory_Get","Không lấy được thông tin kho!"},
{"ErridnInventory.Mst_Inventory_Create","Tạo mới kho không thành công!"},
{"ErridnInventory.Mst_Inventory_Create_InvalidOrgID","Mã chi nhánh không hợp lệ!"},
{"ErridnInventory.Mst_Inventory_Create_InvalidInvCode","Mã kho không hợp lệ!"},
{"ErridnInventory.Mst_Inventory_Create_InvalidInvName","Tên kho không hợp lệ!"},
{"ErridnInventory.WAS_Mst_Inventory_Create","Tạo mới kho không thành công!"},
{"ErridnInventory.Mst_Inventory_Update","Cập nhật kho không thành công!"},
{"ErridnInventory.Mst_Inventory_Update_InvalidInvName","Tên kho không hợp lệ!"},
{"ErridnInventory.Mst_Inventory_Update_ExistInvChildActive","Kho con đang hoạt động đã tồn tại!"},
{"ErridnInventory.WAS_Mst_Inventory_Update","Cập nhật kho không thành công!"},
{"ErridnInventory.Mst_Inventory_Delete","Xóa kho không thành công!"},
{"ErridnInventory.WAS_Mst_Inventory_Delete","Xóa kho không thành công!"},
{"ErridnInventory.InvF_MoveOrd_CheckDB_IF_MONoNotFound","Không tìm thấy số phiếu điều chuyển!"},
{"ErridnInventory.InvF_MoveOrd_CheckDB_IF_MONoExist","Số phiếu điều chuyển đã tồn tại!"},
{"ErridnInventory.InvF_MoveOrd_CheckDB_StatusNotMatched","Trạng thái phiếu điều chuyển không phù hợp!"},
{"ErridnInventory.InvF_MoveOrd_SaveX_InvalidIF_MONo","Số phiếu điều chuyển không hợp lệ!"},
{"ErridnInventory.InvF_MoveOrd_SaveX_InvalidStatus","Trạng thái phiếu điều chuyển không hợp lệ!"},
{"ErridnInventory.InvF_MoveOrd_SaveX_InvalidOrgID","Mã chi nhánh không hợp lệ!"},
{"ErridnInventory.InvF_MoveOrd_SaveX_InvF_MoveOrdDtlTblNotFound","Không tìm thấy thông tin chi tiết phiếu điều chuyển!"},
{"ErridnInventory.InvF_MoveOrd_SaveX_InvF_MoveOrdDtlTblInvalid","Thông tin chi tiết phiếu điều chuyển không hợp lệ!"},
{"ErridnInventory.InvF_MoveOrd_SaveX_MoveOrdInstLotNotFound","Không tìm thấy Lô cần điều chuyển!"},
{"ErridnInventory.InvF_MoveOrd_SaveX_MoveOrdInstSerialNotFound","Không tìm thấy Serial cần điều chuyển!"},
{"ErridnInventory.InvF_MoveOrd_SaveX_InvF_MoveOrdDtlTbl_ProductCodeNotFound","Không tìm thấy mã hàng hóa!"},
{"ErridnInventory.InvF_MoveOrd_SaveX_InvF_MoveOrdDtlTbl_ProductCodeFlagActiveNotMatch","Trạng thái hoạt động của mã hàng hóa không phù hợp!"},
{"ErridnInventory.InvF_MoveOrd_SaveX_InvF_MoveOrdDtlTbl_InvalidProductType","Loại hàng hóa không phù hợp!"},
{"ErridnInventory.InvF_MoveOrd_SaveX_InvF_MoveOrdDtlTbl_InvCodeInNotFound","Không tìm thấy mã kho nhập!"},
{"ErridnInventory.InvF_MoveOrd_SaveX_InvF_MoveOrdDtlTbl_InvCodeInFlagActiveNotMath","Trạng thái mã kho nhập không phù hợp!"},
{"ErridnInventory.InvF_MoveOrd_SaveX_InvF_MoveOrdDtlTbl_InvCodeOutNotFound","Không tìm thấy mã kho xuất!"},
{"ErridnInventory.InvF_MoveOrd_SaveX_InvF_MoveOrdDtlTbl_InvCodeOutFlagActiveNotMath","Trạng thái mã kho xuất không phù hợp!"},
{"ErridnInventory.InvF_MoveOrd_SaveX_InvF_MoveOrdDtlTbl_UnitCodeNotEqualUnitCodeInMstProduct","Mã đơn vị không khớp với mã đơn vị trong menu hàng hóa!"},
{"ErridnInventory.InvF_MoveOrd_SaveX_InvF_MoveOrdDtlTbl_InvalidQty","Số lượng điều chuyển không hợp lệ!"},
{"ErridnInventory.InvF_MoveOrd_SaveX_InvF_MoveOrdInstSerialTbl_SerialNoExistDtl","Số Serial đã có trong danh sách!"},
{"ErridnInventory.InvF_MoveOrd_SaveX_InvF_MoveOrdInstSerialTbl_SerialNoNotExistDtl","Số Serial không có trong danh sách!"},
{"ErridnInventory.InvF_MoveOrd_SaveX_InvF_MoveOrdInstLotTbl_LotNoExistDtl","Số Lô đã có trong danh sách!"},
{"ErridnInventory.myCheck_InvF_MoveOrd_TotalQtySerial_QtySerialNoEqualQtyDtl","Số lượng Serial không bằng số lượng chi tiết!"},
{"ErridnInventory.myCheck_InvF_MoveOrd_TotalQtyLot_QtyLOTNoEqualQtyDtl","Số lượng Lô không bằng số lượng chi tiết!"},
{"ErridnInventory.InvF_MoveOrd_Get","Không lấy được thông tin phiếu điều chuyển!"},
{"ErridnInventory.WAS_InvF_MoveOrd_Get","Không lấy được thông tin phiếu điều chuyển!"},
{"ErridnInventory.InvF_MoveOrd_Save","Lưu phiếu điều chuyển không thành công!"},
{"ErridnInventory.WAS_InvF_MoveOrd_Save","Lưu phiếu điều chuyển không thành công!"},
{"ErridnInventory.InvF_MoveOrd_Appr","Duyệt phiếu điều chuyển không thành công!"},
{"ErridnInventory.WAS_InvF_MoveOrd_Appr","Duyệt phiếu điều chuyển không thành công!"},
{"ErridnInventory.InvF_MoveOrd_Cancel","Hủy phiếu điều chuyển không thành công!"},
{"ErridnInventory.WAS_InvF_MoveOrd_Cancel","Hủy phiếu điều chuyển không thành công!"},
{"ErridnInventory.InvF_InvAudit_CheckDB_IF_InvAudNoNotFound","Không tìm thấy phiếu kiểm kê!"},
{"ErridnInventory.InvF_InvAudit_CheckDB_IF_InvAudNoExist","Phiếu kiểm kê đã tồn tại!"},
{"ErridnInventory.InvF_InvAudit_CheckDB_StatusNotMatched","Trạng thái phiếu kiểm kê không phù hợp!"},
{"ErridnInventory.InvF_InvAudit_Get","Không lấy được thông tin phiếu kiểm kê!"},
{"ErridnInventory.WAS_InvF_InvAudit_Get","Không lấy được thông tin phiếu kiểm kê!"},
{"ErridnInventory.InvF_InvAudit_SaveX_InvalidIF_InvAudNo","Số phiếu kiểm kê không hợp lệ!"},
{"ErridnInventory.InvF_InvAudit_SaveX_InvalidStatus","Trạng thái phiếu kiểm kê không hợp lệ!"},
{"ErridnInventory.InvF_InvAudit_SaveX_InvalidOrgID","Mã chi nhánh không hợp lệ!"},
{"ErridnInventory.InvF_InvAudit_SaveX_InvF_InvAuditDtlTblNotFound","Không tìm thấy thông tin chi tiết phiếu kiểm kê!"},
{"ErridnInventory.InvF_InvAudit_SaveX_InvF_InvAuditDtlTblInvalid","Thông tin chi tiết phiếu kiểm kê không hợp lệ!"},
{"ErridnInventory.InvF_InvAudit_SaveX_InvAuditInstLotNotFound","Không tìm thấy Lô cần kiểm kê!"},
{"ErridnInventory.InvF_InvAudit_SaveX_InvAuditInstSerialNotFound","Không tìm thấy Serial cần kiểm kê!"},
{"ErridnInventory.InvF_InvAudit_SaveX_InvF_InvAuditDtlTbl_ProductCodeNotFound","Không tìm thấy mã hàng hóa!"},
{"ErridnInventory.InvF_InvAudit_SaveX_InvF_InvAuditDtlTbl_ProductCodeFlagActiveNotMatch","Trạng thái hoạt động của hàng hóa không phù hợp!"},
{"ErridnInventory.InvF_InvAudit_SaveX_InvF_InvAuditDtlTbl_InvalidProductType","Loại hàng hóa không phù hợp!"},
{"ErridnInventory.InvF_InvAudit_SaveX_InvF_InvAuditDtlTbl_InvCodeInitNotFound","Không tìm thấy mã kho ban đầu!"},
{"ErridnInventory.InvF_InvAudit_SaveX_InvF_InvAuditDtlTbl_InvCodeInitFlagActiveNotMath","Trạng thái hoạt động của mã kho ban đầu không hợp lệ!"},
{"ErridnInventory.InvF_InvAudit_SaveX_InvF_InvAuditDtlTbl_InvCodeActualNotFound","Không tìm thấy mã kho thực tế!"},
{"ErridnInventory.InvF_InvAudit_SaveX_InvF_InvAuditDtlTbl_InvCodeActualFlagActiveNotMath","Trạng thái hoạt động của mã kho thực tế không phù hợp!"},
{"ErridnInventory.InvF_InvAudit_SaveX_InvF_InvAuditDtlTbl_UnitCodeNotEqualUnitCodeInMstProduct","Mã đơn vị không khớp với mã đơn vị trong menu hàng hóa!"},
{"ErridnInventory.InvF_InvAudit_SaveX_InvF_InvAuditInstLotTbl_LotNoExistDtl","Số Lô đã có trong danh sách!"},
{"ErridnInventory.InvF_InvAudit_SaveX_InvF_InvAuditInstSerialTbl_SerialNoExistDtl","Số Seral đã có trong danh sách!"},
{"ErridnInventory.InvF_InvAudit_SaveX_InvF_InvAuditDtlTbl_ExistFlagAudit","Cờ kiểm kê đã tồn tại!"},
{"ErridnInventory.myCheck_InvF_InvAudit_TotalQtySerial_QtySerialNoEqualQtyDtl","Số lượng Serial không bằng số lượng chi tiết!"},
{"ErridnInventory.myCheck_InvF_InvAudit_TotalQtyLot_QtyLOTNoEqualQtyDtl","Số lượng Lô không bằng số lượng chi tiết!"},
{"ErridnInventory.InvF_InvAudit_Appr","Duyệt phiếu kiểm kê không thành công!"},
{"ErridnInventory.WAS_InvF_InvAudit_Appr","Duyệt phiếu kiểm kê không thành công!"},
{"ErridnInventory.InvF_InvAudit_Save","Lưu phiếu kiểm kê không thành công!"},
{"ErridnInventory.WAS_InvF_InvAudit_Save","Lưu phiếu kiểm kê không thành công!"},
{"ErridnInventory.InvF_InvAudit_Cancel","Hủy phiếu kiểm kê không thành công!"},
{"ErridnInventory.WAS_InvF_InvAudit_Cancel","Hủy phiếu kiểm kê không thành công!"},
{"ErridnInventory.InvF_InvAudit_Finish","Kết thúc kiểm kê không thành công!"},
{"ErridnInventory.InvF_InvAudit_Finish_InvF_InvAuditDtlTbl_ExistFlagAudit","Hàng hóa chưa được kiểm kê!"},
{"ErridnInventory.WAS_InvF_InvAudit_Finish","Kết thúc kiểm kê không thành công!"},
{"ErridnInventory.mycheck_Inv_InventoryBalance_NoEqualInventoryInDB","Tồn kho khác với cơ sở dữ liệu!"},
{"ErridnInventory.mycheck_Inv_InventoryBalanceLot_NoEqualInventoryInDB","Lô tồn kho khác với cơ sở dữ liệu!"},
{"ErridnInventory.mycheck_Inv_InventoryBalanceSerial_NoEqualInventoryInDB","Serial tồn kho khác với cơ sở dữ liệu!"},
{"ErridnInventory.InvF_InvAuditDtl_FlagAuditX","Cờ kiểm kê không thành công!"},
{"ErridnInventory.InvF_InvAuditDtl_FlagAuditX_InvF_InvAuditDtlTblNotFound","Không tìm thấy thông tin chi tiết phiếu kiểm kê!"},
{"ErridnInventory.InvF_InvAuditDtl_FlagAuditX_InvF_InvAuditDtlTblInvalid","Chi tiết phiếu kiểm kê không hợp lệ!"},
{"ErridnInventory.InvF_InvAuditDtl_FlagAuditX_InvF_InvAuditInstLotNotFound","Không tìm thấy Lô cần kiểm kê!"},
{"ErridnInventory.InvF_InvAuditDtl_FlagAuditX_InvAuditInstSerialNotFound","Không tìm thấy Serial cần kiểm kê!"},
{"ErridnInventory.InvF_InvAuditDtl_FlagAudit","Cờ kiểm kê không thành công!"},
{"ErridnInventory.WAS_InvF_InvAuditDtl_FlagAudit","Cờ kiểm kê không thành công!"},
{"ErridnInventory.InvF_InvAuditDtl_FlagAuditSpecial","Cờ kiểm kê đặc biệt không thành công!"},
{"ErridnInventory.WAS_InvF_InvAuditDtl_FlagAuditSpecial","Cờ kiểm kê đặc biệt không thành công!"},
{"ErridnInventory.InvF_InventoryIn_CheckDB_InvInNoNotFound","Không tìm thấy số phiếu nhập!"},
{"ErridnInventory.InvF_InventoryIn_CheckDB_InvInNoExist","Số phiếu nhập đã tồn tại!"},
{"ErridnInventory.InvF_InventoryIn_CheckDB_StatusNotMatched","Trạng thái phiếu nhập không phù hợp!"},
{"ErridnInventory.InvF_InventoryIn_Get","Không lấy được thông tin phiếu nhập !"},
{"ErridnInventory.WAS_InvF_InventoryIn_Get","Không lấy được thông tin phiếu nhập !"},
{"ErridnInventory.InvF_InventoryIn_SaveX","Lưu phiếu nhập không thàng công!"},
{"ErridnInventory.InvF_InventoryIn_SaveX_InvalidIF_InvInNo","Số phiếu nhập không hợp lệ!"},
{"ErridnInventory.InvF_InventoryIn_SaveX_InvalidStatus","Trạng thái Phiếu nhập không hợp lệ!"},
{"ErridnInventory.InvF_InventoryIn_SaveX_InvalidOrgID","Mã tổ chức không hợp lệ!"},
{"ErridnInventory.InvF_InventoryIn_SaveX_InvalidCustomerCode","Mã khách hàng không hợp lệ!"},
{"ErridnInventory.InvF_InventoryIn_SaveX_InvalidValues","Các giá trị không hợp lệ!"},
{"ErridnInventory.InvF_InventoryIn_SaveX_InvFInventoryInDtlTblNotFound","Không tìm thấy thông tin chi tiết phiếu nhập!"},
{"ErridnInventory.InvF_InventoryIn_SaveX_InvFInventoryInDtlTblInvalid","Chi tiết phiếu nhập không hợp lệ!"},
{"ErridnInventory.InvF_InventoryIn_SaveX_InventoryInInstSerialNotFound","Không tìm thấy Serial nhập trong bảng dữ liệu!"},
{"ErridnInventory.InvF_InventoryIn_SaveX_InventoryInInstLotNotFound","Không tìm thấy Lô nhập trong bảng dữ liệu!"},
{"ErridnInventory.InvF_InventoryIn_SaveX_InventoryInQRNotFound","Không tìm thấy mã xác thực nhập kho!"},
{"ErridnInventory.InvF_InventoryIn_SaveX_InvF_InventoryInDtlTbl_ProductCodeFlagActiveNotMatch","Trạng thái hoạt động của mã hàng hóa không phù hợp!"},
{"ErridnInventory.InvF_InventoryIn_SaveX_InvF_InventoryInDtlTbl_InvalidProductType","Loại hàng hóa không hợp lệ!"},
{"ErridnInventory.InvF_InventoryIn_SaveX_InvF_InventoryInDtlTbl_ProductCodeNotFound","Không tìm thấy mã hàng hóa!"},
{"ErridnInventory.InvF_InventoryIn_SaveX_InvF_InventoryInDtlTbl_InvCodeActualNotFound","Không tìm thấy mã kho thực tế!"},
{"ErridnInventory.InvF_InventoryIn_SaveX_InvF_InventoryInDtlTbl_InvCodeActualFlagActiveNotMath","Trạng thái hoạt động của mã kho thực tế không phù hợp!"},
{"ErridnInventory.InvF_InventoryIn_SaveX_InvF_InventoryInDtlTbl_UnitCodeNotEqualUnitCodeInMstProduct","Mã đơn vị không khớp với mã đơn vị trong menu hàng hóa!"},
{"ErridnInventory.InvF_InventoryIn_SaveX_InvF_InventoryInInstLotTbl_LotNoExistDtl","Số Lô đã có trong danh sách!"},
{"ErridnInventory.InvF_InventoryIn_SaveX_InvF_InventoryInInstSerialTbl_SerialNoExistDtl","Số Serial đã có trong danh sách!"},
{"ErridnInventory.InvF_InventoryIn_SaveX_InvF_InventoryInInstSerialTbl_SerialExistInInv","Serial đã được nhập kho!"},
{"ErridnInventory.InvF_InventoryIn_SaveX_InvF_InventoryInQATbl_QANoExistListSeiralInvIn","Danh sách Serial nhập kho"},
{"ErridnInventory.InvF_InventoryIn_SaveX_InvalidOrderNoSys","Số đơn hàng hệ thống không hợp lệ!"},
{"ErridnInventory.InvF_InventoryIn_SaveX_InvalidOrderType","Loại đơn hàng không hợp lệ!"},
{"ErridnInventory.myCheck_InvF_InventoryInDtl_Total_ValInAfterDescNoEqualMyCalc",""},
{"ErridnInventory.myCheck_InvF_InventoryIn_Total_ValInAfterDescNoEqualMyCalc",""},
{"ErridnInventory.myCheck_InvF_InventoryIn_TotalQtySerial_QtySerialNoEqualQtyDtl","Số lượng Serial không bằng số lượng chi tiết!"},
{"ErridnInventory.myCheck_InvF_InventoryIn_TotalQtyLot_QtyLOTNoEqualQtyDtl","Số lượng Lô không bằng số lượng chi tiết!"},
{"ErridnInventory.InvF_InventoryIn_Save","Lưu phiếu nhập không thàng công!"},
{"ErridnInventory.WAS_InvF_InventoryIn_Save","Lưu phiếu nhập không thàng công!"},
{"ErridnInventory.InvF_InventoryIn_ApprX","Duyệt phiếu nhập không thành công!"},
{"ErridnInventory.InvF_InventoryIn_ApprX_InventoryInTblNotFound","Không tìm thấy thông tin chi tiết phiếu nhập!"},
{"ErridnInventory.InvF_InventoryIn_ApprX_InventoryInTblInvalid","Chi tiết phiếu nhập không hợp lệ!"},
{"ErridnInventory.InvF_InventoryIn_Appr","Duyệt phiếu nhập không thành công!"},
{"ErridnInventory.InvF_InventoryIn_SaveAndAppr","Lưu và Duyệt phiếu nhập không thành công!"},
{"ErridnInventory.WAS_InvF_InventoryIn_SaveAndAppr","Lưu và Duyệt phiếu nhập không thành công!"},
{"ErridnInventory.WAS_InvF_InventoryIn_Appr","Duyệt phiếu nhập không thành công!"},
{"ErridnInventory.InvF_InventoryIn_UpdAfterAppr","Sửa phiếu đã duyệt không thành công!"},
{"ErridnInventory.WAS_InvF_InventoryIn_UpdAfterAppr","Sửa phiếu đã duyệt không thành công!"},
{"ErridnInventory.InvF_InventoryIn_Cancel","Hủy phiếu nhập không thành công!"},
{"ErridnInventory.WAS_InvF_InventoryIn_Cancel","Hủy phiếu nhập không thành công!"},
{"ErridnInventory.Mst_TempPrintType_CheckDB_TempPrintTypeNotFound","Không tìm thấy loại mẫu in!"},
{"ErridnInventory.Mst_TempPrintType_CheckDB_TempPrintTypeExist","Loại mẫu in đã tồn tại!"},
{"ErridnInventory.Mst_TempPrintType_CheckDB_StatusNotMatched","Trạng thái loại mẫu in không hợp lệ!"},
{"ErridnInventory.Mst_TempPrintType_Get","Không lấy được thông tin loại mẫu in!"},
{"ErridnInventory.WAS_Mst_TempPrintType_Get","Không lấy được thông tin loại mẫu in!"},
{"ErridnInventory.InvF_TempPrint_CheckDB_IF_TempPrintNoNotFound","Không tìm thấy số mẫu in!"},
{"ErridnInventory.InvF_TempPrint_CheckDB_IF_TempPrintNoExist","Số mẫu in đã tồn tại!"},
{"ErridnInventory.InvF_TempPrint_CheckDB_StatusNotMatched","Trạng thái mẫu in không phù hợp!"},
{"ErridnInventory.InvF_TempPrint_Get","Không lấy được thông tin mẫu in!"},
{"ErridnInventory.WAS_InvF_TempPrint_Get","Không lấy được thông tin mẫu in!"},
{"ErridnInventory.InvF_TempPrint_SaveX","Lưu mẫu in không thành công!"},
{"ErridnInventory.InvF_TempPrint_SaveX_InvalidIF_TempPrintNo","Số mẫu in không hợp lệ!"},
{"ErridnInventory.InvF_TempPrint_Save","Lưu mẫu in không thành công!"},
{"ErridnInventory.WAS_InvF_TempPrint_Save","Lưu mẫu in không thành công!"},
{"ErridnInventory.UploadFileNewX_InvalidFilePath","File đính kèm không hợp lệ!"},
{"ErridnInventory.myCheck_Inv_InventoryBalanceFormBlock_ExistAud","Hàng hóa đang được kiểm kê!"},
{"ErridnInventory.myCheck_Inv_InventoryBalanceFormBlock_ExistInOrOutOrMoveOrAuditPending","Hàng hóa đang được nhập, xuất, điều chuyển hoặc kiểm kê"},
{"ErridnInventory.InvF_InventoryOut_CheckDB_InvOutNoNotFound","Không tìm thấy số phiếu xuất!"},
{"ErridnInventory.InvF_InventoryOut_CheckDB_InvOutNoExist","Số phiếu xuất đã tồn tại!"},
{"ErridnInventory.InvF_InventoryOut_CheckDB_StatusNotMatched","Trạng thái phiếu xuất không phù hợp!"},
{"ErridnInventory.InvF_InventoryOut_Get","Không lấy được thông tin phiếu xuất!"},
{"ErridnInventory.WAS_InvF_InventoryOut_Get","Không lấy được thông tin phiếu xuất!"},
{"ErridnInventory.InvF_InventoryOut_SaveX_InvalidRefNoSys","Số RefNo không hợp lệ!"},
{"ErridnInventory.InvF_InventoryOut_SaveX_InvalidRefType","Loại Ref không hợp lệ!"},
{"ErridnInventory.InvF_InventoryOut_SaveX_InvalidIF_InvOutNo","Số phiếu xuất không hợp lệ!"},
{"ErridnInventory.InvF_InventoryOut_SaveX_InvalidStatus","Trạng thái phiếu xuất không hợp lệ!"},
{"ErridnInventory.InvF_InventoryOut_SaveX_InvalidOrgID","Mã tổ chức không hợp lệ!"},
{"ErridnInventory.InvF_InventoryOut_SaveX_InvalidValues","Giá trị không hợp lệ!"},
{"ErridnInventory.InvF_InventoryOut_SaveX_InvFInventoryOutDtlTblNotFound","Không tìm thấy thông tin chi tiết phiếu xuất kho!"},
{"ErridnInventory.InvF_InventoryOut_SaveX_InvFInventoryOutDtlTblInvalid","Chi tiết phiếu xuất kho không hợp lệ!"},
{"ErridnInventory.InvF_InventoryOut_SaveX_InventoryOutInstLotNotFound","Không tìm thấy Lô xuất trong bảng dữ liệu!"},
{"ErridnInventory.InvF_InventoryOut_SaveX_InventoryOutInstSerialNotFound","Không tìm thấy Serial xuất trong bảng dữ liệu!"},
{"ErridnInventory.InvF_InventoryOut_SaveX_InventoryOutQRNotFound","Không tìm thấy mã xác thực xuất kho!"},
{"ErridnInventory.InvF_InventoryOut_SaveX_InventoryOutQRTbl_InvalidQRType","Loại mã xác thực không hợp lệ!"},
{"ErridnInventory.InvF_InventoryOut_SaveX_InvF_InventoryOutDtlTbl_ProductCodeNotFound","Không tìm thấy mã hàng hóa!"},
{"ErridnInventory.InvF_InventoryOut_SaveX_InvF_InventoryOutDtlTbl_ProductCodeFlagActiveNotMatch","Trạng thái hoạt động của mã hàng hóa không hợp lệ!"},
{"ErridnInventory.InvF_InventoryOut_SaveX_InvF_InventoryOutDtlTbl_InvalidProductType","Loại hàng hóa không hợp lệ!"},
{"ErridnInventory.InvF_InventoryOut_SaveX_InvF_InventoryOutDtlTbl_InvCodeActualNotFound","Không tìm thấy mã kho thực tế!"},
{"ErridnInventory.InvF_InventoryOut_SaveX_InvF_InventoryOutDtlTbl_InvCodeActualFlagActiveNotMath","Trạng thái hoạt động của mã kho thực tế không phù hợp!"},
{"ErridnInventory.InvF_InventoryOut_SaveX_InvF_InventoryOutDtlTbl_UnitCodeNotEqualUnitCodeInMstProduct","Mã đơn vị không khớp với mã đơn vị trong menu hàng hóa!"},
{"ErridnInventory.InvF_InventoryOut_SaveX_InvF_InventoryOutInstLotTbl_LotNoExistDtl","Số Lô đã có trong danh sách!"},
{"ErridnInventory.InvF_InventoryOut_SaveX_InvF_InventoryOutInstLotTbl_SerialNoExistDtl","Số Serial đã có trong danh sách!"},
{"ErridnInventory.InvF_InventoryOut_SaveX_InvF_InventoryOutQATbl_QANoExistListSeiralInvIn","Danh sách Serial nhập kho đã tồn tại!"},
{"ErridnInventory.InvF_InventoryOut_SaveX_InvFInventoryOutCoverTblNotFound","Không tìm thấy thông tin xuất ngoài!"},
{"ErridnInventory.InvF_InventoryOut_SaveX_InvFInventoryOutCoverTblInvalid","Thông tin xuất ngoài không hợp lệ!"},
{"ErridnInventory.InvF_InventoryOut_SaveX_InvalidCustomerCode","Mã khách hàng không hợp lệ!"},
{"ErridnInventory.UserExchangeStatus_InvF_DefectOut_BuildTable_01_InvalidBlockStatus","Trạng thái block không hợp lệ!"},
{"ErridnInventory.UserExchangeStatus_InvF_DefectOut_BuildTable_01_NotFoundSerialCandidate","Không tìm thấy Serial dự phòng"},
{"ErridnInventory.InvF_InventoryOut_Save","Lưu phiếu xuất không thành công!"},
{"ErridnInventory.InvF_InventoryOut_SaveAndAppr_Cheo","Xuất chéo không thành công!"},
{"ErridnInventory.InvF_InventoryOut_SaveAndAppr_Cheo_InvalidQtyCheoOverQtyRoot","Số lượng xuất chéo > số lượng còn lại trong phiếu xuất!"},
{"ErridnInventory.InvF_InventoryOut_SaveAndAppr_Cheo_InvalidIF_InvOutNo","Số phiếu xuất không hợp lệ!"},
{"ErridnInventory.InvF_InventoryOut_SaveAndAppr_Cheo_InvalidStatus","Trạng thái phiếu xuất không hợp lệ!"},
{"ErridnInventory.InvF_InventoryOut_SaveAndAppr_Cheo_InvalidCustomerCode","Mã khách hàng không hợp lệ!"},
{"ErridnInventory.InvF_InventoryOut_SaveAndAppr_Cheo_InvalidValues","Giá trị không hợp lệ!"},
{"ErridnInventory.InvF_InventoryOut_SaveAndAppr_Cheo_ExistOrderNoOutCheo","Số đơn hàng xuất chéo đã tồn tại!"},
{"ErridnInventory.InvF_InventoryOut_SaveAndAppr_Cheo_InvAudNoOutCheo","Không thể xuất chéo hàng hóa đang kiểm kê!"},
{"ErridnInventory.InvF_InventoryOut_SaveAndAppr_Cheo_ExistRefNoOutCheo","Phiếu xuất chéo theo RefNo đã tồn tại!"},
{"ErridnInventory.WAS_InvF_InventoryOut_Save","Lưu phiếu xuất không thành công!"},
{"ErridnInventory.WAS_InvF_InventoryOut_SaveAndAppr","Lưu và Duyệt phiếu xuất không thành công!"},
{"ErridnInventory.WAS_InvF_InventoryOut_SaveAndAppr_Cheo","Xuất chéo không thành công!"},
{"ErridnInventory.InvF_InventoryOut_SaveAndAppr","Lưu và Duyệt phiếu xuất không thành công!"},
{"ErridnInventory.OSDMS_InvF_InventoryOut_UpdQtyOrder","Cập nhật số lượng đơn hàng không thành công!"},
{"ErridnInventory.OSDMS_InvF_InventoryOut_UpdQtyOrder_InvalidUrl_OS_Inv_AllNetWork",""},
{"ErridnInventory.OSDMS_InvF_InventoryOut_UpdQtyOrder_InvalidOrderType","Loại đơn hàng không hợp lệ!"},
{"ErridnInventory.OSDMS_InvF_InventoryOut_UpdQtyOrder_InvalidOrderMixNoSys","Số đơn hàng hỗ hợp trên hệ thống không hợp lệ!"},
{"ErridnInventory.OSVeloca_SerRO_InvF_Transaction_AddQtyMix","Thêm số lượng hỗn hợp không thành công!"},
{"ErridnInventory.OSVeloca_SerRO_InvF_Transaction_AddQtyMix_InvalidUrl_OS_Inv_AllNetWork",""},
{"ErridnInventory.OSVeloca_WA_SerRO_InvF_Transaction_AddQtyMix","Thêm số lượng hỗn hợp không thành công!"},
{"ErridnInventory.OS_MstSvDMS_MstSv_Mst_Network_GetByMST","Không lấy được thông tin bằng mã số thuế!"},
{"ErridnInventory.OS_MstSvVeloca_MstSv_Mst_Network_GetByMST","Không lấy được thông tin bằng mã số thuế!"},
{"ErridnInventory.OS_MstSvInBrand_MstSv_Mst_Network_GetByMST","Không lấy được thông tin bằng mã số thuế!"},
{"ErridnInventory.OS_MstSv_Sys_User_GetAccessToken","Không lấy được mã thông báo truy cập!"},
{"ErridnInventory.OSDMS_InvF_InventoryCusReturn_UpdQtyRtnOrder","Cập nhật số lượng trả theo đơn hàng không thành công!"},
{"ErridnInventory.OSDMS_InvF_InventoryCusReturn_UpdQtyRtnOrder_InvalidUrl_OS_Inv_AllNetWork",""},
{"ErridnInventory.OSDMS_InvF_InventoryCusReturn_UpdQtyRtnOrder_InvalidOrderMixNoSys","Số đơn hàng hỗn hợp không hợp lệ!"},
{"ErridnInventory.OSDMS_InvF_InventoryCusReturn_UpdQtyRtnOrder_InvalidOrderType","Loại đơn hàng không hợp lệ!"},
{"ErridnInventory.OSInBrand_Inv_InventoryVerifiedID_AddMulti_NoGenInvFIn",""},
{"ErridnInventory.OSInBrand_Inv_InventoryVerifiedID_AddMulti_NoGenInvFIn_InvalidUrl_OS_Inv_AllNetWork",""},
{"ErridnInventory.OSInBrand_Inv_InventoryVerifiedID_OutInv","Xuất kho không thành công!"},
{"ErridnInventory.OSInBrand_Inv_InventoryVerifiedID_OutInv_InvalidUrl_OS_Inv_AllNetWork",""},
{"ErridnInventory.OSInBrand_Inv_InventoryGenID_CheckListDB","Kiểm tra danh sách cơ sở dữ liệu!"},
{"ErridnInventory.OSInBrand_Inv_InventoryGenID_CheckListDB_InvalidUrl_OS_Inv_AllNetWork","Kiểm tra danh sách cơ sở dữ liệu trên tất cả các NetWork!"},
{"ErridnInventory.Inv_InventoryBalanceSerial_CheckDB_InventoryBalanceSerialNotFound","Không tìm thấy Serial tồn kho!"},
{"ErridnInventory.Inv_InventoryBalanceSerial_CheckDB_InventoryBalanceSerialExist","Serial đã tồn tại trong kho!"},
{"ErridnInventory.Inv_InventoryBalanceSerial_CheckDB_FlagNGNotMatched",""},
{"ErridnInventory.Inv_InventoryBalanceSerial_CheckListSerialExist_SerialNoNotExistInInv","Số seri không tồn tại trong kho!"},
{"ErridnInventory.Inv_InventoryBalanceSerial_CheckListSerialExist_SerialNoExistedInInv","Số seri đã tồn tại trong kho!"},
{"ErridnInventory.Inv_InventoryBalanceSerial_CheckListSerialAndInvCodeExist_SerialNoNotExistInInv","Số seri không tồn tại trong kho!"},
{"ErridnInventory.myCheck_InvF_InventoryOut_TotalQtySerial_QtySerialNoEqualQtyDtl","Số lượng Serial không bằng số lượng chi tiết!"},
{"ErridnInventory.myCheck_InvF_InventoryOut_TotalQtyLot_QtyLOTNoEqualQtyDtl","Số lượng Lô không bằng số lượng chi tiết!"},
{"ErridnInventory.myCheck_InvF_InventoryOut_Total_ValOutAfterDescNoEqualMyCalc",""},
{"ErridnInventory.myCheck_InvF_InventoryOutCover_Total_ValOutAfterDescNoEqualMyCalc",""},
{"ErridnInventory.InvF_InventoryOut_ApprX","Duyệt phiếu xuất không thành công!"},
{"ErridnInventory.InvF_InventoryOut_Appr","Duyệt phiếu xuất không thành công!"},
{"ErridnInventory.WAS_InvF_InventoryOut_Appr","Duyệt phiếu xuất không thành công!"},
{"ErridnInventory.InvF_InventoryOut_Cancel","Hủy phiếu xuất không thành công!"},
{"ErridnInventory.WAS_InvF_InventoryOut_Cancel","Hủy phiếu xuất không thành công!"},
{"ErridnInventory.WAS_Inv_InventoryBalanceLot_Get","Không lấy được thông tin Lô tồn kho!"},
{"ErridnInventory.Inv_InventoryBalanceLot_Get","Không lấy được thông tin Lô tồn kho!"},
{"ErridnInventory.OS_Inv_InventoryBalance_GetQty","Không lấy được thông tin số lượng tồn kho!"},
{"ErridnInventory.OS_Inv_InventoryBalance_GetQtyX_Inv_InventoryBalance_GetQtyTblNotFound","Không tìm thấy thông tin chi tiết số lượng tồn kho!"},
{"ErridnInventory.WAS_OS_Inv_InventoryBalance_GetQty","Không lấy được thông tin số lượng tồn kho!"},
{"ErridnInventory.myCheck_InvF_InventoryCusReturn_CheckQtyReturnOverQtyOut","Số lượng trả lại > Số lượng xuất!"},
{"ErridnInventory.myCheck_InventoryCusReturnDtl_CheckQtyReturnOverQtyOut","Số lượng trả lại > Số lượng xuất!"},
{"ErridnInventory.myCheck_InvF_InventoryOutInstLot_CheckQtyReturnOverQtyOut","Số lượng trả lại > Số lượng xuất!"},
{"ErridnInventory.myCheck_InvF_InventoryCusReturnInstSerial_CheckQtyReturnOverQtyOut","Số lượng trả lại > Số lượng xuất!"},
{"ErridnInventory.myCheck_InvF_InventoryCusReturn_TotalQtySerial_QtySerialNoEqualQtyDtl","Số lượng Serial không bằng số lượng chi tiết!"},
{"ErridnInventory.myCheck_InvF_InventoryCusReturn_TotalQtyLot_QtyLOTNoEqualQtyDtl","Số lượng Lô không bằng số lượng chi tiết!"},
{"ErridnInventory.myCheck_InvF_InventoryCusReturn_Total_ValCusReturnAfterDescNoEqualMyCalc",""},
{"ErridnInventory.myCheck_InvF_InventoryCusReturnDtl_Total_ValCusReturnAfterDescNoEqualMyCalc",""},
{"ErridnInventory.InvF_InventoryCusReturn_CheckDB_InvInNoNotFound","Không tìm thấy số phiếu !"},
{"ErridnInventory.InvF_InventoryCusReturn_CheckDB_InvInNoExist","Số phiếu đã tồn tại!"},
{"ErridnInventory.InvF_InventoryCusReturn_CheckDB_StatusNotMatched","Trạng thái phiếu không phù hợp!"},
{"ErridnInventory.InvF_InventoryCusReturn_Get","Không lấy được thông tin phiếu!"},
{"ErridnInventory.InvF_InventoryCusReturn_Save","Lưu phiếu không thành công!"},
{"ErridnInventory.InvF_InventoryCusReturn_SaveX_InvalidIF_InvCusReturnNo","Số phiếu không hợp lệ!"},
{"ErridnInventory.InvF_InventoryCusReturn_SaveX_InvalidStatus","Trạng thái phiếu không hợp lệ!"},
{"ErridnInventory.InvF_InventoryCusReturn_SaveX_InvalidOrgID","Mã tổ chức không hợp lệ!"},
{"ErridnInventory.InvF_InventoryCusReturn_SaveX_InvalidCustomerCode","Mã khách hàng không hợp lệ!"},
{"ErridnInventory.InvF_InventoryCusReturn_SaveX_InvalidValues","Giá trị không hợp lệ!"},
{"ErridnInventory.InvF_InventoryCusReturn_SaveX_InvalidRefSys",""},
{"ErridnInventory.InvF_InventoryCusReturn_SaveX_InvlidRefType",""},
{"ErridnInventory.InvF_InventoryCusReturn_SaveX_InvFInventoryInDtlTblNotFound","Không tìm thấy thông tin chi tiết phiếu!"},
{"ErridnInventory.InvF_InventoryCusReturn_SaveX_InvFInventoryInDtlTblInvalid","Chi tiết phiếu không hợp lệ!"},
{"ErridnInventory.InvF_InventoryCusReturn_SaveX_InventoryInInstLotNotFound","Không tìm thấy Lô nhập!"},
{"ErridnInventory.InvF_InventoryCusReturn_SaveX_InventoryInInstSerialNotFound","Không tìm thấy Serial nhập!"},
{"ErridnInventory.InvF_InventoryCusReturn_SaveX_InvF_InventoryCusReturnDtlTbl_ProductCodeNotFound","Không tìm thấy mã hàng hóa!"},
{"ErridnInventory.InvF_InventoryCusReturn_SaveX_InvF_InventoryCusReturnDtlTbl_ProductCodeFlagActiveNotMatch","Trạng thái hoạt động của hàng hóa không phù hợp!"},
{"ErridnInventory.InvF_InventoryCusReturn_SaveX_InvF_InventoryCusReturnDtlTbl_InvalidProductType","Loại hàng hóa không hợp lệ!"},
{"ErridnInventory.InvF_InventoryCusReturn_SaveX_InvF_InventoryCusReturnDtlTbl_InvCodeActualNotFound","Không tìm thấy mã kho thực tế!"},
{"ErridnInventory.InvF_InventoryCusReturn_SaveX_InvF_InventoryCusReturnDtlTbl_InvCodeActualFlagActiveNotMath","Trạng thái mã kho thực tế không phù hợp!"},
{"ErridnInventory.InvF_InventoryCusReturn_SaveX_InvF_InventoryCusReturnDtlTbl_UnitCodeNotEqualUnitCodeInMstProduct","Mã đơn vị không khớp với mã đơn vị trong menu hàng hóa!"},
{"ErridnInventory.InvF_InventoryCusReturn_SaveX_InvF_InventoryCusReturnInstLotTbl_LotNoExistDtl","Số Lô đã có trong danh sách!"},
{"ErridnInventory.InvF_InventoryCusReturn_SaveX_InvF_InventoryCusReturnInstSerialTbl_SerialNoExistDtl","Số Serial đã có trong danh sách!"},
{"ErridnInventory.InvF_InventoryCusReturn_SaveX_InvF_InventoryCusReturnInstSerialTbl_SerialExistInInv","Serial đã tồn tại trong phiếu!"},
{"ErridnInventory.InvF_InventoryCusReturn_SaveX_InvFInventoryOutCoverTblNotFound",""},
{"ErridnInventory.InvF_InventoryCusReturn_SaveX_InvFInventoryOutCoverTblInvalid",""},
{"ErridnInventory.myCheck_InvF_InventoryCusReturnCover_Total_ValCusReturnAfterDescNoEqualMyCalc",""},
{"ErridnInventory.InvF_InventoryCusReturn_Appr","Duyệt phiếu không thành công!"},
{"ErridnInventory.InvF_InventoryCusReturnAppr_InvalidQtyReturn","Số lượng trả không hợp lệ!"},
{"ErridnInventory.InvF_InventoryCusReturn_Cancel","Hủy phiếu không thành công!"},
{"ErridnInventory.WAS_InvF_InventoryCusReturn_Appr","Duyệt phiếu không thành công!"},
{"ErridnInventory.WAS_InvF_InventoryCusReturn_Cancel","Hủy phiếu không thành công!"},
{"ErridnInventory.WAS_InvF_InventoryCusReturn_Get","Không lấy được thông tin phiếu!"},
{"ErridnInventory.WAS_InvF_InventoryCusReturn_Save","Lưu phiếu không thành công!"},
{"ErridnInventory.myCheck_InvF_InventoryReturnSup_TotalQtySerial",""},
{"ErridnInventory.myCheck_InvF_InventoryReturnSup_TotalQtySerial_QtySerialNoEqualQtyDtl","Số lượng Serial không bằng số lượng chi tiết!"},
{"ErridnInventory.myCheck_InvF_InventoryReturnSup_TotalQtyLot_QtyLOTNoEqualQtyDtl","Số lượng Lô không bằng số lượng chi tiết!"},
{"ErridnInventory.myCheck_InvF_InventoryReturnSup_Total_ValInAfterDescNoEqualMyCalc",""},
{"ErridnInventory.myCheck_InvF_InventoryReturnSupDtl_Total_ValInAfterDescNoEqualMyCalc",""},
{"ErridnInventory.myCheck_InvF_InventoryReturnSup_Total_ValReturnSupAfterDescNoEqualMyCalc",""},
{"ErridnInventory.myCheck_InvF_InventoryReturnSupDtl_Total_ValReturnSupAfterDescNoEqualMyCalc",""},
{"ErridnInventory.InvF_InventoryReturnSup_CheckDB","Kiểm tra cơ sở dữ liệu không thành công!"},
{"ErridnInventory.InvF_InventoryReturnSup_CheckDB_InvInNoNotFound","Không tìm thấy số phiếu!"},
{"ErridnInventory.InvF_InventoryReturnSup_CheckDB_InvInNoExist","Số phiếu đã tồn tại!"},
{"ErridnInventory.InvF_InventoryReturnSup_CheckDB_StatusNotMatched","Trạng thái phiếu không phù hợp!"},
{"ErridnInventory.InvF_InventoryReturnSup_Get","Không lấy được thông tin phiếu!"},
{"ErridnInventory.InvF_InventoryReturnSup_SaveX_InvalidIF_InvReturnSupNo","Số phiếu không hợp lệ!"},
{"ErridnInventory.InvF_InventoryReturnSup_SaveX_InvalidStatus","Trạng thái phiếu không hợp lệ!"},
{"ErridnInventory.InvF_InventoryReturnSup_SaveX_InvalidOrgID","Mã tổ chức không hợp lệ!"},
{"ErridnInventory.InvF_InventoryReturnSup_SaveX_InvalidCustomerCode","Mã khách hàng không hợp lệ!"},
{"ErridnInventory.InvF_InventoryReturnSup_SaveX_InvalidValues","Giá trị không hợp lệ!"},
{"ErridnInventory.InvF_InventoryReturnSup_SaveX_InventoryReturnSupDtlTblNotFound","Không tìm thấy thông tin chi tiết phiếu trả hàng NCC!"},
{"ErridnInventory.InvF_InventoryReturnSup_SaveX_InventoryReturnSupDtlTblInvalid","Chi tiết phiếu không hợp lệ!"},
{"ErridnInventory.InvF_InventoryReturnSup_SaveX_InventoryReturnSupInstLotNotFound","Không tìm thấy thông tin Lô!"},
{"ErridnInventory.InvF_InventoryReturnSup_SaveX_InventoryInInstSerialNotFound","Không tìm thấy thông tin Serial!"},
{"ErridnInventory.InvF_InventoryReturnSup_SaveX_InvF_InventoryReturnSupDtlTbl_ProductCodeNotFound","Không tìm thấy mã hàng hóa!"},
{"ErridnInventory.InvF_InventoryReturnSup_SaveX_InvF_InventoryReturnSupDtlTbl_ProductCodeFlagActiveNotMatch","Trạng thái hoạt động của hàng hóa không phù hợp!"},
{"ErridnInventory.InvF_InventoryReturnSup_SaveX_InvF_InventoryReturnSupDtlTbl_InvalidProductType","Loại hàng hóa không phù hợp!"},
{"ErridnInventory.InvF_InventoryReturnSup_SaveX_InvF_InventoryReturnSupDtlTbl_InvCodeActualNotFound","Không tìm thấy mã kho thực tế!"},
{"ErridnInventory.InvF_InventoryReturnSup_SaveX_InvF_InventoryReturnSupDtlTbl_InvCodeActualFlagActiveNotMath","Trạng thái hoạt động của mã kho thực tế không phù hợp!"},
{"ErridnInventory.InvF_InventoryReturnSup_SaveX_InvF_InventoryReturnSupDtlTbl_UnitCodeNotEqualUnitCodeInMstProduct","Mã đơn vị không khớp với mã đơn vị trong menu hàng hóa!"},
{"ErridnInventory.InvF_InventoryReturnSup_SaveX_InvF_InventoryReturnSupDtlTbl_InvalidValues","Giá trị không hợp lệ!"},
{"ErridnInventory.InvF_InventoryReturnSup_SaveX_InvF_InventoryReturnSupInstLotTbl_LotNoExistDtl","Số Lô đã có trong danh sách!"},
{"ErridnInventory.InvF_InventoryReturnSup_SaveX_InvF_InventoryReturnSupInstSerialTbl_SerialNoExistInInv","Số Serial đã có trong phiếu!"},
{"ErridnInventory.InvF_InventoryReturnSup_SaveX_InvF_InventoryReturnSupInstSerialTbl_SerialNoExistDtl","Số Serial đã có trong danh sách!"},
{"ErridnInventory.InvF_InventoryReturnSup_Save","Lưu phiếu không thành công!"},
{"ErridnInventory.InvF_InventoryReturnSup_Appr","Duyệt phiếu không thành công!"},
{"ErridnInventory.InvF_InventoryReturnSup_Cancel","Hủy phiếu không thành công!"},
{"ErridnInventory.WAS_InvF_InventoryReturnSup_Get","Không lấy được thông tin phiếu!"},
{"ErridnInventory.WAS_InvF_InventoryReturnSup_Save","Lưu phiếu không thành công!"},
{"ErridnInventory.WAS_InvF_InventoryReturnSup_Appr","Duyệt phiếu không thành công!"},
{"ErridnInventory.WAS_InvF_InventoryReturnSup_Cancel","Hủy phiếu không thành công!"},
{"ErridnInventory.myCheck_InvF_InventoryReturnSupDtl_CheckQtyReturnOverQtyIn","Số lượng trả lại > Số lượng nhập!"},
{"ErridnInventory.myCheck_InvF_InventoryReturnSupInstLot_CheckQtyReturnOverQtyOut","Số lượng trả lại > Số lượng xuất!"},
{"ErridnInventory.myCheck_InvF_InventoryReturnSupInstSerial_CheckQtyReturnOverQtyOut","Số lượng trả lại > Số lượng xuất!"},
{"ErridnInventory.Rpt_InvF_WarehouseCard","Thẻ kho"},
{"ErridnInventory.WAS_Rpt_InvF_WarehouseCard","Thẻ kho"},
{"ErridnInventory.Rpt_Inv_InventoryBalance","Báo cáo tồn kho"},
{"ErridnInventory.WAS_Rpt_Inv_InventoryBalance","Báo cáo tồn kho"},
{"ErridnInventory.Rpt_Inventory_In_Out_Inv","Báo cáo nhập xuất tồn"},
{"ErridnInventory.WAS_Rpt_Inventory_In_Out_Inv","Báo cáo nhập xuất tồn"},
{"ErridnInventory.Rpt_In_Out_Inv_JobAuto",""},
{"ErridnInventory.WAS_Rpt_In_Out_Inv_JobAuto",""},
{"ErridnInventory.Rpt_Inv_InventoryBalance_LastUpdInvByProduct","Báo cáo hạn sử dụng hàng hóa"},
{"ErridnInventory.WAS_Rpt_Inv_InventoryBalance_LastUpdInvByProduct","Báo cáo hạn sử dụng hàng hóa"},
{"ErridnInventory.Rpt_Summary_InAndReturnSup",""},
{"ErridnInventory.WAS_Rpt_Summary_InAndReturnSup",""},
{"ErridnInventory.WAS_Rpt_Summary_QtyInvByPeriod",""},
{"ErridnInventory.Rpt_Summary_In_Out",""},
{"ErridnInventory.WAS_Rpt_Summary_In_Out",""},
{"ErridnInventory.myCheck_Mst_Inventory_CheckExistInvSub_InvSubNoExistInInvParent",""},
{"ErridnInventory.myCheck_Mst_Product_FlagLotOrSerial_ProductNoFlagSerial","Hàng hóa không gắn cờ Serial!"},
{"ErridnInventory.myCheck_Mst_Product_FlagLotOrSerial_ProductNoFlagLOT","Hàng hóa không gắn cờ Lot!"},
{"ErridnInventory.Mst_Product_CheckListDB_MstProductTbl_ProductCodeNotFound","Không tìm thấy mã hàng hóa!"},
{"ErridnInventory.Mst_Product_CheckListDB_MstProductTbl_ProductCodeFlagActiveNotMatch","Trạng thái hoạt động của hàng hóa không phù hợp!"},
{"ErridnInventory.Mst_Product_CheckListDB_MstProductTbl_InvalidProductType","Loại hàng hóa không hợp lệ!"},
{"ErridnInventory.myCheck_Mst_Product_UnitCode_MstProductTbl_UnitCodeNotEqualUnitCodeInMstProduct","Mã đơn vị không khớp với mã đơn vị trong menu hàng hóa!"},
{"ErridnInventory.Mst_Customer_Create_Input_Mst_CustomerInCustomerGroupTblNotFound","Không tìm thấy thông tin khách hàng trong nhóm khách hàng!"},
{"ErridnInventory.WAS_Mst_Customer_Get","Không lấy được thông tin khách hàng!"},
{"ErridnInventory.WAS_Mst_Customer_Create","Tạo mới khách hàng không thành công!"},
{"ErridnInventory.Mst_Customer_Create_InvalidOrgID","Mã tổ chức không hợp lệ!"},
{"ErridnInventory.Mst_Customer_Create_InvalidProductName","Tên sản phẩm không hợp lệ!"},
{"ErridnInventory.Mst_Customer_Create_Input_Mst_CustomerTblNotFound","Không tìm thấy thông tin khách hàng!"},
{"ErridnInventory.Mst_Customer_Create_Input_Mst_CustomerTblInvalid","Thông tin khách hàng không hợp lệ!"},
{"ErridnInventory.Mst_Customer_Create_Input_Prd_BOMTblNotFound","Không tìm thấy thông tin BOM!"},
{"ErridnInventory.Mst_Customer_Create_Input_UserOwner_CustomerTblNotFound","Không tìm thấy thông tin khách hàng!"},
{"ErridnInventory.Mst_Customer_Create_Input_Mst_CustomerImagesTblNotFound","Không tìm thấy thông tin hình ảnh khách hàng!"},
{"ErridnInventory.Mst_Customer_Create_Input_Mst_CustomerFilesTblNotFound","Không tìm thấy thông tin files đính kèm của khách hàng!"},
{"ErridnInventory.Mst_Customer_Create_InvalidProductCodeUK",""},
{"ErridnInventory.Mst_Customer_Create_InvalidCOMBO",""},
{"ErridnInventory.Mst_Customer_Update_InvalidOrgID","Mã tổ chức không hợp lệ!"},
{"ErridnInventory.Mst_Customer_Update_InvalidProductName","Tên sản phẩm không hợp lệ!"},
{"ErridnInventory.Mst_Customer_Update_Input_Mst_CustomerTblNotFound","Không tìm thấy thông tin khách hàng!"},
{"ErridnInventory.Mst_Customer_Update_Input_Mst_CustomerTblInvalid","Thông tin khách hàng không hợp lệ!"},
{"ErridnInventory.Mst_Customer_Update_Input_Prd_BOMTblNotFound","Không tìm thấy thông tin BOM!"},
{"ErridnInventory.Mst_Customer_Update_Input_UserOwner_CustomerTblNotFound","Không tìm thấy thông tin khách hàng!"},
{"ErridnInventory.Mst_Customer_Update_Input_Mst_CustomerImagesTblNotFound","Không tìm thấy thông tin hình ảnh khách hàng!"},
{"ErridnInventory.Mst_Customer_Update_Input_Mst_CustomerFilesTblNotFound","Không tìm thấy thông tin files đính kèm của khách hàng!"},
{"ErridnInventory.Mst_Customer_Update_InvalidProductCodeUK",""},
{"ErridnInventory.Mst_Customer_Update_InvalidCOMBO",""},
{"ErridnInventory.WAS_Mst_Customer_Update","Cập nhật khách hàng không thành công!"},
{"ErridnInventory.Mst_Customer_UpdateX","Cập nhật khách hàng không thành công!"},
{"ErridnInventory.Mst_Customer_UpdateX_InvalidProductName","Tên sản phẩm không hợp lệ!"},
{"ErridnInventory.WAS_Mst_Customer_Delete","Xóa khách hàng không thành công!"},
{"ErridnInventory.Mst_Customer_Delete_Input_Mst_CustomerTblNotFound","Không tìm thấy thông tin khách hàng!"},
{"ErridnInventory.Mst_Customer_Delete_Input_Mst_CustomerTblInvalid","Thông tin khách hàng không hợp lệ!"},
{"ErridnInventory.Mst_CustomerType_CheckDB_OrganNotFound","Không tìm thấy tổ chức!"},
{"ErridnInventory.Mst_CustomerType_CheckDB_OrganExist","Tổ chức đã tồn tại!"},
{"ErridnInventory.WAS_Mst_CustomerType_Get","Không lấy được thông tin loại khách hàng!"},
{"ErridnInventory.WAS_Mst_CustomerType_Create","Tạo loại khách hàng không thành công!"},
{"ErridnInventory.Mst_CustomerType_Create","Tạo loại khách hàng không thành công!"},
{"ErridnInventory.Mst_CustomerType_Create_InvalidCustomerType","Loại khách hàng không hợp lệ!"},
{"ErridnInventory.Mst_CustomerType_Create_InvalidOrganName","Tên tổ chức không hợp lệ!"},
{"ErridnInventory.Mst_CustomerType_Update","Cập nhật loại khách hàng không thành công!"},
{"ErridnInventory.WAS_Mst_CustomerType_Update","Cập nhật loại khách hàng không thành công!"},
{"ErridnInventory.Mst_CustomerType_UpdateX","Cập nhật loại khách hàng không thành công!"},
{"ErridnInventory.Mst_CustomerType_UpdateX_InvalidOrganName","Tên tổ chức không hợp lệ!"},
{"ErridnInventory.WAS_Mst_CustomerType_Delete","Xóa loại khách hàng không thành công!"},
{"ErridnInventory.Mst_CustomerType_Delete","Xóa loại khách hàng không thành công!"},
{"ErridnInventory.Mst_CustomerType_Create_Input_Mst_CustomerTypeImagesTblNotFound","Không tìm thấy thông tin ảnh của loại khách hàng!"},
{"ErridnInventory.Mst_CustomerGroup_CheckDB_OrganNotFound","Không tìm thấy tổ chức!"},
{"ErridnInventory.Mst_CustomerGroup_CheckDB_OrganExist","Tổ chức đã tồn tại!"},
{"ErridnInventory.Mst_CustomerGroup_CheckDB_FlagActiveNotMatched","Trạng thái hoạt động của nhóm khách hàng không phù hợp!"},
{"ErridnInventory.Mst_CustomerGroup_Get","Không lấy được thông tin nhóm khách hàng!"},
{"ErridnInventory.WAS_Mst_CustomerGroup_Get","Không lấy được thông tin nhóm khách hàng!"},
{"ErridnInventory.WAS_Mst_CustomerGroup_Create","Tạo nhóm khách hàng không thành công!"},
{"ErridnInventory.Mst_CustomerGroup_Create","Tạo nhóm khách hàng không thành công!"},
{"ErridnInventory.Mst_CustomerGroup_Create_InvalidOrgID","Mã tổ chức không hợp lệ!"},
{"ErridnInventory.Mst_CustomerGroup_Create_InvalidOrganName","Tên tổ chức không hợp lệ!"},
{"ErridnInventory.Mst_CustomerGroup_Update","Cập nhật nhóm khách hàng không thành công!"},
{"ErridnInventory.WAS_Mst_CustomerGroup_Update","Cập nhật nhóm khách hàng không thành công!"},
{"ErridnInventory.Mst_CustomerGroup_UpdateX","Cập nhật nhóm khách hàng không thành công!"},
{"ErridnInventory.Mst_CustomerGroup_UpdateX_InvalidOrganName","Tên chi nhánh không hợp lệ!"},
{"ErridnInventory.WAS_Mst_CustomerGroup_Delete","Xóa nhóm khách hàng không thành công!"},
{"ErridnInventory.Mst_CustomerGroup_Delete","Xóa nhóm khách hàng không thành công!"},
{"ErridnInventory.Mst_CustomerType_Create_Input_Mst_CustomerGroupImagesTblNotFound","Không tìm thấy thông tin hình ảnh nhóm khách hàng!"},
{"ErridnInventory.Mst_CustomerSource_CheckDB_OrganNotFound","Không tìm thấy chi nhánh!"},
{"ErridnInventory.Mst_CustomerSource_CheckDB_OrganExist","Chi nhánh đã tồn tại!"},
{"ErridnInventory.Mst_CustomerSource_CheckDB_FlagActiveNotMatched","Trạng thái hoạt động của nguồn khách hàng không hợp lệ!"},
{"ErridnInventory.Mst_CustomerSource_Get","Không lấy được thông tin nguồn khách hàng!"},
{"ErridnInventory.WAS_Mst_CustomerSource_Get","Không lấy được thông tin nguồn khách hàng!"},
{"ErridnInventory.WAS_Mst_CustomerSource_Create","Tạo nguồn khách hàng không thành công!"},
{"ErridnInventory.Mst_CustomerSource_Create","Tạo nguồn khách hàng không thành công!"},
{"ErridnInventory.Mst_CustomerSource_Create_InvalidOrgID","Mã chi nhánh không hợp lệ!"},
{"ErridnInventory.Mst_CustomerSource_Create_InvalidOrganName","Tên chi nhánh không hợp lệ!"},
{"ErridnInventory.Mst_CustomerSource_Update","Cập nhật nguồn khách hàng không thành công!"},
{"ErridnInventory.WAS_Mst_CustomerSource_Update","Cập nhật nguồn khách hàng không thành công!"},
{"ErridnInventory.Mst_CustomerSource_UpdateX","Cập nhật nguồn khách hàng không thành công!"},
{"ErridnInventory.Mst_CustomerSource_UpdateX_InvalidOrganName","Tên chi nhánh không hợp lệ!"},
{"ErridnInventory.WAS_Mst_CustomerSource_Delete","Xóa nguồn khách hàng không thành công!"},
{"ErridnInventory.Mst_CustomerSource_Delete","Xóa nguồn khách hàng không thành công!"},
{"ErridnInventory.Mst_CustomerType_Create_Input_Mst_CustomerSourceImagesTblNotFound","Không tìm thấy thông tin hình ảnh nguồn khách hàng!"},
{"ErridnInventory.Mst_Area_CheckDB_AreaNotFound","Không tìm thấy khu vực!"},
{"ErridnInventory.Mst_Area_CheckDB_AreaExist","Khu vực đã tồn tại!"},
{"ErridnInventory.Mst_Area_CheckDB_FlagActiveNotMatched","Trạng thái hoạt động của khu vực không hợp lệ!"},
{"ErridnInventory.Mst_Area_Get","Không lấy được thông tin khu vực!"},
{"ErridnInventory.WAS_Mst_Area_Get","Không lấy được thông tin khu vực!"},
{"ErridnInventory.WAS_Mst_Area_Create","Tạo khu vực mới không thành công!"},
{"ErridnInventory.Mst_Area_Create","Tạo khu vực mới không thành công!"},
{"ErridnInventory.Mst_Area_Create_InvalidOrgID","Mã chi nhánh không hợp lệ!"},
{"ErridnInventory.Mst_Area_Create_InvalidAreaName","Tên khu vực không hợp lệ!"},
{"ErridnInventory.Mst_Area_Update","Cập nhật khu vực không thành công!"},
{"ErridnInventory.WAS_Mst_Area_Update","Cập nhật khu vực không thành công!"},
{"ErridnInventory.Mst_Area_UpdateX","Cập nhật khu vực không thành công!"},
{"ErridnInventory.Mst_Area_UpdateX_InvalidAreaName","Tên khu vực không hợp lệ!"},
{"ErridnInventory.WAS_Mst_Area_Delete","Xóa khu vực không thành công!"},
{"ErridnInventory.Mst_Area_Delete","Xóa khu vực không thành công!"},
{"ErridnInventory.Customer_DynamicField_CheckDB_OrganNotFound","Không tìm thấy thông tin tổ chức!"},
{"ErridnInventory.Customer_DynamicField_CheckDB_OrganExist","Tổ chức đã tồn tại!"},
{"ErridnInventory.Customer_DynamicField_CheckDB_FlagActiveNotMatched","Trạng thái hoạt động không hợp lệ!"},
{"ErridnInventory.Customer_DynamicField_Get","Không lấy được thông tin trường động!"},
{"ErridnInventory.WAS_Customer_DynamicField_Get","Không lấy được thông tin trường động!"},
{"ErridnInventory.WAS_Customer_DynamicField_Create","Tạo mới không thành công!"},
{"ErridnInventory.Customer_DynamicField_Create","Tạo mới không thành công!"},
{"ErridnInventory.Customer_DynamicField_Create_InvalidOrgID","Mã chi nhánh không hợp lệ!"},
{"ErridnInventory.Customer_DynamicField_Create_InvalidOrganName","Tên chi nhánh không hợp lệ!"},
{"ErridnInventory.Customer_DynamicField_Update","Cập nhật không thành công!"},
{"ErridnInventory.WAS_Customer_DynamicField_Update","Cập nhật không thành công!"},
{"ErridnInventory.Customer_DynamicField_UpdateX","Cập nhật không thành công!"},
{"ErridnInventory.Customer_DynamicField_UpdateX_InvalidOrganName","Tên chi nhánh không hợp lệ!"},
{"ErridnInventory.WAS_Customer_DynamicField_Delete","Xóa không thành công!"},
{"ErridnInventory.Customer_DynamicField_Delete","Xóa không thành công!"},
{"ErridnInventory.Inv_InventoryBalanceCustomer_UpdQtyReturn_NoExistInvFOut","Không tồn tại phiếu xuất!"},
{"ErridnInventory.Inv_InventoryBalanceCustomer_UpdQtyReturn_NoExistInvFIn","Không tồn tại phiếu nhập!"},
{"ErridnInventory.Inv_InventoryBalanceCustomer_UpdQtyReturn_QtyBaseReturnOverQtyRemainIn","Số lượng trả > số lượng còn lại"},
{"ErridnInventory.Inv_InventoryBalanceCustomer_UpdQtyReturn_SerialRetuntedOrNoExist","Serial đã trả hoặc không tồn tại!"},
{"ErrProductCenter.Mst_ProductType_CheckDB_ProductTypeNotFound","Không tìm thấy loại hàng hóa!"},
{"ErrProductCenter.Mst_ProductType_CheckDB_ProductTypeExist","Loại hàng hóa đã tồn tại!"},
{"ErrProductCenter.Mst_ProductType_CheckDB_FlagActiveNotMatched","Trạng thái hoạt động của loại hàng hóa không phù hợp!"},
{"ErrProductCenter.Mst_ProductType_Get","Không lấy được thông tin loại hàng hóa!"},
{"ErrProductCenter.WAS_Mst_ProductType_Get","Không lấy được thông tin loại hàng hóa!"},
{"ErrProductCenter.WAS_Mst_ProductType_Create","Tạo loại hàng hóa không thành công!"},
{"ErrProductCenter.Mst_ProductType_Create","Tạo loại hàng hóa không thành công!"},
{"ErrProductCenter.Mst_ProductType_Create_InvalidProductType","Loại hàng hóa không hợp lệ!"},
{"ErrProductCenter.Mst_ProductType_Create_InvalidProductTypeName","Tên loại hàng hóa không hợp lệ!"},
{"ErrProductCenter.Mst_ProductType_Update","Cập nhật loại hàng hóa không thành công!"},
{"ErrProductCenter.WAS_Mst_ProductType_Update","Cập nhật loại hàng hóa không thành công!"},
{"ErrProductCenter.Mst_ProductType_UpdateX","Cập nhật loại hàng hóa không thành công!"},
{"ErrProductCenter.Mst_ProductType_UpdateX_InvalidProductTypeName","Tên loại hàng hóa không hợp lệ!"},
{"ErrProductCenter.WAS_Mst_ProductType_Delete","Xóa loại hàng hóa không thành công!"},
{"ErrProductCenter.Mst_ProductType_Delete","Xóa loại hàng hóa không thành công!"},
{"ErridnInventory.Sys_User_CheckAuthorize","Kiểm tra phân quyền người dùng!"},
{"ErridnInventory.Sys_User_CheckAuthorize_InvalidUserCode","Mã người dùng không hợp lệ!"},
{"ErridnInventory.Rpt_Inv_InventoryBalance_LastUpdInvByProductX","Báo cáo hạn sử dụng hàng hóa"},
{"ErridnInventory.Rpt_Inv_InventoryBalance_LastUpdInvByProductX_MstProductNotFound","Không tìm thấy hàng hóa"},
{"ErridnInventory.Rpt_Inv_InventoryBalance_LastUpdInvByProductX_MstProductTblInvalid","Hàng hóa không hợp lệ"},
{"ErridnInventory.Mst_TempPrintGroup_CheckDB_TempPrintTypeNotFound","Không tìm thấy loại mẫu in!"},
{"ErridnInventory.Mst_TempPrintGroup_CheckDB_TempPrintTypeExist","Loại mẫu in đã tồn tại!"},
{"ErridnInventory.Mst_TempPrintGroup_CheckDB_StatusNotMatched","Trạng thái nhóm mẫu in không phù hợp!"},
{"ErridnInventory.Mst_TempPrintGroup_Get","Không lấy được thông tin nhóm mẫu in!"},
{"ErridnInventory.WAS_Mst_TempPrintGroup_Get","Không lấy được thông tin nhóm mẫu in!"},
{"ErridnInventory.Mst_TempPrintGroup_SaveX_InvalidTempPrintType","Loại mẫu in không hợp lệ!"},
{"ErridnInventory.Mst_TempPrintGroup_Save","Lưu nhóm mẫu in không thành công!"},
{"ErridnInventory.WAS_Mst_TempPrintGroup_Save","Lưu nhóm mẫu in không thành công!"},
{"ErridnInventory.Mst_Attribute_Get","Không lấy được thông tin thuộc tính!"},
{"ErridnInventory.WAS_Mst_Attribute_Get","Không lấy được thông tin thuộc tính!"},
{"ErridnInventory.Mst_UserMapInventory_SaveX","Lưu người dùng được phân quyền kho không thành công!"},
{"ErridnInventory.Mst_UserMapInventoryX_Mst_UserMapInventoryTblNotFound","Không tìm thấy thông tin người dùng được phân quyền kho!"},
{"ErridnInventory.Mst_UserMapInventoryX_Mst_UserMapInventoryTblInvalid","Thông tin người dùng được phân quyền kho không hợp lệ!"},
{"ErridnInventory.Mst_UserMapInventory_Save","Lưu người dùng được phân quyền kho không thành công!"},
{"ErridnInventory.WAS_Mst_UserMapInventory_Save","Lưu người dùng được phân quyền kho không thành công!"},
{"ErridnInventory.Mst_UserMapInventory_Get","Không lấy được thông tin người dùng được phân quyền kho!"},
{"ErridnInventory.WAS_Mst_UserMapInventory_Get","Không lấy được thông tin người dùng được phân quyền kho!"},
{"ErridnInventory.Rpt_Summary_In_Out_Pivot",""},
{"ErridnInventory.Rpt_Summary_In_Out_Pivot_ProductNotFound","Không tìm thấy hàng hóa!"},
{"ErridnInventory.Rpt_Summary_In_Out_Pivot_InventoryNotFound","Không tìm thấy kho!"},
{"ErridnInventory.Rpt_Summary_In_Out_Pivot_ProductGroupNotFound","Không tìm thấy nhóm hàng hóa!"},
{"ErridnInventory.Rpt_Summary_In_Out_Pivot_CustomerNotFound","Không tìm thấy khách hàng!"},
{"ErridnInventory.Rpt_Summary_In_Out_Sup_Pivot",""},
{"ErridnInventory.WAS_Rpt_Summary_In_Out_Sup_Pivot",""},
{"ErridnInventory.WAS_Rpt_Summary_In_Out_Pivot",""},
{"ErridnInventory.Rpt_InvBalLot_MaxExpiredDateByInvX",""},
{"ErridnInventory.Rpt_InvBalLot_MaxExpiredDateByInvX_ProductNotFound","Không tìm thấy hàng hóa!"},
{"ErridnInventory.Rpt_InvBalLot_MaxExpiredDateByInvX_InventoryNotFound","Không tìm thấy kho!"},
{"ErridnInventory.Rpt_InvBalLot_MaxExpiredDateByInvX_ProductGroupNotFound","Không tìm thấy nhóm hàng hóa!"},
{"ErridnInventory.Rpt_InvBalLot_MaxExpiredDateByInv",""},
{"ErridnInventory.WAS_Rpt_InvBalLot_MaxExpiredDateByInv",""},
{"ErridnInventory.Rpt_Summary_In_Out_Sup_PivotSpecial",""},
{"ErridnInventory.WAS_Rpt_Summary_In_Out_Sup_PivotSpecial",""},
{"ErridnInventory.Mst_NotifyType_CheckDB_NotifyTypeFound","Không tìm thấy loại thông báo!"},
{"ErridnInventory.Mst_NotifyType_CheckDB_NotifyTypeExist","Loại thông báo đã tồn tại!"},
{"ErridnInventory.Mst_NotifyType_CheckDB_FlagActiveNotMatched","Trạng thái hoạt động của loại thông báo không hợp lệ!"},
{"ErridnInventory.Mst_NotifyType_Get","Không lấy được thông tin loại thông báo!"},
{"ErridnInventory.WAS_Mst_NotifyType_Get","Không lấy được thông tin loại thông báo!"},
{"ErridnInventory.WAS_Mst_NotifyType_Create","Tạo loại thông báo không thành công!"},
{"ErridnInventory.Mst_NotifyType_Create","Tạo loại thông báo không thành công!"},
{"ErridnInventory.Mst_NotifyType_Create_InvalidNotifyType","Loại thông báo không hợp lệ!"},
{"ErridnInventory.Mst_NotifyType_Create_InvalidNotifyTypeDesc",""},
{"ErridnInventory.Mst_NotifyType_Update","Cập nhật loại thông báo không thành công!"},
{"ErridnInventory.WAS_Mst_NotifyType_Update","Cập nhật loại thông báo không thành công!"},
{"ErridnInventory.Mst_NotifyType_UpdateX","Cập nhật loại thông báo không thành công!"},
{"ErridnInventory.Mst_NotifyType_UpdateX_InvalidOrganName","Tên tổ chức không hợp lệ!"},
{"ErridnInventory.WAS_Mst_NotifyType_Delete","Xóa loại thông báo không thành công!"},
{"ErridnInventory.Mst_NotifyType_Delete","Xóa loại thông báo không thành công!"},
{"ErridnInventory.Mst_ManageNotify_CheckDB_UserCodeNotFound","Không tìm thấy mã người dùng trong hệ thống!"},
{"ErridnInventory.Mst_ManageNotify_CheckDB_OrganExist","Tổ chức đã tồn tại!"},
{"ErridnInventory.Mst_ManageNotify_CheckDB_FlagActiveNotMatched","Trạng thái hoạt động không phù hợp!"},
{"ErridnInventory.Mst_ManageNotify_Get","Không lấy được thông tin quản lý thông báo!"},
{"ErridnInventory.WAS_Mst_ManageNotify_Get","Không lấy được thông tin quản lý thông báo!"},
{"ErridnInventory.WAS_Mst_ManageNotify_Create","Tạo quản lý thông báo không thành công!"},
{"ErridnInventory.Mst_ManageNotify_Create","Tạo quản lý thông báo không thành công!"},
{"ErridnInventory.Mst_ManageNotify_Create_InvalidUserCode","Mã người dùng không hợp lệ!"},
{"ErridnInventory.Mst_ManageNotify_Create_InvalidOrganName","Tên tổ chức không hợp lệ!"},
{"ErridnInventory.Mst_ManageNotify_Update","Cập nhật quản lý thông báo không thành công!"},
{"ErridnInventory.WAS_Mst_ManageNotify_Update","Cập nhật quản lý thông báo không thành công!"},
{"ErridnInventory.Mst_ManageNotify_UpdateX","Cập nhật quản lý thông báo không thành công!"},
{"ErridnInventory.Mst_ManageNotify_UpdateX_InvalidOrganName","Tên tổ chức không hợp lệ!"},
{"ErridnInventory.WAS_Mst_ManageNotify_Delete","Xóa quản lý thông báo không thành công!"},
{"ErridnInventory.Mst_ManageNotify_Delete","Xóa quản lý thông báo không thành công!"},
{"ErridnInventory.Map_UserInNotifyType_CheckDB_UserCodeNotFound","Không tìm thấy mã người dùng trong hệ thống!"},
{"ErridnInventory.Map_UserInNotifyType_CheckDB_UserCodeExist","Mã người dùng đã tồn tại!"},
{"ErridnInventory.Map_UserInNotifyType_CheckDB_FlagActiveNotMatched","Trạng thái hoạt động của người dùng không phù hợp!"},
{"ErridnInventory.Map_UserInNotifyType_Get","Không lấy được thông tin người dùng!"},
{"ErridnInventory.WAS_Map_UserInNotifyType_Get","Không lấy được thông tin người dùng!"},
{"ErridnInventory.WAS_Map_UserInNotifyType_Create","Tạo người dùng trong loại thông báo không thành công!"},
{"ErridnInventory.Map_UserInNotifyType_Create","Tạo người dùng trong loại thông báo không thành công!"},
{"ErridnInventory.Map_UserInNotifyType_Create_InvalidUserCode","Mã người dùng không hợp lệ!"},
{"ErridnInventory.Map_UserInNotifyType_Create_InvalidOrganName","Tên tổ chức không hợp lệ!"},
{"ErridnInventory.Map_UserInNotifyType_Update","Cập nhật người dùng trong loại thông báo không thành công!"},
{"ErridnInventory.WAS_Map_UserInNotifyType_Update","Cập nhật người dùng trong loại thông báo không thành công!"},
{"ErridnInventory.Map_UserInNotifyType_UpdateX","Cập nhật người dùng trong loại thông báo không thành công!"},
{"ErridnInventory.Map_UserInNotifyType_UpdateX_InvalidOrganName","Tên tổ chức không hợp lệ!"},
{"ErridnInventory.WAS_Map_UserInNotifyType_Delete","Xóa người dùng trong loại thông báo không thành công!"},
{"ErridnInventory.Map_UserInNotifyType_Delete","Xóa người dùng trong loại thông báo không thành công!"},
{"ErridnInventory.Map_UserInNotifyType_SaveX_Input_InvoiceTblNotFound","Không tìm thấy thông tin hóa đơn!"},
{"ErridnInventory.Map_UserInNotifyType_SaveX_Input_InvoiceTblInvalid","Thông tin hóa đơn không hợp lệ!"},
{"ErridnInventory.WAS_Map_UserInNotifyType_Save","Lưu người dùng trong loại thông báo không thành công!"},
{"ErridnInventory.Map_UserInNotifyType_Save","Lưu người dùng trong loại thông báo không thành công!"},
{"ErridnInventory.OS_MstSvPrdCenter_MstSv_Sys_User_Login","Đăng nhập không thành công!"},
{"ErridnInventory.WAS_OS_MstSvPrdCenter_MstSv_Sys_User_Login","Đăng nhập không thành công!"},
{"ErridnInventory.OS_MstSvTVAN20_MstSv_Seq_Common_Get","Không lấy được thông tin chung!"},
{"ErridnInventory.WAS_OS_MstSvTVAN20_MstSv_Seq_Common_Get","Không lấy được thông tin chung!"},
{"ErridnInventory.WAS_OS_MstSvTVAN_MstSv_Sys_User_Login","Đăng nhập không thành công!"},
{"ErridnInventory.OS_MstSvTVAN_MstSv_Sys_User_Login","Đăng nhập không thành công!"},
{"ErrProductCenter.Mst_Product_CheckDB_ProductNotFound","Không tìm thấy hàng hóa!"},
{"ErrProductCenter.Mst_Product_CheckDB_ProductExist","Hàng hóa đã tồn tại!"},
{"ErrProductCenter.Mst_Product_CheckDB_FlagActiveNotMatched","Trạng thái hoạt động của hàng hóa không phù hợp!"},
{"ErrProductCenter.Mst_Product_Get","Không lấy được thông tin hàng hóa!"},
{"ErrProductCenter.WAS_Mst_Product_Get","Không lấy được thông tin hàng hóa!"},
{"ErrProductCenter.WAS_Mst_Product_Create","Tạo mới hàng hóa không thành công!"},
{"ErrProductCenter.Mst_Product_Create","Tạo mới hàng hóa không thành công!"},
{"ErrProductCenter.Mst_Product_Create_InvalidOrgID","Mã chi nhánh không hợp lệ!"},
{"ErrProductCenter.Mst_Product_Create_InvalidProductName","Tên hàng hóa không hợp lệ!"},
{"ErrProductCenter.Mst_Product_Create_Input_Mst_ProductTblNotFound","Không tìm thấy thông tin hàng hóa!"},
{"ErrProductCenter.Mst_Product_Create_Input_Mst_ProductTblInvalid","Thông tin hàng hóa không hợp lệ!"},
{"ErrProductCenter.Mst_Product_Create_Input_Prd_BOMTblNotFound","Không tìm thấy thông tin BOM!"},
{"ErrProductCenter.Mst_Product_Create_Input_Prd_AttributeTblNotFound","Không tìm thấy thông tin thuộc tính!"},
{"ErrProductCenter.Mst_Product_Create_Input_Mst_ProductImagesTblNotFound","Không tìm thấy thông tin hình ảnh hàng hóa!"},
{"ErrProductCenter.Mst_Product_Create_Input_Mst_ProductFilesTblNotFound","Không tìm thấy thông tin trường hàng hóa!"},
{"ErrProductCenter.Mst_Product_Create_InvalidProductCodeUK",""},
{"ErrProductCenter.Mst_Product_Create_InvalidCOMBO","COMBO không hợp lệ!"},
{"ErrProductCenter.Mst_Product_Update","Cập nhật hàng hóa không thành công!"},
{"ErrProductCenter.Mst_Product_Update_InvalidOrgID","Mã chi nhánh không hợp lệ!"},
{"ErrProductCenter.Mst_Product_Update_InvalidProductName","Tên hàng hóa không hợp lệ!"},
{"ErrProductCenter.Mst_Product_Update_Input_Mst_ProductTblNotFound","Không tìm thấy thông tin hàng hóa!"},
{"ErrProductCenter.Mst_Product_Update_Input_Mst_ProductTblInvalid","Thông tin hàng hóa không hợp lệ!"},
{"ErrProductCenter.Mst_Product_Update_Input_Prd_BOMTblNotFound","Không tìm thấy thông tin BOM!"},
{"ErrProductCenter.Mst_Product_Update_Input_Prd_AttributeTblNotFound","Không tìm thấy thông tin thuộc tính!"},
{"ErrProductCenter.Mst_Product_Update_Input_Mst_ProductImagesTblNotFound","Không tìm thấy thông tin hình ảnh hàng hóa!"},
{"ErrProductCenter.Mst_Product_Update_Input_Mst_ProductFilesTblNotFound","Không tìm thấy thông tin trường hàng hóa!"},
{"ErrProductCenter.Mst_Product_Update_InvalidProductCodeUK",""},
{"ErrProductCenter.Mst_Product_Update_InvalidCOMBO","COMBO không hợp lệ!"},
{"ErrProductCenter.Mst_Product_Save","Lưu hàng hóa không thành công!"},
{"ErrProductCenter.Mst_Product_Save_InvalidOrgID","Mã chi nhánh không hợp lệ!"},
{"ErrProductCenter.Mst_Product_Save_InvalidProductName","Tên hàng hóa không hợp lệ!"},
{"ErrProductCenter.Mst_Product_Save_Input_Mst_ProductTblNotFound","Không tìm thấy thông tin hàng hóa!"},
{"ErrProductCenter.Mst_Product_Save_Input_Mst_ProductTblInvalid","Thông tin hàng hóa không hợp lệ!"},
{"ErrProductCenter.Mst_Product_Save_Input_Prd_BOMTblNotFound","Không tìm thấy thông tin BOM!"},
{"ErrProductCenter.Mst_Product_Save_Input_Prd_AttributeTblNotFound","Không tìm thấy thông tin thuộc tính!"},
{"ErrProductCenter.Mst_Product_Save_Input_Mst_ProductImagesTblNotFound","Không tìm thấy thông tin hình ảnh hàng hóa!"},
{"ErrProductCenter.Mst_Product_Save_Input_Mst_ProductFilesTblNotFound","Không tìm thấy thông tin trường hàng hóa!"},
{"ErrProductCenter.Mst_Product_Save_InvalidProductCodeUK",""},
{"ErrProductCenter.Mst_Product_Save_InvalidCOMBO","COMBO không hợp lệ!"},
{"ErrProductCenter.WAS_Mst_Product_Update","Cập nhật hàng hóa không thành công!"},
{"ErrProductCenter.WAS_Mst_Product_Save","Lưu hàng hóa không thành công!"},
{"ErrProductCenter.Mst_Product_UpdateX","Cập nhật hàng hóa không thành công!"},
{"ErrProductCenter.Mst_Product_UpdateX_InvalidProductName","Tên hàng hóa không hợp lệ!"},
{"ErrProductCenter.WAS_Mst_Product_Delete","Xóa hàng hóa không thành công!"},
{"ErrProductCenter.Mst_Product_Delete","Xóa hàng hóa không thành công!"},
{"ErrProductCenter.Mst_Product_Delete_Input_Mst_ProductTblNotFound","Không tìm thấy thông tin hàng hóa!"},
{"ErrProductCenter.Mst_Product_Delete_Input_Mst_ProductTblInvalid","Thông tin hàng hóa không hợp lệ!"},
{"ErridnInventory.Mst_Organ_CheckDB_OrganNotFound","Không tìm thấy chi nhánh!"},
{"ErridnInventory.Mst_Organ_CheckDB_OrganExist","Chi nhánh đã tồn tại!"},
{"ErridnInventory.Mst_Organ_CheckDB_FlagActiveNotMatched","Trạng thái hoạt động của chi nhánh không phù hợp!"},
{"ErridnInventory.Mst_Organ_Get","Không lấy được thông tin chi nhánh!"},
{"ErridnInventory.WAS_Mst_Organ_Get","Không lấy được thông tin chi nhánh!"},
{"ErridnInventory.Mst_Organ_GetForCurrentUser","Không lấy được thông tin người dùng hiện tại!"},
{"ErridnInventory.WAS_Mst_Organ_GetForCurrentUser","Không lấy được thông tin người dùng hiện tại!"},
{"ErridnInventory.WAS_Mst_Organ_Create","Tạo chi nhánh không thành công!"},
{"ErridnInventory.Mst_Organ_Create","Tạo chi nhánh không thành công!"},
{"ErridnInventory.Mst_Organ_Create_InvalidOrganCode","Mã chi nhánh không hợp lệ!"},
{"ErridnInventory.Mst_Organ_Create_InvalidOrganName","Tên chi nhánh không hợp lệ!"},
{"ErridnInventory.Mst_Organ_Update","Cập nhật chi nhánh không thành công!"},
{"ErridnInventory.WAS_Mst_Organ_Update","Cập nhật chi nhánh không thành công!"},
{"ErridnInventory.Mst_Organ_UpdateX","Cập nhật chi nhánh không thành công!"},
{"ErridnInventory.Mst_Organ_UpdateX_InvalidOrganName","Tên chi nhánh không hợp lệ!"},
{"ErridnInventory.WAS_Mst_Organ_Delete","Xóa chi nhánh không thành công!"},
{"ErridnInventory.Mst_Organ_Delete","Xóa chi nhánh không thành công!"},
{"ErridnInventory.Mst_Org_CheckDB_OrgNotFound","Không tìm thấy chi nhánh!"},
{"ErridnInventory.Mst_Org_CheckDB_OrgExist","Chi nhánh đã tồn tại!"},
{"ErridnInventory.Mst_Org_CheckDB_FlagActiveNotMatched","Trạng thái hoạt động của chi nhánh không phù hợp!"},
{"ErridnInventory.Mst_Org_Create","Tạo chi nhánh không thành công!"},
{"ErridnInventory.Mst_Org_Create_InvalidOrgID","Mã chi nhánh không hợp lệ!"},
{"ErridnInventory.RptSv_Sys_Group_CheckDB_GroupCodeNotFound","Không tìm thấy mã nhóm người dùng!"},
{"ErridnInventory.RptSv_Sys_Group_CheckDB_GroupCodeExist","Mã nhóm người dùng đã tồn tại!"},
{"ErridnInventory.RptSv_Sys_Group_CheckDB_FlagActiveNotMatched","Trạng thái hoạt động của nhóm người dùng không phù hợp!"},
{"ErridnInventory.RptSv_Sys_Group_Get","Không lấy được thông tin nhóm người dùng!"},
{"ErridnInventory.RptSv_Sys_Group_Create","Tạo nhóm người dùng không thành công!"},
{"ErridnInventory.RptSv_Sys_Group_Create_InvalidGroupCode","Mã nhóm người dùng không hợp lệ!"},
{"ErridnInventory.RptSv_Sys_Group_Create_InvalidGroupName","Tên nhóm người dùng không hợp lệ!"},
{"ErridnInventory.RptSv_Sys_Group_Update","Cập nhật nhóm người dùng không thành công!"},
{"ErridnInventory.RptSv_Sys_Group_Update_InvalidGroupName","Tên nhóm người dùng không hợp lệ!"},
{"ErridnInventory.RptSv_Sys_Group_Delete","Xóa nhóm người dùng không thành công!"},
{"ErridnInventory.WAS_RptSv_Sys_Group_Get","Không lấy được thông tin nhóm người dùng!"},
{"ErridnInventory.WAS_RptSv_Sys_Group_Create","Tạo nhóm người dùng không thành công!"},
{"ErridnInventory.WAS_RptSv_Sys_Group_Update","Cập nhật nhóm người dùng không thành công!"},
{"ErridnInventory.WAS_RptSv_Sys_Group_Delete","Xóa nhóm người dùng không thành công!"},
{"ErridnInventory.RptSv_Sys_UserInGroup_Save","Thêm người dùng vào nhóm không thành công!"},
{"ErridnInventory.RptSv_Sys_UserInGroup_Save_InputTblDtlNotFound","Không tìm thấy thông tin chi tiết đầu vào!"},
{"ErridnInventory.WAS_RptSv_Sys_UserInGroup_Save","Thêm người dùng vào nhóm không thành công!"},
{"ErridnInventory.RptSv_Sys_User_CheckDB_UserCodeNotFound","Không tìm thấy mã người dùng trong hệ thống!"},
{"ErridnInventory.RptSv_Sys_User_CheckDB_UserCodeExist","Mã người dùng đã tồn tại!"},
{"ErridnInventory.RptSv_Sys_User_CheckDB_FlagActiveNotMatched","Trạng thái hoạt động của người dùng không phù hợp!"},
{"ErridnInventory.RptSv_Sys_User_CheckDB_FlagSysAdminNotMatched","Cờ quản trị hệ thống không phù hợp!"},
{"ErridnInventory.RptSv_Sys_User_CheckDB_BizInvalidUserAbility","Khả năng của người dùng không hợp lệ!"},
{"ErridnInventory.RptSv_Sys_User_BizInvalidUserAbility","Khả năng của người dùng không hợp lệ!"},
{"ErridnInventory.RptSv_Sys_User_ChangePassword","Thay đổi mật khẩu không thành công!"},
{"ErridnInventory.RptSv_Sys_User_ChangePassword_InvalidPasswordOld","Mật khẩu cũ không hợp lệ!"},
{"ErridnInventory.RptSv_Sys_User_ChangePassword_InvalidPasswordNew","Mật khẩu mới không hợp lệ!"},
{"ErridnInventory.RptSv_Sys_User_ResetPassword","Đặt lại mật khẩu không thành công!"},
{"ErridnInventory.RptSv_Sys_User_GetForCurrentUser","Không lấy được thông tin người dùng hiện tại!"},
{"ErridnInventory.RptSv_Sys_User_Login","Đăng nhập không thành công!"},
{"ErridnInventory.RptSv_Sys_User_Login_InvalidLDAP",""},
{"ErridnInventory.RptSv_Sys_User_Login_Checking","Đang kiểm tra đăng nhập!"},
{"ErridnInventory.RptSv_Sys_User_Login_InvalidPassword","Mật khẩu không hợp lệ!"},
{"ErridnInventory.RptSv_Sys_User_CheckAuthentication","Kiểm tra xác thực!"},
{"ErridnInventory.RptSv_Sys_User_CheckAuthentication_InvalidPassword","Mật khẩu không hợp lệ!"},
{"ErridnInventory.RptSv_Sys_User_Get","Không lấy được thông tin người dùng!"},
{"ErridnInventory.RptSv_Sys_User_Get_01","Không lấy được thông tin người dùng 01!"},
{"ErridnInventory.WA_RptSv_Sys_User_Get","Không lấy được thông tin người dùng!"},
{"ErridnInventory.WAS_RptSv_Sys_User_Get","Không lấy được thông tin người dùng!"},
{"ErridnInventory.WAS_RptSv_Sys_User_GetForCurrentUser","Không lấy được thông tin người dùng hiện tại!"},
{"ErridnInventory.WAS_RptSv_Sys_User_Create","Tạo mới người dùng không thành công!"},
{"ErridnInventory.WAS_RptSv_Sys_User_ChangePassword","Thay đổi mật khẩu không thành công!"},
{"ErridnInventory.WAS_RptSv_Sys_User_Update","Cập nhật người dùng không thành công!"},
{"ErridnInventory.WAS_RptSv_Sys_User_Delete","Xóa người dùng không thành công!"},
{"ErridnInventory.WAS_RptSv_Sys_User_Login","Đăng nhập không thành công!"},
{"ErridnInventory.RptSv_Sys_User_Logout","Đăng xuất không thành công!"},
{"ErridnInventory.RptSv_Sys_User_GetByDB","Không lấy được thông tin người dùng bằng cơ sở dữ liệu!"},
{"ErridnInventory.RptSv_Sys_User_Create","Tạo mới người dùng không thành công!"},
{"ErridnInventory.RptSv_Sys_User_Create_InvalidUserCode","Mã người dùng không hợp lệ!"},
{"ErridnInventory.RptSv_Sys_User_Create_InvalidDBCode","Mã cơ sở dữ liệu không hợp lệ!"},
{"ErridnInventory.RptSv_Sys_User_Create_InvalidAreaCode","Mã khu vực không hợp lệ!"},
{"ErridnInventory.RptSv_Sys_User_Create_InvalidUserNick","Nick người dùng không hợp lệ!"},
{"ErridnInventory.RptSv_Sys_User_Create_InvalidUserName","Tên người dùng không hợp lệ!"},
{"ErridnInventory.RptSv_Sys_User_Create_InvalidUserPassword","Mật khẩu người dùng không hợp lệ!"},
{"ErridnInventory.RptSv_Sys_User_Create_InvalidFlagDLAdmin","Cờ quản trị đại lý không phù hợp!"},
{"ErridnInventory.RptSv_Sys_User_Create_InvalidFlagSysAdmin","Cờ quản trị hệ thống không phù hợp!"},
{"ErridnInventory.RptSv_Sys_User_Create_InvalidFlagDBAdmin","Cờ quản trị cơ sở dữ liệu không hợp lệ!"},
{"ErridnInventory.RptSv_Sys_User_Update","Cập nhật người dùng không thành công!"},
{"ErridnInventory.RptSv_Sys_User_Update_InvalidUserCode","Mã người dùng không hợp lệ!"},
{"ErridnInventory.RptSv_Sys_User_Update_InvalidDBCode","Mã cơ sở dữ liệu không hợp lệ!"},
{"ErridnInventory.RptSv_Sys_User_Update_InvalidAreaCode","Mã khu vực không hợp lệ!"},
{"ErridnInventory.RptSv_Sys_User_Update_InvalidUserName","Tên người dùng không hợp lệ!"},
{"ErridnInventory.RptSv_Sys_User_Update_InvalidUserPassword","Mật khẩu người dùng không hợp lệ!"},
{"ErridnInventory.RptSv_Sys_User_Update_InvalidFlagSysAdmin","Cờ quản trị hệ thống không hợp lệ!"},
{"ErridnInventory.RptSv_Sys_User_Update_InvalidFlagDBAdmin","Cờ quản trị cơ sở dữ liệu không hợp lệ!"},
{"ErridnInventory.RptSv_Sys_User_Delete","Xóa người dùng không thành công!"},
{"ErridnInventory.RptSv_Sys_Object_CheckDB_ObjectCodeNotFound",""},
{"ErridnInventory.RptSv_Sys_Object_CheckDB_ObjectCodeExist",""},
{"ErridnInventory.RptSv_Sys_Object_CheckDB_FlagActiveNotMatched",""},
{"ErridnInventory.RptSv_Sys_Object_Get",""},
{"ErridnInventory.RptSv_OS_Inos_Package_Get","Không lấy được thông tin gói hàng!"},
{"ErridnInventory.WAS_RptSv_OS_Inos_Package_Get","Không lấy được thông tin gói hàng!"},
{"ErridnInventory.Inos_OrgService_DeleteUser","Xóa người dùng không thành công!"},
{"ErridnInventory.Mst_NNT_Calc",""},
{"ErridnInventory.Mst_NNT_Calc_InvalidInosCreateUser",""},
{"ErridnInventory.Mst_NNT_Calc_InvalidInosCreateOrg",""},
{"ErridnInventory.Mst_NNT_Calc_InvalidRptSvMstNNtAdd",""},
{"ErridnInventory.Mst_NNT_Calc_InvalidInosCreateOrder",""},
{"ErridnInventory.Mst_NNT_Calc_InvalidInosCreateOrder_DiscountCodeNotFound",""},
{"ErridnInventory.Mst_NNT_Calc_InvalidInosCreateOrder_InvalidDiscountStatus",""},
{"ErridnInventory.RptSv_Inv_InventoryBalanceSerial_Get","Không lấy được thông tin Serial tồn kho!"},
{"ErridnInventory.WAS_RptSv_Inv_InventoryBalanceSerial_Get","Không lấy được thông tin Serial tồn kho!"},
{"ErridnInventory.RptSv_Rpt_Inv_InventoryBalanceSerialForSearch","Không tìm kiếm được Serial tồn kho!"},
{"ErridnInventory.WAS_RptSv_Rpt_Inv_InventoryBalanceSerialForSearchForSearch","Không tìm kiếm được Serial tồn kho!"},
                #endregion
            };
            errContent = errDict.ContainsKey(errCode) ? errDict[errCode] : "Lỗi!";

            return errContent;
        }


    }
}
