//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace idn.Skycic.Inventory.Biz.WSKQuaGDich {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://kquagdich.van.gdt.gov.vn/", ConfigurationName="WSKQuaGDich.KQuaGDichService")]
    public interface KQuaGDichService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        idn.Skycic.Inventory.Biz.WSKQuaGDich.traKQuaGDichResponse traKQuaGDich(idn.Skycic.Inventory.Biz.WSKQuaGDich.traKQuaGDichRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSKQuaGDich.traKQuaGDichResponse> traKQuaGDichAsync(idn.Skycic.Inventory.Biz.WSKQuaGDich.traKQuaGDichRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        idn.Skycic.Inventory.Biz.WSKQuaGDich.traKQuaPhienGDichResponse traKQuaPhienGDich(idn.Skycic.Inventory.Biz.WSKQuaGDich.traKQuaPhienGDichRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSKQuaGDich.traKQuaPhienGDichResponse> traKQuaPhienGDichAsync(idn.Skycic.Inventory.Biz.WSKQuaGDich.traKQuaPhienGDichRequest request);
        
        // CODEGEN: Parameter 'maSoThue' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        idn.Skycic.Inventory.Biz.WSKQuaGDich.traTTinMaSoThueResponse traTTinMaSoThue(idn.Skycic.Inventory.Biz.WSKQuaGDich.traTTinMaSoThueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSKQuaGDich.traTTinMaSoThueResponse> traTTinMaSoThueAsync(idn.Skycic.Inventory.Biz.WSKQuaGDich.traTTinMaSoThueRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        idn.Skycic.Inventory.Biz.WSKQuaGDich.traTThaiMaSoThueResponse traTThaiMaSoThue(idn.Skycic.Inventory.Biz.WSKQuaGDich.traTThaiMaSoThueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSKQuaGDich.traTThaiMaSoThueResponse> traTThaiMaSoThueAsync(idn.Skycic.Inventory.Biz.WSKQuaGDich.traTThaiMaSoThueRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        idn.Skycic.Inventory.Biz.WSKQuaGDich.traDanhMucResponse traDanhMuc(idn.Skycic.Inventory.Biz.WSKQuaGDich.traDanhMucRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSKQuaGDich.traDanhMucResponse> traDanhMucAsync(idn.Skycic.Inventory.Biz.WSKQuaGDich.traDanhMucRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        idn.Skycic.Inventory.Biz.WSKQuaGDich.traDsachTKhaiLoiResponse traDsachTKhaiLoi(idn.Skycic.Inventory.Biz.WSKQuaGDich.traDsachTKhaiLoiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSKQuaGDich.traDsachTKhaiLoiResponse> traDsachTKhaiLoiAsync(idn.Skycic.Inventory.Biz.WSKQuaGDich.traDsachTKhaiLoiRequest request);
        
        // CODEGEN: Parameter 'maGDich' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        idn.Skycic.Inventory.Biz.WSKQuaGDich.traTTinLoiTKhaiResponse traTTinLoiTKhai(idn.Skycic.Inventory.Biz.WSKQuaGDich.traTTinLoiTKhaiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSKQuaGDich.traTTinLoiTKhaiResponse> traTTinLoiTKhaiAsync(idn.Skycic.Inventory.Biz.WSKQuaGDich.traTTinLoiTKhaiRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="traKQuaGDich", WrapperNamespace="http://kquagdich.van.gdt.gov.vn/", IsWrapped=true)]
    public partial class traKQuaGDichRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kquagdich.van.gdt.gov.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string maGDich;
        
        public traKQuaGDichRequest() {
        }
        
        public traKQuaGDichRequest(string maGDich) {
            this.maGDich = maGDich;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="traKQuaGDichResponse", WrapperNamespace="http://kquagdich.van.gdt.gov.vn/", IsWrapped=true)]
    public partial class traKQuaGDichResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kquagdich.van.gdt.gov.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string @return;
        
        public traKQuaGDichResponse() {
        }
        
        public traKQuaGDichResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="traKQuaPhienGDich", WrapperNamespace="http://kquagdich.van.gdt.gov.vn/", IsWrapped=true)]
    public partial class traKQuaPhienGDichRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kquagdich.van.gdt.gov.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ngayGDich;
        
        public traKQuaPhienGDichRequest() {
        }
        
        public traKQuaPhienGDichRequest(string ngayGDich) {
            this.ngayGDich = ngayGDich;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="traKQuaPhienGDichResponse", WrapperNamespace="http://kquagdich.van.gdt.gov.vn/", IsWrapped=true)]
    public partial class traKQuaPhienGDichResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kquagdich.van.gdt.gov.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string @return;
        
        public traKQuaPhienGDichResponse() {
        }
        
        public traKQuaPhienGDichResponse(string @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kquagdich.services.van.ihtkk.seatechit/types")]
    public partial class viewTin : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fullNameField;
        
        private string tinField;
        
        private string payTaxOfficeIdField;
        
        private string payTaxOfficeNameField;
        
        private string payTaxOfficeAbbreviationField;
        
        private string depaIdField;
        
        private string emailField;
        
        private string telField;
        
        private string faxField;
        
        private string provField;
        
        private string distField;
        
        private string addrField;
        
        private string certSerialNumberField;
        
        private string finaStartDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
                this.RaisePropertyChanged("fullName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string tin {
            get {
                return this.tinField;
            }
            set {
                this.tinField = value;
                this.RaisePropertyChanged("tin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string payTaxOfficeId {
            get {
                return this.payTaxOfficeIdField;
            }
            set {
                this.payTaxOfficeIdField = value;
                this.RaisePropertyChanged("payTaxOfficeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string payTaxOfficeName {
            get {
                return this.payTaxOfficeNameField;
            }
            set {
                this.payTaxOfficeNameField = value;
                this.RaisePropertyChanged("payTaxOfficeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string payTaxOfficeAbbreviation {
            get {
                return this.payTaxOfficeAbbreviationField;
            }
            set {
                this.payTaxOfficeAbbreviationField = value;
                this.RaisePropertyChanged("payTaxOfficeAbbreviation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string depaId {
            get {
                return this.depaIdField;
            }
            set {
                this.depaIdField = value;
                this.RaisePropertyChanged("depaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string tel {
            get {
                return this.telField;
            }
            set {
                this.telField = value;
                this.RaisePropertyChanged("tel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
                this.RaisePropertyChanged("fax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string prov {
            get {
                return this.provField;
            }
            set {
                this.provField = value;
                this.RaisePropertyChanged("prov");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string dist {
            get {
                return this.distField;
            }
            set {
                this.distField = value;
                this.RaisePropertyChanged("dist");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string addr {
            get {
                return this.addrField;
            }
            set {
                this.addrField = value;
                this.RaisePropertyChanged("addr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string certSerialNumber {
            get {
                return this.certSerialNumberField;
            }
            set {
                this.certSerialNumberField = value;
                this.RaisePropertyChanged("certSerialNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string finaStartDate {
            get {
                return this.finaStartDateField;
            }
            set {
                this.finaStartDateField = value;
                this.RaisePropertyChanged("finaStartDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kquagdich.services.van.ihtkk.seatechit/types")]
    public partial class mesgTKError : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tthaiField;
        
        private string tbaoloiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string tthai {
            get {
                return this.tthaiField;
            }
            set {
                this.tthaiField = value;
                this.RaisePropertyChanged("tthai");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI", Order=1)]
        public string tbaoloi {
            get {
                return this.tbaoloiField;
            }
            set {
                this.tbaoloiField = value;
                this.RaisePropertyChanged("tbaoloi");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="traTTinMaSoThue", WrapperNamespace="http://kquagdich.van.gdt.gov.vn/", IsWrapped=true)]
    public partial class traTTinMaSoThueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kquagdich.van.gdt.gov.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string maSoThue;
        
        public traTTinMaSoThueRequest() {
        }
        
        public traTTinMaSoThueRequest(string maSoThue) {
            this.maSoThue = maSoThue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="traTTinMaSoThueResponse", WrapperNamespace="http://kquagdich.van.gdt.gov.vn/", IsWrapped=true)]
    public partial class traTTinMaSoThueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kquagdich.van.gdt.gov.vn/", Order=0)]
        public idn.Skycic.Inventory.Biz.WSKQuaGDich.viewTin @return;
        
        public traTTinMaSoThueResponse() {
        }
        
        public traTTinMaSoThueResponse(idn.Skycic.Inventory.Biz.WSKQuaGDich.viewTin @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="traTThaiMaSoThue", WrapperNamespace="http://kquagdich.van.gdt.gov.vn/", IsWrapped=true)]
    public partial class traTThaiMaSoThueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kquagdich.van.gdt.gov.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string maSoThue;
        
        public traTThaiMaSoThueRequest() {
        }
        
        public traTThaiMaSoThueRequest(string maSoThue) {
            this.maSoThue = maSoThue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="traTThaiMaSoThueResponse", WrapperNamespace="http://kquagdich.van.gdt.gov.vn/", IsWrapped=true)]
    public partial class traTThaiMaSoThueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kquagdich.van.gdt.gov.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public traTThaiMaSoThueResponse() {
        }
        
        public traTThaiMaSoThueResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="traDanhMuc", WrapperNamespace="http://kquagdich.van.gdt.gov.vn/", IsWrapped=true)]
    public partial class traDanhMucRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kquagdich.van.gdt.gov.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string maLoaiDMuc;
        
        public traDanhMucRequest() {
        }
        
        public traDanhMucRequest(string maLoaiDMuc) {
            this.maLoaiDMuc = maLoaiDMuc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="traDanhMucResponse", WrapperNamespace="http://kquagdich.van.gdt.gov.vn/", IsWrapped=true)]
    public partial class traDanhMucResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kquagdich.van.gdt.gov.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string @return;
        
        public traDanhMucResponse() {
        }
        
        public traDanhMucResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="traDsachTKhaiLoi", WrapperNamespace="http://kquagdich.van.gdt.gov.vn/", IsWrapped=true)]
    public partial class traDsachTKhaiLoiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kquagdich.van.gdt.gov.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ngayTraLoi;
        
        public traDsachTKhaiLoiRequest() {
        }
        
        public traDsachTKhaiLoiRequest(string ngayTraLoi) {
            this.ngayTraLoi = ngayTraLoi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="traDsachTKhaiLoiResponse", WrapperNamespace="http://kquagdich.van.gdt.gov.vn/", IsWrapped=true)]
    public partial class traDsachTKhaiLoiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kquagdich.van.gdt.gov.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string @return;
        
        public traDsachTKhaiLoiResponse() {
        }
        
        public traDsachTKhaiLoiResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="traTTinLoiTKhai", WrapperNamespace="http://kquagdich.van.gdt.gov.vn/", IsWrapped=true)]
    public partial class traTTinLoiTKhaiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kquagdich.van.gdt.gov.vn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string maGDich;
        
        public traTTinLoiTKhaiRequest() {
        }
        
        public traTTinLoiTKhaiRequest(string maGDich) {
            this.maGDich = maGDich;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="traTTinLoiTKhaiResponse", WrapperNamespace="http://kquagdich.van.gdt.gov.vn/", IsWrapped=true)]
    public partial class traTTinLoiTKhaiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kquagdich.van.gdt.gov.vn/", Order=0)]
        public idn.Skycic.Inventory.Biz.WSKQuaGDich.mesgTKError @return;
        
        public traTTinLoiTKhaiResponse() {
        }
        
        public traTTinLoiTKhaiResponse(idn.Skycic.Inventory.Biz.WSKQuaGDich.mesgTKError @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KQuaGDichServiceChannel : idn.Skycic.Inventory.Biz.WSKQuaGDich.KQuaGDichService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KQuaGDichServiceClient : System.ServiceModel.ClientBase<idn.Skycic.Inventory.Biz.WSKQuaGDich.KQuaGDichService>, idn.Skycic.Inventory.Biz.WSKQuaGDich.KQuaGDichService {
        
        public KQuaGDichServiceClient() {
        }
        
        public KQuaGDichServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KQuaGDichServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KQuaGDichServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KQuaGDichServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        idn.Skycic.Inventory.Biz.WSKQuaGDich.traKQuaGDichResponse idn.Skycic.Inventory.Biz.WSKQuaGDich.KQuaGDichService.traKQuaGDich(idn.Skycic.Inventory.Biz.WSKQuaGDich.traKQuaGDichRequest request) {
            return base.Channel.traKQuaGDich(request);
        }
        
        public string traKQuaGDich(string maGDich) {
            idn.Skycic.Inventory.Biz.WSKQuaGDich.traKQuaGDichRequest inValue = new idn.Skycic.Inventory.Biz.WSKQuaGDich.traKQuaGDichRequest();
            inValue.maGDich = maGDich;
            idn.Skycic.Inventory.Biz.WSKQuaGDich.traKQuaGDichResponse retVal = ((idn.Skycic.Inventory.Biz.WSKQuaGDich.KQuaGDichService)(this)).traKQuaGDich(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSKQuaGDich.traKQuaGDichResponse> idn.Skycic.Inventory.Biz.WSKQuaGDich.KQuaGDichService.traKQuaGDichAsync(idn.Skycic.Inventory.Biz.WSKQuaGDich.traKQuaGDichRequest request) {
            return base.Channel.traKQuaGDichAsync(request);
        }
        
        public System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSKQuaGDich.traKQuaGDichResponse> traKQuaGDichAsync(string maGDich) {
            idn.Skycic.Inventory.Biz.WSKQuaGDich.traKQuaGDichRequest inValue = new idn.Skycic.Inventory.Biz.WSKQuaGDich.traKQuaGDichRequest();
            inValue.maGDich = maGDich;
            return ((idn.Skycic.Inventory.Biz.WSKQuaGDich.KQuaGDichService)(this)).traKQuaGDichAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        idn.Skycic.Inventory.Biz.WSKQuaGDich.traKQuaPhienGDichResponse idn.Skycic.Inventory.Biz.WSKQuaGDich.KQuaGDichService.traKQuaPhienGDich(idn.Skycic.Inventory.Biz.WSKQuaGDich.traKQuaPhienGDichRequest request) {
            return base.Channel.traKQuaPhienGDich(request);
        }
        
        public string traKQuaPhienGDich(string ngayGDich) {
            idn.Skycic.Inventory.Biz.WSKQuaGDich.traKQuaPhienGDichRequest inValue = new idn.Skycic.Inventory.Biz.WSKQuaGDich.traKQuaPhienGDichRequest();
            inValue.ngayGDich = ngayGDich;
            idn.Skycic.Inventory.Biz.WSKQuaGDich.traKQuaPhienGDichResponse retVal = ((idn.Skycic.Inventory.Biz.WSKQuaGDich.KQuaGDichService)(this)).traKQuaPhienGDich(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSKQuaGDich.traKQuaPhienGDichResponse> idn.Skycic.Inventory.Biz.WSKQuaGDich.KQuaGDichService.traKQuaPhienGDichAsync(idn.Skycic.Inventory.Biz.WSKQuaGDich.traKQuaPhienGDichRequest request) {
            return base.Channel.traKQuaPhienGDichAsync(request);
        }
        
        public System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSKQuaGDich.traKQuaPhienGDichResponse> traKQuaPhienGDichAsync(string ngayGDich) {
            idn.Skycic.Inventory.Biz.WSKQuaGDich.traKQuaPhienGDichRequest inValue = new idn.Skycic.Inventory.Biz.WSKQuaGDich.traKQuaPhienGDichRequest();
            inValue.ngayGDich = ngayGDich;
            return ((idn.Skycic.Inventory.Biz.WSKQuaGDich.KQuaGDichService)(this)).traKQuaPhienGDichAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        idn.Skycic.Inventory.Biz.WSKQuaGDich.traTTinMaSoThueResponse idn.Skycic.Inventory.Biz.WSKQuaGDich.KQuaGDichService.traTTinMaSoThue(idn.Skycic.Inventory.Biz.WSKQuaGDich.traTTinMaSoThueRequest request) {
            return base.Channel.traTTinMaSoThue(request);
        }
        
        public idn.Skycic.Inventory.Biz.WSKQuaGDich.viewTin traTTinMaSoThue(string maSoThue) {
            idn.Skycic.Inventory.Biz.WSKQuaGDich.traTTinMaSoThueRequest inValue = new idn.Skycic.Inventory.Biz.WSKQuaGDich.traTTinMaSoThueRequest();
            inValue.maSoThue = maSoThue;
            idn.Skycic.Inventory.Biz.WSKQuaGDich.traTTinMaSoThueResponse retVal = ((idn.Skycic.Inventory.Biz.WSKQuaGDich.KQuaGDichService)(this)).traTTinMaSoThue(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSKQuaGDich.traTTinMaSoThueResponse> idn.Skycic.Inventory.Biz.WSKQuaGDich.KQuaGDichService.traTTinMaSoThueAsync(idn.Skycic.Inventory.Biz.WSKQuaGDich.traTTinMaSoThueRequest request) {
            return base.Channel.traTTinMaSoThueAsync(request);
        }
        
        public System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSKQuaGDich.traTTinMaSoThueResponse> traTTinMaSoThueAsync(string maSoThue) {
            idn.Skycic.Inventory.Biz.WSKQuaGDich.traTTinMaSoThueRequest inValue = new idn.Skycic.Inventory.Biz.WSKQuaGDich.traTTinMaSoThueRequest();
            inValue.maSoThue = maSoThue;
            return ((idn.Skycic.Inventory.Biz.WSKQuaGDich.KQuaGDichService)(this)).traTTinMaSoThueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        idn.Skycic.Inventory.Biz.WSKQuaGDich.traTThaiMaSoThueResponse idn.Skycic.Inventory.Biz.WSKQuaGDich.KQuaGDichService.traTThaiMaSoThue(idn.Skycic.Inventory.Biz.WSKQuaGDich.traTThaiMaSoThueRequest request) {
            return base.Channel.traTThaiMaSoThue(request);
        }
        
        public string traTThaiMaSoThue(string maSoThue) {
            idn.Skycic.Inventory.Biz.WSKQuaGDich.traTThaiMaSoThueRequest inValue = new idn.Skycic.Inventory.Biz.WSKQuaGDich.traTThaiMaSoThueRequest();
            inValue.maSoThue = maSoThue;
            idn.Skycic.Inventory.Biz.WSKQuaGDich.traTThaiMaSoThueResponse retVal = ((idn.Skycic.Inventory.Biz.WSKQuaGDich.KQuaGDichService)(this)).traTThaiMaSoThue(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSKQuaGDich.traTThaiMaSoThueResponse> idn.Skycic.Inventory.Biz.WSKQuaGDich.KQuaGDichService.traTThaiMaSoThueAsync(idn.Skycic.Inventory.Biz.WSKQuaGDich.traTThaiMaSoThueRequest request) {
            return base.Channel.traTThaiMaSoThueAsync(request);
        }
        
        public System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSKQuaGDich.traTThaiMaSoThueResponse> traTThaiMaSoThueAsync(string maSoThue) {
            idn.Skycic.Inventory.Biz.WSKQuaGDich.traTThaiMaSoThueRequest inValue = new idn.Skycic.Inventory.Biz.WSKQuaGDich.traTThaiMaSoThueRequest();
            inValue.maSoThue = maSoThue;
            return ((idn.Skycic.Inventory.Biz.WSKQuaGDich.KQuaGDichService)(this)).traTThaiMaSoThueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        idn.Skycic.Inventory.Biz.WSKQuaGDich.traDanhMucResponse idn.Skycic.Inventory.Biz.WSKQuaGDich.KQuaGDichService.traDanhMuc(idn.Skycic.Inventory.Biz.WSKQuaGDich.traDanhMucRequest request) {
            return base.Channel.traDanhMuc(request);
        }
        
        public string traDanhMuc(string maLoaiDMuc) {
            idn.Skycic.Inventory.Biz.WSKQuaGDich.traDanhMucRequest inValue = new idn.Skycic.Inventory.Biz.WSKQuaGDich.traDanhMucRequest();
            inValue.maLoaiDMuc = maLoaiDMuc;
            idn.Skycic.Inventory.Biz.WSKQuaGDich.traDanhMucResponse retVal = ((idn.Skycic.Inventory.Biz.WSKQuaGDich.KQuaGDichService)(this)).traDanhMuc(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSKQuaGDich.traDanhMucResponse> idn.Skycic.Inventory.Biz.WSKQuaGDich.KQuaGDichService.traDanhMucAsync(idn.Skycic.Inventory.Biz.WSKQuaGDich.traDanhMucRequest request) {
            return base.Channel.traDanhMucAsync(request);
        }
        
        public System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSKQuaGDich.traDanhMucResponse> traDanhMucAsync(string maLoaiDMuc) {
            idn.Skycic.Inventory.Biz.WSKQuaGDich.traDanhMucRequest inValue = new idn.Skycic.Inventory.Biz.WSKQuaGDich.traDanhMucRequest();
            inValue.maLoaiDMuc = maLoaiDMuc;
            return ((idn.Skycic.Inventory.Biz.WSKQuaGDich.KQuaGDichService)(this)).traDanhMucAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        idn.Skycic.Inventory.Biz.WSKQuaGDich.traDsachTKhaiLoiResponse idn.Skycic.Inventory.Biz.WSKQuaGDich.KQuaGDichService.traDsachTKhaiLoi(idn.Skycic.Inventory.Biz.WSKQuaGDich.traDsachTKhaiLoiRequest request) {
            return base.Channel.traDsachTKhaiLoi(request);
        }
        
        public string traDsachTKhaiLoi(string ngayTraLoi) {
            idn.Skycic.Inventory.Biz.WSKQuaGDich.traDsachTKhaiLoiRequest inValue = new idn.Skycic.Inventory.Biz.WSKQuaGDich.traDsachTKhaiLoiRequest();
            inValue.ngayTraLoi = ngayTraLoi;
            idn.Skycic.Inventory.Biz.WSKQuaGDich.traDsachTKhaiLoiResponse retVal = ((idn.Skycic.Inventory.Biz.WSKQuaGDich.KQuaGDichService)(this)).traDsachTKhaiLoi(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSKQuaGDich.traDsachTKhaiLoiResponse> idn.Skycic.Inventory.Biz.WSKQuaGDich.KQuaGDichService.traDsachTKhaiLoiAsync(idn.Skycic.Inventory.Biz.WSKQuaGDich.traDsachTKhaiLoiRequest request) {
            return base.Channel.traDsachTKhaiLoiAsync(request);
        }
        
        public System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSKQuaGDich.traDsachTKhaiLoiResponse> traDsachTKhaiLoiAsync(string ngayTraLoi) {
            idn.Skycic.Inventory.Biz.WSKQuaGDich.traDsachTKhaiLoiRequest inValue = new idn.Skycic.Inventory.Biz.WSKQuaGDich.traDsachTKhaiLoiRequest();
            inValue.ngayTraLoi = ngayTraLoi;
            return ((idn.Skycic.Inventory.Biz.WSKQuaGDich.KQuaGDichService)(this)).traDsachTKhaiLoiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        idn.Skycic.Inventory.Biz.WSKQuaGDich.traTTinLoiTKhaiResponse idn.Skycic.Inventory.Biz.WSKQuaGDich.KQuaGDichService.traTTinLoiTKhai(idn.Skycic.Inventory.Biz.WSKQuaGDich.traTTinLoiTKhaiRequest request) {
            return base.Channel.traTTinLoiTKhai(request);
        }
        
        public idn.Skycic.Inventory.Biz.WSKQuaGDich.mesgTKError traTTinLoiTKhai(string maGDich) {
            idn.Skycic.Inventory.Biz.WSKQuaGDich.traTTinLoiTKhaiRequest inValue = new idn.Skycic.Inventory.Biz.WSKQuaGDich.traTTinLoiTKhaiRequest();
            inValue.maGDich = maGDich;
            idn.Skycic.Inventory.Biz.WSKQuaGDich.traTTinLoiTKhaiResponse retVal = ((idn.Skycic.Inventory.Biz.WSKQuaGDich.KQuaGDichService)(this)).traTTinLoiTKhai(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSKQuaGDich.traTTinLoiTKhaiResponse> idn.Skycic.Inventory.Biz.WSKQuaGDich.KQuaGDichService.traTTinLoiTKhaiAsync(idn.Skycic.Inventory.Biz.WSKQuaGDich.traTTinLoiTKhaiRequest request) {
            return base.Channel.traTTinLoiTKhaiAsync(request);
        }
        
        public System.Threading.Tasks.Task<idn.Skycic.Inventory.Biz.WSKQuaGDich.traTTinLoiTKhaiResponse> traTTinLoiTKhaiAsync(string maGDich) {
            idn.Skycic.Inventory.Biz.WSKQuaGDich.traTTinLoiTKhaiRequest inValue = new idn.Skycic.Inventory.Biz.WSKQuaGDich.traTTinLoiTKhaiRequest();
            inValue.maGDich = maGDich;
            return ((idn.Skycic.Inventory.Biz.WSKQuaGDich.KQuaGDichService)(this)).traTTinLoiTKhaiAsync(inValue);
        }
    }
}
